// packages/react/src/components/card.tsx
import * as React from "react";
import { Slot } from "@radix-ui/react-slot";
import { cardVariants, type VariantProps } from "@bpdm/variants";
import { cn } from "@/lib/utils";

export interface CardProps
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof cardVariants> {
  /** Render as the child element (e.g. an <a> for a fully-clickable card). */
  asChild?: boolean;
}

export const Card = React.forwardRef<HTMLDivElement, CardProps>(
  (
    { className, variant, hoverable, interactive, asChild = false, role, tabIndex, onKeyDown, ...props },
    ref,
  ) => {
    const Comp = asChild ? Slot : "div";
    // An `interactive` card renders hover/press affordances, so it must be a real,
    // keyboard-operable control — focusable (tabIndex=0), `role="button"`, and
    // Enter/Space activation. When `asChild`, the consumer's own <a>/<button> child
    // already carries the semantics, so we leave those untouched.
    const keyboardable = interactive && !asChild;
    const handleKeyDown = (e: React.KeyboardEvent<HTMLDivElement>) => {
      onKeyDown?.(e);
      if (!keyboardable || e.defaultPrevented) return;
      // only self-activate — never hijack Enter/Space aimed at a nested control
      if (e.target !== e.currentTarget) return;
      if (e.key === "Enter" || e.key === " " || e.key === "Spacebar") {
        e.preventDefault();
        e.currentTarget.click();
      }
    };
    return (
      <Comp
        ref={ref}
        role={keyboardable ? (role ?? "button") : role}
        tabIndex={keyboardable ? (tabIndex ?? 0) : tabIndex}
        onKeyDown={handleKeyDown}
        data-bpdm="" data-bpdm-slot="card"
        className={cn(cardVariants({ variant, hoverable, interactive }), className)}
        {...props}
      />
    );
  },
);
Card.displayName = "Card";

const ASPECT: Record<string, string> = {
  video: "aspect-video",
  square: "aspect-square",
  wide: "aspect-[21/9]",
  auto: "",
};

export interface CardMediaProps extends React.HTMLAttributes<HTMLDivElement> {
  src?: string;
  alt?: string;
  /** Aspect ratio of the media band. Default "video" (16:9). */
  aspect?: keyof typeof ASPECT;
  /** Dark gradient scrim at the bottom (for text/badges placed over the media). */
  overlay?: boolean;
}

/** Edge-to-edge media band at the top of a card; the image zooms on card hover. */
export const CardMedia = React.forwardRef<HTMLDivElement, CardMediaProps>(
  ({ className, src, alt, aspect = "video", overlay = false, children, ...props }, ref) => (
    <div ref={ref} data-bpdm-slot="card-media" className={cn("relative overflow-hidden bg-muted", ASPECT[aspect], className)} {...props}>
      {src ? (
        <img
          src={src}
          alt={alt ?? ""}
          className="size-full object-cover transition-transform duration-[500ms] ease-[cubic-bezier(0.22,1,0.36,1)] group-hover/card:scale-[1.06]"
        />
      ) : (
        children
      )}
      {overlay && (
        <div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-black/55 via-black/0 to-transparent" />
      )}
    </div>
  ),
);
CardMedia.displayName = "CardMedia";

export interface CardHeaderProps extends React.HTMLAttributes<HTMLDivElement> {
  /** Right-aligned slot (icon button, badge, menu…). */
  action?: React.ReactNode;
}

export const CardHeader = React.forwardRef<HTMLDivElement, CardHeaderProps>(
  ({ className, action, children, ...props }, ref) => (
    <div
      ref={ref}
      data-bpdm-slot="card-header"
      className={cn("flex items-start justify-between gap-4 px-5 pt-5", className)}
      {...props}
    >
      <div className="flex min-w-0 flex-col gap-1">{children}</div>
      {action && <div data-bpdm-slot="card-action" className="shrink-0">{action}</div>}
    </div>
  ),
);
CardHeader.displayName = "CardHeader";

export interface CardTitleProps extends React.HTMLAttributes<HTMLHeadingElement> {
  /** Heading level for the card title, for a correct document outline. Default `"h3"`. */
  as?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
}

export const CardTitle = React.forwardRef<HTMLHeadingElement, CardTitleProps>(
  ({ className, as: Tag = "h3", ...props }, ref) => (
    // `m-0` keeps the heading self-contained (no inherited host-page heading margin);
    // `as` lets you set the level so the card sits correctly in the document outline.
    <Tag
      ref={ref}
      data-bpdm-slot="card-title"
      className={cn("m-0 text-lg font-semibold leading-tight tracking-tight", className)}
      {...props}
    />
  ),
);
CardTitle.displayName = "CardTitle";

export const CardDescription = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLParagraphElement>
>(({ className, ...props }, ref) => (
  <p ref={ref} data-bpdm-slot="card-description" className={cn("m-0 text-sm text-muted-foreground", className)} {...props} />
));
CardDescription.displayName = "CardDescription";

export const CardContent = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    data-bpdm-slot="card-content"
    className={cn("px-5 py-4 text-sm leading-relaxed text-muted-foreground", className)}
    {...props}
  />
));
CardContent.displayName = "CardContent";

export interface CardFooterProps extends React.HTMLAttributes<HTMLDivElement> {
  /** Add a hairline divider above the footer. */
  divider?: boolean;
}

export const CardFooter = React.forwardRef<HTMLDivElement, CardFooterProps>(
  ({ className, divider = false, ...props }, ref) => (
    <div
      ref={ref}
      data-bpdm-slot="card-footer"
      className={cn(
        "mt-auto flex items-center gap-3 px-5 pb-5 pt-1",
        divider && "border-t border-border pt-4",
        className,
      )}
      {...props}
    />
  ),
);
CardFooter.displayName = "CardFooter";

export { cardVariants };

// packages/angular/src/lib/card/card.ts
import {
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  Directive,
  computed,
  ElementRef,
  inject,
  input,
} from "@angular/core";
import { cardVariants, cn, type CardVariants } from "@bpdm/variants";

/**
 * `<bpdm-card>` — a surface container. Compose it with the card parts:
 *
 * ```html
 * <bpdm-card variant="outlined" hoverable>
 *   <bpdm-card-header>
 *     <h3 bpdmCardTitle>Deployment</h3>
 *     <p bpdmCardDescription>Triggered 2 minutes ago</p>
 *     <button bpdmButton size="iconSm" variant="secondary" appearance="ghost" bpdmCardAction aria-label="Menu">⋯</button>
 *   </bpdm-card-header>
 *   <div bpdmCardContent>Build #482 is rolling out to production.</div>
 *   <div bpdmCardFooter divider><button bpdmButton size="sm">View logs</button></div>
 * </bpdm-card>
 * ```
 */
@Component({
  selector: "bpdm-card",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "data-bpdm": "",
    "data-bpdm-slot": "card",
    "[class]": "classes()",
    // An `interactive` card carries hover/press affordances, so it must be a
    // real, keyboard-operable control: focusable + role=button + Enter/Space.
    "[attr.role]": "interactive() ? 'button' : null",
    "[attr.tabindex]": "interactive() ? 0 : null",
    "(keydown)": "onKeyDown($event)",
  },
  template: `<ng-content />`,
})
export class BpdmCard {
  /** Surface style. */
  readonly variant = input<NonNullable<CardVariants["variant"]>>("elevated");
  /** Lift + deepen the shadow on hover. */
  readonly hoverable = input(false, { transform: booleanAttribute });
  /** Focusable + pressable (use for fully-clickable cards). */
  readonly interactive = input(false, { transform: booleanAttribute });
  /** Extra classes, merged with tailwind-merge. */
  readonly classInput = input<string>("", { alias: "class" });

  private readonly host = inject<ElementRef<HTMLElement>>(ElementRef);

  protected readonly classes = computed(() =>
    cn(
      cardVariants({
        variant: this.variant(),
        hoverable: this.hoverable(),
        interactive: this.interactive(),
      }),
      this.classInput(),
    ),
  );

  protected onKeyDown(e: KeyboardEvent): void {
    if (!this.interactive()) return;
    // only self-activate — never hijack Enter/Space aimed at a nested control
    if (e.target !== this.host.nativeElement) return;
    if (e.key === "Enter" || e.key === " " || e.key === "Spacebar") {
      e.preventDefault();
      this.host.nativeElement.click();
    }
  }
}

const ASPECTS: Record<string, string> = {
  video: "aspect-video",
  square: "aspect-square",
  wide: "aspect-[21/9]",
  auto: "",
};

/**
 * Edge-to-edge media band at the top (or side) of a card. Pass `src` for an
 * image (it zooms on card hover) or project your own content. `overlay` adds a
 * bottom scrim for text placed over the media.
 */
@Component({
  selector: "bpdm-card-media",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { "data-bpdm-slot": "card-media", "[class]": "hostClass()" },
  template: `
    @if (src()) {
      <img
        [src]="src()"
        [alt]="alt()"
        class="size-full object-cover transition-transform duration-[500ms] ease-[cubic-bezier(0.22,1,0.36,1)] group-hover/card:scale-[1.06]"
      />
    } @else {
      <ng-content />
    }
    @if (overlay()) {
      <div
        class="pointer-events-none absolute inset-0 bg-gradient-to-t from-black/55 via-black/0 to-transparent"
      ></div>
    }
  `,
})
export class BpdmCardMedia {
  /** Image URL; omit to project custom content instead. */
  readonly src = input<string>();
  readonly alt = input("");
  /** Aspect ratio of the band. Default `video` (16:9). */
  readonly aspect = input<keyof typeof ASPECTS>("video");
  /** Dark gradient scrim at the bottom (for text/badges over the media). */
  readonly overlay = input(false, { transform: booleanAttribute });
  /** Extra classes, merged with tailwind-merge. */
  readonly classInput = input<string>("", { alias: "class" });

  protected readonly hostClass = computed(() =>
    cn("relative block overflow-hidden bg-muted", ASPECTS[this.aspect()], this.classInput()),
  );
}

/** Header row — projects the title/description; mark a trailing element `bpdmCardAction`. */
@Component({
  selector: "bpdm-card-header",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { "data-bpdm-slot": "card-header", class: "flex items-start justify-between gap-4 px-5 pt-5" },
  template: `
    <div class="flex min-w-0 flex-col gap-1"><ng-content /></div>
    <div data-bpdm-slot="card-action" class="shrink-0"><ng-content select="[bpdmCardAction]" /></div>
  `,
})
export class BpdmCardHeader {}

/** Card title — apply to a heading element. */
@Directive({
  selector: "[bpdmCardTitle]",
  host: { "data-bpdm-slot": "card-title", class: "m-0 text-lg font-semibold leading-tight tracking-tight" },
})
export class BpdmCardTitle {}

/** Card description — apply to a paragraph. */
@Directive({
  selector: "[bpdmCardDescription]",
  host: { "data-bpdm-slot": "card-description", class: "m-0 text-sm text-muted-foreground" },
})
export class BpdmCardDescription {}

/** Card body content. */
@Directive({
  selector: "[bpdmCardContent]",
  host: { "data-bpdm-slot": "card-content", class: "px-5 py-4 text-sm leading-relaxed text-muted-foreground" },
})
export class BpdmCardContent {}

/** Card footer (actions row). Set `divider` for a hairline above it. */
@Directive({
  selector: "[bpdmCardFooter]",
  host: {
    "data-bpdm-slot": "card-footer",
    class: "mt-auto flex items-center gap-3 px-5 pb-5 pt-1",
    "[class.border-t]": "divider()",
    "[class.border-border]": "divider()",
    "[class.pt-4]": "divider()",
  },
})
export class BpdmCardFooter {
  /** Add a hairline divider above the footer. */
  readonly divider = input(false, { transform: booleanAttribute });
}
