// packages/react/src/components/select.tsx
import * as React from "react";
import * as PopoverPrimitive from "@radix-ui/react-popover";
import { useVirtualizer } from "@tanstack/react-virtual";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "@/lib/utils";
import { FieldChevron, FieldCheck, FieldSearch } from "./internal/field-icons";

export type SelectOption = {
  value: string;
  label: string;
  icon?: React.ReactNode;
  disabled?: boolean;
};
export type SelectOptionGroup = {
  label: string;
  icon?: React.ReactNode;
  options: SelectOption[];
};
export type SelectItems = Array<SelectOption | SelectOptionGroup>;

const isGroup = (x: SelectOption | SelectOptionGroup): x is SelectOptionGroup =>
  Array.isArray((x as SelectOptionGroup).options);

const triggerVariants = cva(
  "flex w-full cursor-pointer items-center justify-between gap-2 rounded-[var(--radius)] border border-input bg-background text-foreground shadow-sm transition-colors focus-visible:border-ring focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 aria-[invalid=true]:border-destructive aria-[invalid=true]:focus-visible:ring-destructive",
  {
    variants: {
      size: {
        sm: "h-8 px-2.5 text-sm",
        md: "h-10 px-3 text-sm",
        lg: "h-12 px-4 text-base",
      },
    },
    defaultVariants: { size: "md" },
  },
);

type Row =
  | { kind: "group"; label: string; icon?: React.ReactNode }
  | { kind: "item"; option: SelectOption };

const ITEM_H = 36;
const GROUP_H = 30;


export interface SelectProps extends VariantProps<typeof triggerVariants> {
  options: SelectItems;
  value?: string;
  defaultValue?: string;
  onValueChange?: (value: string) => void;
  placeholder?: string;
  /** Show a filter box at the top of the dropdown. */
  searchable?: boolean;
  searchPlaceholder?: string;
  emptyText?: string;
  /** Max height (px) of the scrollable option list. */
  maxHeight?: number;
  disabled?: boolean;
  className?: string;
  contentClassName?: string;
  "aria-invalid"?: boolean;
  id?: string;
  /** Accessible name for the trigger + option list (when there's no visible `<label>`). */
  "aria-label"?: string;
  "aria-describedby"?: string;
}

/**
 * Single-select dropdown. Data-driven (`options`, flat or grouped), always
 * **virtualized** (10k+ rows stay smooth), with an optional **searchable** filter.
 * Controlled (`value` + `onValueChange`) or uncontrolled (`defaultValue`).
 */
export function Select({
  options,
  value,
  defaultValue,
  onValueChange,
  placeholder = "Select…",
  searchable = false,
  searchPlaceholder = "Search…",
  emptyText = "No results.",
  maxHeight = 256,
  size,
  disabled,
  className,
  contentClassName,
  "aria-invalid": ariaInvalid,
  id,
  "aria-label": ariaLabel,
  "aria-describedby": ariaDescribedBy,
}: SelectProps) {
  const baseId = React.useId();
  const listboxId = `${baseId}-listbox`;
  const optionId = (index: number) => `${baseId}-opt-${index}`;
  const searchRef = React.useRef<HTMLInputElement>(null);
  const listRef = React.useRef<HTMLDivElement | null>(null);
  const [open, setOpen] = React.useState(false);
  const isControlled = value !== undefined;
  const [internal, setInternal] = React.useState(defaultValue ?? "");
  const selected = isControlled ? value : internal;
  const [query, setQuery] = React.useState("");
  const [active, setActive] = React.useState(0);
  // callback-ref + state so the virtualizer re-measures once the scroll element
  // mounts (a plain ref doesn't re-render → empty list on the first open).
  const [listEl, setListEl] = React.useState<HTMLDivElement | null>(null);

  // Portal into the nearest dialog (if any) instead of <body>. Inside a modal
  // dialog, scroll-lock makes a body-portaled popover inert (no clicks/scroll);
  // rendering within the dialog keeps the dropdown interactive. Outside a dialog
  // this is null → defaults to <body>.
  const triggerRef = React.useRef<HTMLButtonElement>(null);
  const [portalContainer, setPortalContainer] = React.useState<HTMLElement | null>(null);
  React.useEffect(() => {
    setPortalContainer(triggerRef.current?.closest<HTMLElement>("[role='dialog']") ?? null);
  }, []);

  // flatten options → rows (group headers + items)
  const allRows = React.useMemo<Row[]>(() => {
    const rows: Row[] = [];
    for (const entry of options) {
      if (isGroup(entry)) {
        rows.push({ kind: "group", label: entry.label, icon: entry.icon });
        for (const o of entry.options) rows.push({ kind: "item", option: o });
      } else {
        rows.push({ kind: "item", option: entry });
      }
    }
    return rows;
  }, [options]);

  // filter (keeps a group header only if it has a matching item)
  const rows = React.useMemo<Row[]>(() => {
    const q = query.trim().toLowerCase();
    if (!q) return allRows;
    const out: Row[] = [];
    let pending: Row | null = null;
    let used = false;
    for (const r of allRows) {
      if (r.kind === "group") {
        pending = r;
        used = false;
      } else if (r.option.label.toLowerCase().includes(q)) {
        if (pending && !used) {
          out.push(pending);
          used = true;
        }
        out.push(r);
      }
    }
    return out;
  }, [allRows, query]);

  const firstItem = React.useMemo(
    () => rows.findIndex((r) => r.kind === "item"),
    [rows],
  );

  const virtualizer = useVirtualizer({
    count: rows.length,
    getScrollElement: () => listEl,
    estimateSize: (i) => (rows[i]?.kind === "group" ? GROUP_H : ITEM_H),
    overscan: 12,
  });

  // Reset the active option ONLY when the menu opens or the filter changes — not
  // on every `rows` identity change. Inline `options` props re-create the array
  // each render, so keying off `rows` would snap the highlight + scroll back to
  // the top on every interaction.
  React.useEffect(() => {
    setActive(firstItem === -1 ? 0 : firstItem);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, query]);
  React.useEffect(() => {
    if (open && rows.length) virtualizer.scrollToIndex(active);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [active, open]);

  const selectedLabel = React.useMemo(() => {
    for (const r of allRows)
      if (r.kind === "item" && r.option.value === selected) return r.option.label;
    return undefined;
  }, [allRows, selected]);

  const commit = (val: string) => {
    if (!isControlled) setInternal(val);
    onValueChange?.(val);
    setOpen(false);
    setQuery("");
  };

  const move = (dir: 1 | -1) =>
    setActive((cur) => {
      let i = cur;
      do {
        i += dir;
      } while (i >= 0 && i < rows.length && rows[i].kind === "group");
      return i < 0 || i >= rows.length ? cur : i;
    });

  // first / last selectable option row (skips group headers) — for Home / End
  const edgeItem = (from: "start" | "end") => {
    if (from === "start") return rows.findIndex((r) => r.kind === "item");
    for (let i = rows.length - 1; i >= 0; i--) if (rows[i].kind === "item") return i;
    return -1;
  };

  // APG type-ahead: accumulate rapid keystrokes and jump to the first option
  // whose label starts with the buffer. A lone repeated key cycles matches.
  const typeahead = React.useRef("");
  const typeaheadTimer = React.useRef<ReturnType<typeof setTimeout> | null>(null);
  React.useEffect(
    () => () => {
      if (typeaheadTimer.current) clearTimeout(typeaheadTimer.current);
    },
    [],
  );
  const onType = (char: string) => {
    if (typeaheadTimer.current) clearTimeout(typeaheadTimer.current);
    const q = (typeahead.current + char).toLowerCase();
    typeahead.current = q;
    typeaheadTimer.current = setTimeout(() => {
      typeahead.current = "";
    }, 500);
    const items: number[] = [];
    for (let i = 0; i < rows.length; i++) if (rows[i].kind === "item") items.push(i);
    if (!items.length) return;
    const pos = items.indexOf(active);
    // fresh single char → start after the active row (cycle); accumulating → include it
    const offset = q.length === 1 ? 1 : 0;
    for (let n = 0; n < items.length; n++) {
      const idx = items[(pos + offset + n + items.length) % items.length];
      const r = rows[idx];
      if (r.kind === "item" && r.option.label.toLowerCase().startsWith(q)) {
        setActive(idx);
        return;
      }
    }
  };

  const onKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "ArrowDown") {
      e.preventDefault();
      move(1);
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      move(-1);
    } else if (e.key === "Home" && !searchable) {
      e.preventDefault();
      const i = edgeItem("start");
      if (i >= 0) setActive(i);
    } else if (e.key === "End" && !searchable) {
      e.preventDefault();
      const i = edgeItem("end");
      if (i >= 0) setActive(i);
    } else if (e.key === "Enter") {
      e.preventDefault();
      const r = rows[active];
      if (r?.kind === "item" && !r.option.disabled) commit(r.option.value);
    } else if (
      !searchable &&
      e.key.length === 1 &&
      !e.ctrlKey &&
      !e.metaKey &&
      !e.altKey &&
      /\S/.test(e.key)
    ) {
      // printable character → type-ahead (only when there's no filter input)
      e.preventDefault();
      onType(e.key);
    }
  };

  // the id of the highlighted option, exposed via aria-activedescendant so screen
  // readers announce the active row as you arrow through the list
  const activeId = rows[active]?.kind === "item" ? optionId(active) : undefined;

  return (
    <PopoverPrimitive.Root open={open} onOpenChange={setOpen}>
      <PopoverPrimitive.Trigger asChild>
        <button
          ref={triggerRef}
          type="button"
          id={id}
          role="combobox"
          aria-haspopup="listbox"
          aria-expanded={open}
          aria-controls={open ? listboxId : undefined}
          aria-label={ariaLabel}
          aria-describedby={ariaDescribedBy}
          aria-invalid={ariaInvalid}
          disabled={disabled}
          data-bpdm="" data-bpdm-slot="select-trigger"
          className={cn(triggerVariants({ size }), "group", className)}
        >
          <span
            data-bpdm-slot="select-value"
            className={cn("truncate", !selectedLabel && "text-muted-foreground")}
            title={selectedLabel ?? placeholder}
          >
            {selectedLabel ?? placeholder}
          </span>
          <FieldChevron />
        </button>
      </PopoverPrimitive.Trigger>

      <PopoverPrimitive.Portal container={portalContainer ?? undefined}>
        <PopoverPrimitive.Content
          align="start"
          sideOffset={4}
          collisionPadding={8}
          onKeyDown={onKeyDown}
          onOpenAutoFocus={(e) => {
            // focus the search box (editable combobox) or the listbox itself, so
            // aria-activedescendant is announced from the focused element
            e.preventDefault();
            (searchable ? searchRef.current : listRef.current)?.focus();
          }}
          // cap to the space available in the viewport/modal and flip if needed,
          // so it never overflows or squishes a small modal (it's portaled to
          // <body>, so opening never resizes the modal either)
          style={{ maxHeight: "var(--radix-popover-content-available-height)" }}
          data-bpdm="" data-bpdm-slot="select-content"
          className={cn(
            "z-50 flex w-[var(--radix-popover-trigger-width)] flex-col overflow-hidden rounded-[var(--radius)] border border-border bg-popover text-popover-foreground shadow-md",
            "origin-[var(--radix-popover-content-transform-origin)] data-[state=open]:animate-[bpdm-pop-in_var(--bpdm-duration-fast)_var(--bpdm-ease-out)] data-[state=closed]:animate-[bpdm-pop-out_var(--bpdm-duration-fast)_ease-in]",
            contentClassName,
          )}
        >
          {searchable && (
            <div className="flex shrink-0 items-center gap-2 border-b border-border px-3">
              <FieldSearch />
              <input
                ref={searchRef}
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                placeholder={searchPlaceholder}
                aria-label={searchPlaceholder}
                role="combobox"
                aria-expanded
                aria-controls={listboxId}
                aria-autocomplete="list"
                aria-activedescendant={activeId}
                data-bpdm-slot="select-search"
                className="h-9 w-full bg-transparent text-sm text-foreground placeholder:text-muted-foreground focus:outline-none"
              />
            </div>
          )}

          {rows.length === 0 ? (
            <div data-bpdm-slot="select-empty" className="px-3 py-6 text-center text-sm text-muted-foreground">
              {emptyText}
            </div>
          ) : (
            <div
              ref={(el) => {
                listRef.current = el;
                setListEl(el);
              }}
              id={listboxId}
              role="listbox"
              aria-label={ariaLabel ?? placeholder}
              tabIndex={-1}
              aria-activedescendant={searchable ? undefined : activeId}
              style={{ maxHeight }}
              data-bpdm-slot="select-list"
              className="min-h-0 flex-1 overflow-auto p-1 focus:outline-none"
            >
              <div style={{ height: virtualizer.getTotalSize(), position: "relative" }}>
                {virtualizer.getVirtualItems().map((vi) => {
                  const r = rows[vi.index];
                  const common = {
                    style: {
                      height: vi.size,
                      transform: `translateY(${vi.start}px)`,
                    } as React.CSSProperties,
                  };
                  if (r.kind === "group") {
                    return (
                      <div
                        key={`g-${vi.index}`}
                        aria-hidden="true"
                        data-bpdm-slot="select-group"
                        className="absolute start-0 top-0 flex w-full items-center gap-2 px-2 text-sm font-semibold text-foreground [&_img]:size-4 [&_svg]:size-4"
                        {...common}
                      >
                        {r.icon}
                        {r.label}
                      </div>
                    );
                  }
                  const o = r.option;
                  const isSelected = o.value === selected;
                  const isActive = vi.index === active;
                  return (
                    <button
                      key={o.value}
                      id={optionId(vi.index)}
                      type="button"
                      role="option"
                      aria-selected={isSelected}
                      disabled={o.disabled}
                      onClick={() => !o.disabled && commit(o.value)}
                      onMouseMove={() => setActive(vi.index)}
                      data-bpdm-slot="select-option"
                      className={cn(
                        "absolute start-0 top-0 flex w-full cursor-pointer items-center gap-2 rounded-[calc(var(--radius)-3px)] px-2 text-start text-sm text-foreground transition-colors duration-[var(--bpdm-duration-fast)] disabled:pointer-events-none disabled:opacity-50",
                        // keyboard-active / hovered row: an amber inline-start bar (ring
                        // token, ≥3:1 in every theme) + soft tint + weight — clearly
                        // perceptible where bg-muted alone was ~1.05:1. RTL-safe (logical
                        // shadow mirror), jitter-free (inset shadow takes no layout space).
                        isActive &&
                          "bg-[var(--bpdm-option-active-bg)] font-medium shadow-[inset_2px_0_0_0_var(--bpdm-option-active-bar)] rtl:shadow-[inset_-2px_0_0_0_var(--bpdm-option-active-bar)]",
                      )}
                      {...common}
                    >
                      <span className="flex size-4 shrink-0 items-center justify-center text-primary">
                        {isSelected && (
                          <span className="animate-[bpdm-indicator-in_var(--bpdm-duration-base)_var(--bpdm-ease-overshoot)]">
                            <FieldCheck />
                          </span>
                        )}
                      </span>
                      {o.icon}
                      <span className="truncate" title={o.label}>
                        {o.label}
                      </span>
                    </button>
                  );
                })}
              </div>
            </div>
          )}
        </PopoverPrimitive.Content>
      </PopoverPrimitive.Portal>
    </PopoverPrimitive.Root>
  );
}

// packages/angular/src/lib/select/select.ts
import {
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  inject,
  input,
  model,
  OnDestroy,
  signal,
  TemplateRef,
  viewChild,
  ViewContainerRef,
} from "@angular/core";
import {
  CdkFixedSizeVirtualScroll,
  CdkVirtualForOf,
  CdkVirtualScrollViewport,
} from "@angular/cdk/scrolling";
import { Overlay, OverlayRef } from "@angular/cdk/overlay";
import { TemplatePortal } from "@angular/cdk/portal";
import { cn } from "@bpdm/variants";
import {
  type FieldSize,
  FIELD_PANEL,
  SELECT_TRIGGER_BASE,
  SELECT_TRIGGER_SIZE,
} from "../internal/field";

export interface SelectOption {
  value: string;
  label: string;
  disabled?: boolean;
}
export interface SelectOptionGroup {
  label: string;
  options: SelectOption[];
}
export type SelectItems = Array<SelectOption | SelectOptionGroup>;

const isGroup = (x: SelectOption | SelectOptionGroup): x is SelectOptionGroup =>
  Array.isArray((x as SelectOptionGroup).options);

export type SelectRow =
  | { kind: "group"; label: string }
  | { kind: "item"; option: SelectOption };

const ROW_H = 36;

/** Per-instance counter for stable listbox/option ids (aria-activedescendant). */
let selectUid = 0;

export function flattenSelectRows(options: SelectItems): SelectRow[] {
  const rows: SelectRow[] = [];
  for (const entry of options) {
    if (isGroup(entry)) {
      rows.push({ kind: "group", label: entry.label });
      for (const o of entry.options) rows.push({ kind: "item", option: o });
    } else {
      rows.push({ kind: "item", option: entry });
    }
  }
  return rows;
}

export function filterSelectRows(all: SelectRow[], query: string): SelectRow[] {
  const q = query.trim().toLowerCase();
  if (!q) return all;
  const out: SelectRow[] = [];
  let pending: SelectRow | null = null;
  let used = false;
  for (const r of all) {
    if (r.kind === "group") {
      pending = r;
      used = false;
    } else if (r.option.label.toLowerCase().includes(q)) {
      if (pending && !used) {
        out.push(pending);
        used = true;
      }
      out.push(r);
    }
  }
  return out;
}

/**
 * `<bpdm-select>` — single-select dropdown. Data-driven (`options`, flat or
 * grouped), always **virtualized** (10k+ rows stay smooth), with an optional
 * **searchable** filter. Controlled (`[(value)]`) or uncontrolled (`defaultValue`).
 * Mirrors the React `Select`.
 */
@Component({
  selector: "bpdm-select",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CdkVirtualScrollViewport, CdkFixedSizeVirtualScroll, CdkVirtualForOf],
  host: { class: "block" },
  template: `
    <button
      #trigger
      type="button"
      data-bpdm=""
      data-bpdm-slot="select-trigger"
      role="combobox"
      aria-haspopup="listbox"
      [attr.id]="id() || null"
      [attr.aria-expanded]="open()"
      [attr.aria-controls]="open() ? listboxId : null"
      [attr.aria-label]="ariaLabel() || null"
      [attr.aria-describedby]="ariaDescribedby() || null"
      [attr.aria-invalid]="ariaInvalid() || null"
      [attr.data-state]="open() ? 'open' : 'closed'"
      [disabled]="disabled() || null"
      [class]="triggerClass()"
      (click)="toggle()"
      (keydown)="onTriggerKeydown($event)"
    >
      <span data-bpdm-slot="select-value" class="truncate" [class.text-muted-foreground]="!selectedLabel()" [attr.title]="selectedLabel() || placeholder()">
        {{ selectedLabel() || placeholder() }}
      </span>
      <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" class="size-4 shrink-0 opacity-60 transition-transform duration-[var(--bpdm-duration-base)] ease-[var(--bpdm-ease-out)]" [class.rotate-180]="open()">
        <path d="M4 6l4 4 4-4" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" />
      </svg>
    </button>

    <ng-template #panel>
      <div #panelRoot data-bpdm="" data-bpdm-slot="select-content" tabindex="-1" [class]="panelClass()" [style.width.px]="panelWidth()" (keydown)="onKeydown($event)">
        @if (searchable()) {
          <div class="flex shrink-0 items-center gap-2 border-b border-border px-3">
            <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" class="size-4 shrink-0 text-muted-foreground"><circle cx="7" cy="7" r="4.5" stroke="currentColor" stroke-width="1.6" /><path d="M11 11l3 3" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" /></svg>
            <input #search data-bpdm-slot="select-search" [value]="query()" (input)="onSearch($any($event.target).value)" [attr.placeholder]="searchPlaceholder()" [attr.aria-label]="searchPlaceholder()" role="combobox" aria-expanded="true" aria-autocomplete="list" [attr.aria-controls]="listboxId" [attr.aria-activedescendant]="activeDescId()" class="h-9 w-full bg-transparent text-sm text-foreground placeholder:text-muted-foreground focus:outline-none" />
          </div>
        }
        @if (rows().length === 0) {
          <div data-bpdm-slot="select-empty" class="px-3 py-6 text-center text-sm text-muted-foreground">{{ emptyText() }}</div>
        } @else {
          <cdk-virtual-scroll-viewport
            #viewport
            data-bpdm-slot="select-list"
            role="listbox"
            tabindex="-1"
            [attr.id]="listboxId"
            [attr.aria-label]="ariaLabel() || placeholder()"
            [attr.aria-activedescendant]="searchable() ? null : activeDescId()"
            [itemSize]="36"
            [style.height.px]="viewportHeight()"
            class="overflow-auto px-1 focus:outline-none"
          >
            <ng-container *cdkVirtualFor="let r of rows(); let i = index">
              @if (r.kind === "group") {
                <div data-bpdm-slot="select-group" aria-hidden="true" class="flex h-9 items-center gap-2 px-2 text-sm font-semibold text-foreground">{{ r.label }}</div>
              } @else {
                <button
                  type="button"
                  data-bpdm-slot="select-option"
                  role="option"
                  [attr.id]="optionId(i)"
                  [attr.aria-selected]="r.option.value === selected()"
                  [disabled]="r.option.disabled || null"
                  (click)="commit(r.option)"
                  (mousemove)="active.set(i)"
                  [class]="optionClass(i)"
                >
                  <span class="flex size-4 shrink-0 items-center justify-center text-primary">
                    @if (r.option.value === selected()) {
                      <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" class="size-3.5 animate-[bpdm-indicator-in_var(--bpdm-duration-base)_var(--bpdm-ease-overshoot)]"><path d="M3.5 8.5l3 3 6-7" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round" /></svg>
                    }
                  </span>
                  <span class="truncate" [attr.title]="r.option.label">{{ r.option.label }}</span>
                </button>
              }
            </ng-container>
          </cdk-virtual-scroll-viewport>
        }
      </div>
    </ng-template>
  `,
})
export class BpdmSelect implements OnDestroy {
  private readonly overlay = inject(Overlay);
  private readonly vcr = inject(ViewContainerRef);

  readonly options = input<SelectItems>([]);
  readonly value = model<string>("");
  readonly defaultValue = input<string>("");
  readonly placeholder = input("Select…");
  /** Show a filter box at the top of the dropdown. */
  readonly searchable = input(false, { transform: booleanAttribute });
  readonly searchPlaceholder = input("Search…");
  readonly emptyText = input("No results.");
  /** Max height (px) of the scrollable option list. */
  readonly maxHeight = input(256);
  readonly size = input<FieldSize>("md");
  readonly disabled = input(false, { transform: booleanAttribute });
  readonly ariaInvalid = input(false, { alias: "aria-invalid", transform: booleanAttribute });
  readonly classInput = input("", { alias: "class" });
  readonly id = input("");
  /** Accessible name for the trigger + option list — pass a translated string. */
  readonly ariaLabel = input("", { alias: "aria-label" });
  readonly ariaDescribedby = input("", { alias: "aria-describedby" });

  protected readonly open = signal(false);
  protected readonly query = signal("");
  protected readonly active = signal(0);

  /** Stable ids linking trigger → listbox → active option (aria-activedescendant). */
  protected readonly baseId = `bpdm-select-${(selectUid += 1)}`;
  protected readonly listboxId = `${this.baseId}-listbox`;
  protected optionId(index: number): string {
    return `${this.baseId}-opt-${index}`;
  }
  protected readonly activeDescId = computed(() => {
    const r = this.rows()[this.active()];
    return r?.kind === "item" ? this.optionId(this.active()) : null;
  });

  private readonly triggerEl = viewChild.required<ElementRef<HTMLButtonElement>>("trigger");
  private readonly panelTpl = viewChild.required<TemplateRef<unknown>>("panel");
  private readonly searchEl = viewChild<ElementRef<HTMLInputElement>>("search");
  private readonly viewport = viewChild<CdkVirtualScrollViewport>("viewport");

  protected readonly panelWidth = signal(0);
  private overlayRef?: OverlayRef;

  protected readonly selected = computed(() => this.value() || this.defaultValue());
  private readonly allRows = computed(() => flattenSelectRows(this.options()));
  protected readonly rows = computed(() => filterSelectRows(this.allRows(), this.query()));
  protected readonly viewportHeight = computed(() =>
    Math.min(this.maxHeight(), this.rows().length * ROW_H),
  );
  protected readonly selectedLabel = computed(() => {
    const sel = this.selected();
    for (const r of this.allRows()) if (r.kind === "item" && r.option.value === sel) return r.option.label;
    return "";
  });

  protected readonly triggerClass = computed(() =>
    cn(SELECT_TRIGGER_BASE, SELECT_TRIGGER_SIZE[this.size()], "group", this.classInput()),
  );
  protected readonly panelClass = computed(() => FIELD_PANEL);

  protected optionClass(i: number): string {
    return cn(
      "flex h-9 w-full cursor-pointer items-center gap-2 rounded-[calc(var(--radius)-3px)] px-2 text-start text-sm text-foreground transition-colors duration-[var(--bpdm-duration-fast)] disabled:pointer-events-none disabled:opacity-50",
      // keyboard-active / hovered row: an amber inline-start bar (ring token, ≥3:1
      // in every theme) + soft tint + weight — clearly perceptible where bg-muted
      // alone was ~1.05:1. RTL-safe (logical shadow mirror), jitter-free (inset).
      i === this.active() &&
        "bg-[var(--bpdm-option-active-bg)] font-medium shadow-[inset_2px_0_0_0_var(--bpdm-option-active-bar)] rtl:shadow-[inset_-2px_0_0_0_var(--bpdm-option-active-bar)]",
    );
  }

  protected toggle(): void {
    if (this.open()) this.close();
    else this.openPanel();
  }

  private openPanel(): void {
    if (this.disabled() || this.overlayRef) return;
    const trigger = this.triggerEl().nativeElement;
    this.panelWidth.set(trigger.offsetWidth);
    const positionStrategy = this.overlay
      .position()
      .flexibleConnectedTo(trigger)
      .withPositions([
        { originX: "start", originY: "bottom", overlayX: "start", overlayY: "top", offsetY: 4 },
        { originX: "start", originY: "top", overlayX: "start", overlayY: "bottom", offsetY: -4 },
      ])
      .withFlexibleDimensions(false)
      .withPush(false);
    this.overlayRef = this.overlay.create({
      positionStrategy,
      scrollStrategy: this.overlay.scrollStrategies.reposition(),
    });
    this.overlayRef.attach(new TemplatePortal(this.panelTpl(), this.vcr));
    this.open.set(true);
    this.resetActive();

    this.overlayRef.outsidePointerEvents().subscribe((e) => {
      if (!trigger.contains(e.target as Node)) this.close();
    });
    // measure the virtual viewport + move focus once the panel has rendered
    setTimeout(() => {
      this.viewport()?.checkViewportSize();
      const search = this.searchEl()?.nativeElement;
      // focus the search box (editable combobox) or the listbox itself, so
      // aria-activedescendant is announced from the focused element
      if (search) search.focus();
      else this.viewport()?.elementRef.nativeElement.focus();
    });
  }

  protected close(): void {
    this.overlayRef?.dispose();
    this.overlayRef = undefined;
    this.open.set(false);
    this.query.set("");
    this.triggerEl().nativeElement.focus();
  }

  protected commit(option: SelectOption): void {
    if (option.disabled) return;
    this.value.set(option.value);
    this.close();
  }

  protected onSearch(v: string): void {
    this.query.set(v);
    this.resetActive();
  }

  private resetActive(): void {
    const first = this.rows().findIndex((r) => r.kind === "item");
    this.active.set(first === -1 ? 0 : first);
  }

  private move(dir: 1 | -1): void {
    const rows = this.rows();
    let i = this.active();
    do {
      i += dir;
    } while (i >= 0 && i < rows.length && rows[i].kind === "group");
    if (i < 0 || i >= rows.length) return;
    this.active.set(i);
    this.viewport()?.scrollToIndex(i, "smooth");
  }

  protected onTriggerKeydown(e: KeyboardEvent): void {
    if (!this.open() && (e.key === "ArrowDown" || e.key === "Enter" || e.key === " ")) {
      e.preventDefault();
      this.openPanel();
    }
  }

  /** Jump the active row to the first / last selectable option (skips groups). */
  private jumpTo(edge: "start" | "end"): void {
    const rows = this.rows();
    let i = -1;
    if (edge === "start") {
      i = rows.findIndex((r) => r.kind === "item");
    } else {
      for (let k = rows.length - 1; k >= 0; k--)
        if (rows[k].kind === "item") {
          i = k;
          break;
        }
    }
    if (i < 0) return;
    this.active.set(i);
    this.viewport()?.scrollToIndex(i, "smooth");
  }

  private typeahead = "";
  private typeaheadTimer?: ReturnType<typeof setTimeout>;
  // APG type-ahead: accumulate rapid keystrokes and jump to the first option whose
  // label starts with the buffer. A lone repeated key cycles matches.
  private onType(char: string): void {
    if (this.typeaheadTimer) clearTimeout(this.typeaheadTimer);
    const q = (this.typeahead + char).toLowerCase();
    this.typeahead = q;
    this.typeaheadTimer = setTimeout(() => {
      this.typeahead = "";
    }, 500);
    const rows = this.rows();
    const items: number[] = [];
    for (let i = 0; i < rows.length; i++) if (rows[i].kind === "item") items.push(i);
    if (!items.length) return;
    const pos = items.indexOf(this.active());
    // fresh single char → start after the active row (cycle); accumulating → include it
    const offset = q.length === 1 ? 1 : 0;
    for (let n = 0; n < items.length; n++) {
      const idx = items[(pos + offset + n + items.length) % items.length];
      const r = rows[idx];
      if (r.kind === "item" && r.option.label.toLowerCase().startsWith(q)) {
        this.active.set(idx);
        this.viewport()?.scrollToIndex(idx, "smooth");
        return;
      }
    }
  }

  protected onKeydown(e: KeyboardEvent): void {
    if (e.key === "ArrowDown") {
      e.preventDefault();
      this.move(1);
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      this.move(-1);
    } else if (e.key === "Home" && !this.searchable()) {
      e.preventDefault();
      this.jumpTo("start");
    } else if (e.key === "End" && !this.searchable()) {
      e.preventDefault();
      this.jumpTo("end");
    } else if (e.key === "Enter") {
      e.preventDefault();
      const r = this.rows()[this.active()];
      if (r?.kind === "item" && !r.option.disabled) this.commit(r.option);
    } else if (e.key === "Escape") {
      e.preventDefault();
      this.close();
    } else if (
      !this.searchable() &&
      e.key.length === 1 &&
      !e.ctrlKey &&
      !e.metaKey &&
      !e.altKey &&
      /\S/.test(e.key)
    ) {
      // printable character → type-ahead (only when there's no filter input)
      e.preventDefault();
      this.onType(e.key);
    }
  }

  ngOnDestroy(): void {
    if (this.typeaheadTimer) clearTimeout(this.typeaheadTimer);
    this.overlayRef?.dispose();
  }
}
