// packages/react/src/components/alert.tsx
import * as React from "react";
import {
  CircleCheck,
  CircleHelp,
  CircleX,
  Info,
  TriangleAlert,
  X,
} from "lucide-react";
import { type AlertAppearance, alertTones, type AlertVariant } from "@bpdm/variants";
import { cn } from "@/lib/utils";

export type { AlertVariant, AlertAppearance };

// --- i18n ---
export interface AlertMessages {
  /** Dismiss (X) button aria-label. */
  dismiss: string;
}

export const DEFAULT_ALERT_MESSAGES: AlertMessages = { dismiss: "Dismiss" };

// per-variant leading icon — the colors (fg / accent / tint / solid / outline)
// come from the shared `alertTones` so the React and Angular alerts match.
const ICONS: Record<AlertVariant, React.ComponentType<{ className?: string }> | null> = {
  default: Info,
  primary: Info,
  info: Info,
  success: CircleCheck,
  warning: TriangleAlert,
  help: CircleHelp,
  error: CircleX,
  contrast: Info,
};

export interface AlertProps extends Omit<React.HTMLAttributes<HTMLDivElement>, "title"> {
  variant?: AlertVariant;
  /** Visual style — `soft` (tinted, default), `solid` (filled), `outline` (border). */
  appearance?: AlertAppearance;
  /** Bold heading line. */
  title?: React.ReactNode;
  /** Override the leading icon; pass `null` to hide it. */
  icon?: React.ReactNode | null;
  /** Show a close button and call this when clicked. */
  onClose?: () => void;
  /** Action buttons/links shown under the body. */
  action?: React.ReactNode;
  /** Override the translatable strings (currently just the dismiss button label). */
  messages?: Partial<AlertMessages>;
  /**
   * Live-region politeness. Defaults to today's behavior — `role="alert"`
   * (assertive, interrupts the screen reader), right for urgent messages.
   * Set `"polite"` for `role="status"` (announced when idle) on info/success,
   * or `"off"` to render no live role.
   */
  live?: "assertive" | "polite" | "off";
}

/**
 * Inline, persistent alert — a severity-tinted surface, an inline icon, a title
 * and body, with optional actions and a dismiss button. Three appearances
 * (`soft` / `solid` / `outline`) × the full severity palette. Theme-aware.
 * For transient notifications use `toast` / `<Toaster>` instead.
 */
export const Alert = React.forwardRef<HTMLDivElement, AlertProps>(
  (
    { variant = "default", appearance = "soft", title, icon, onClose, action, messages, live, className, children, ...props },
    ref,
  ) => {
    const tone = alertTones[variant];
    const Icon = ICONS[variant];
    const showIcon = icon !== null && (icon !== undefined || Icon);
    const [closing, setClosing] = React.useState(false);
    const solid = appearance === "solid";
    const soft = appearance === "soft";
    const t = React.useMemo(() => ({ ...DEFAULT_ALERT_MESSAGES, ...messages }), [messages]);
    // undefined / "assertive" → role="alert"; "polite" → role="status"; "off" → no live role.
    const liveRole =
      live === undefined || live === "assertive" ? "alert" : live === "polite" ? "status" : undefined;

    const box = (
      <div
        ref={ref}
        role={liveRole}
        className={cn(
          "relative flex w-full items-start gap-3 overflow-hidden rounded-lg border p-4",
          // soft = tinted inline-message surface (distinct from the white floating Toast)
          soft && tone.soft,
          appearance === "outline" && cn("bg-card text-card-foreground shadow-sm", tone.outline),
          solid && tone.solid,
          className,
        )}
        {...props}
      >
        {showIcon &&
          (soft ? (
            // inline coloured icon (no tinted box) — the inline-message look; the
            // size-5 icon matches the title's line height, so it reads aligned.
            <span className={cn("flex shrink-0 items-center [&>svg]:size-5", tone.fg)}>
              {icon ?? (Icon ? <Icon className="size-5" /> : null)}
            </span>
          ) : (
            <span
              className={cn(
                "mt-0.5 flex size-8 shrink-0 items-center justify-center rounded-lg animate-[bpdm-pop-in_220ms_ease-out]",
                solid ? "bg-white/15" : tone.tint,
              )}
            >
              {icon ?? (Icon ? <Icon className={cn("size-4", !solid && tone.fg)} /> : null)}
            </span>
          ))}
        <div className={cn("min-w-0 flex-1", onClose && "pe-6")}>
          {title && <p className="m-0 text-sm font-semibold">{title}</p>}
          {children != null && (
            <div className={cn("text-sm", solid ? "text-current" : "text-muted-foreground", title && "mt-1")}>
              {children}
            </div>
          )}
          {action && <div className="mt-3 flex flex-wrap gap-2">{action}</div>}
        </div>
        {onClose && (
          <button
            type="button"
            onClick={() => setClosing(true)}
            aria-label={t.dismiss}
            className={cn(
              "absolute end-2.5 top-2.5 inline-flex size-6 cursor-pointer items-center justify-center rounded-md transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
              solid
                ? "text-current/70 hover:bg-white/15 hover:text-current"
                : "text-muted-foreground/70 hover:bg-muted hover:text-foreground",
            )}
          >
            <X className="size-3.5" />
          </button>
        )}
      </div>
    );

    // not dismissible → render the box directly
    if (!onClose) return box;

    // dismissible → wrap so closing collapses height + fades (no layout snap)
    return (
      <div
        className={cn(
          "grid transition-all duration-200 ease-out",
          closing ? "grid-rows-[0fr] opacity-0" : "grid-rows-[1fr] opacity-100",
        )}
        onTransitionEnd={(e) => {
          if (closing && e.propertyName === "grid-template-rows") onClose();
        }}
      >
        <div className="min-h-0 overflow-hidden">{box}</div>
      </div>
    );
  },
);
Alert.displayName = "Alert";

// packages/angular/src/lib/alert/alert.ts
import {
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  Directive,
  computed,
  input,
  output,
  signal,
} from "@angular/core";
import { type AlertAppearance, alertTones, cn, type AlertVariant } from "@bpdm/variants";

// --- i18n ---
export interface AlertMessages {
  /** Dismiss (X) button aria-label. */
  dismiss: string;
}

export const DEFAULT_ALERT_MESSAGES: AlertMessages = { dismiss: "Dismiss" };

/** Actions row inside an alert — lays its buttons out with the right spacing. */
@Directive({
  selector: "[bpdmAlertActions]",
  host: { class: "mt-3 flex flex-wrap gap-2" },
})
export class BpdmAlertActions {}

/**
 * `<bpdm-alert>` — an inline, persistent alert: a severity-tinted surface, an
 * inline icon, a title and body, with an optional actions slot and a dismiss
 * button. Three
 * appearances (`soft` / `solid` / `outline`) × the full severity palette.
 * Theme-aware across all four themes. For transient notifications use a toast.
 *
 * ```html
 * <bpdm-alert variant="success" title="Saved" dismissible (closed)="onClose()">
 *   Your changes have been published.
 *   <div bpdmAlertActions><button bpdmButton size="sm" variant="secondary" appearance="ghost">Undo</button></div>
 * </bpdm-alert>
 * ```
 *
 * Colors come from the shared `@bpdm/variants` tones — identical to the React alert.
 */
@Component({
  selector: "bpdm-alert",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    // dismissible alerts collapse their height + fade on close
    class: "grid transition-all duration-200 ease-out",
    "[class.grid-rows-[0fr]]": "closing()",
    "[class.opacity-0]": "closing()",
    "[class.grid-rows-[1fr]]": "!closing()",
    "[class.opacity-100]": "!closing()",
    "(transitionend)": "onTransitionEnd($event)",
  },
  template: `
    <div class="min-h-0 overflow-hidden">
      <div [attr.role]="liveRole()" [class]="boxClass()">
        @if (showIcon()) {
          <span [class]="iconWrapClass()">
            <svg
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              [class]="iconSvgClass()"
              aria-hidden="true"
            >
              @switch (variant()) {
                @case ("success") {
                  <path d="M21.801 10A10 10 0 1 1 17 3.335" /><path d="m9 11 3 3L22 4" />
                }
                @case ("warning") {
                  <path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z" /><path d="M12 9v4" /><path d="M12 17h.01" />
                }
                @case ("error") {
                  <circle cx="12" cy="12" r="10" /><path d="m15 9-6 6" /><path d="m9 9 6 6" />
                }
                @case ("help") {
                  <circle cx="12" cy="12" r="10" /><path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" /><path d="M12 17h.01" />
                }
                @default {
                  <circle cx="12" cy="12" r="10" /><path d="M12 16v-4" /><path d="M12 8h.01" />
                }
              }
            </svg>
          </span>
        }

        <div class="min-w-0 flex-1" [class.pe-6]="dismissible()">
          @if (title()) {
            <p class="m-0 text-sm font-semibold">{{ title() }}</p>
          }
          <div class="text-sm empty:hidden" [class]="bodyClass()" [class.mt-1]="!!title()">
            <ng-content />
          </div>
          <ng-content select="[bpdmAlertActions]" />
        </div>

        @if (dismissible()) {
          <button
            type="button"
            (click)="dismiss()"
            [attr.aria-label]="t().dismiss"
            class="absolute end-2.5 top-2.5 inline-flex size-6 cursor-pointer items-center justify-center rounded-md transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
            [class]="closeClass()"
          >
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" class="size-3.5" aria-hidden="true">
              <path d="M18 6 6 18" /><path d="m6 6 12 12" />
            </svg>
          </button>
        }
      </div>
    </div>
  `,
})
export class BpdmAlert {
  /** Color + default icon. */
  readonly variant = input<AlertVariant>("default");
  /** Visual style — `soft` (tinted, default), `solid` (filled), `outline` (border). */
  readonly appearance = input<AlertAppearance>("soft");
  /** Bold heading line. */
  readonly title = input<string>();
  /** Show a dismiss button; emits `closed` after the collapse animation. */
  readonly dismissible = input(false, { transform: booleanAttribute });
  /** Show the leading status icon. */
  readonly showIcon = input(true, { transform: booleanAttribute });
  /** Override the translatable strings (currently just the dismiss button label). */
  readonly messages = input<Partial<AlertMessages>>({});
  /**
   * Live-region politeness. Defaults to today's behavior — `role="alert"`
   * (assertive, interrupts the screen reader), right for urgent messages.
   * Set `"polite"` for `role="status"` (announced when idle) on info/success,
   * or `"off"` to render no live role.
   */
  readonly live = input<"assertive" | "polite" | "off" | undefined>(undefined);
  /** Fired once the alert has finished collapsing after dismiss. */
  readonly closed = output<void>();

  protected readonly t = computed(() => ({ ...DEFAULT_ALERT_MESSAGES, ...this.messages() }));
  // undefined / "assertive" → role="alert"; "polite" → role="status"; "off" → no live role.
  protected readonly liveRole = computed(() => {
    const l = this.live();
    if (l === undefined || l === "assertive") return "alert";
    if (l === "polite") return "status";
    return null;
  });
  protected readonly closing = signal(false);
  protected readonly tone = computed(() => alertTones[this.variant()]);
  private readonly solid = computed(() => this.appearance() === "solid");

  protected readonly boxClass = computed(() => {
    const base = "relative flex w-full items-start gap-3 overflow-hidden rounded-lg border p-4";
    const a = this.appearance();
    if (a === "solid") return cn(base, this.tone().solid);
    if (a === "outline") return cn(base, "bg-card text-card-foreground shadow-sm", this.tone().outline);
    // soft = tinted inline-message surface (distinct from the white floating Toast)
    return cn(base, this.tone().soft);
  });
  private readonly box8 =
    "mt-0.5 flex size-8 shrink-0 items-center justify-center rounded-lg animate-[bpdm-pop-in_220ms_ease-out]";
  protected readonly iconWrapClass = computed(() => {
    const a = this.appearance();
    if (a === "soft") return cn("flex shrink-0 items-center", this.tone().fg); // inline coloured icon
    if (a === "solid") return cn(this.box8, "bg-white/15");
    return cn(this.box8, this.tone().tint); // outline
  });
  protected readonly iconSvgClass = computed(() => {
    const a = this.appearance();
    if (a === "soft") return "size-5";
    if (a === "solid") return "size-4";
    return cn("size-4", this.tone().fg); // outline
  });
  protected readonly bodyClass = computed(() => (this.solid() ? "text-current/90" : "text-muted-foreground"));
  protected readonly closeClass = computed(() =>
    this.solid()
      ? "text-current/70 hover:bg-white/15 hover:text-current"
      : "text-muted-foreground/70 hover:bg-muted hover:text-foreground",
  );

  protected dismiss(): void {
    this.closing.set(true);
  }

  protected onTransitionEnd(event: TransitionEvent): void {
    if (this.closing() && event.propertyName === "grid-template-rows") {
      this.closed.emit();
    }
  }
}
