// packages/react/src/components/calendar.tsx
import * as React from "react";
import { CalendarDays, ChevronDown, ChevronLeft, ChevronRight, X } from "lucide-react";
import { cn } from "@/lib/utils";
import { useControllable } from "@/lib/use-controllable";
import { Popover } from "./popover";

// date helpers (local, compared by y/m/d so DST never bites)
function startOfDay(d: Date) {
  return new Date(d.getFullYear(), d.getMonth(), d.getDate());
}
function sameDay(a?: Date | null, b?: Date | null) {
  return !!a && !!b && a.getFullYear() === b.getFullYear() && a.getMonth() === b.getMonth() && a.getDate() === b.getDate();
}
function addDays(d: Date, n: number) {
  return new Date(d.getFullYear(), d.getMonth(), d.getDate() + n);
}
function addMonths(d: Date, n: number) {
  return new Date(d.getFullYear(), d.getMonth() + n, 1);
}
function isBefore(a: Date, b: Date) {
  return startOfDay(a).getTime() < startOfDay(b).getTime();
}
function isAfter(a: Date, b: Date) {
  return startOfDay(a).getTime() > startOfDay(b).getTime();
}
function clampDay(d: Date, min?: Date, max?: Date) {
  if (min && isBefore(d, min)) return startOfDay(min);
  if (max && isAfter(d, max)) return startOfDay(max);
  return startOfDay(d);
}
function inRange(d: Date, from?: Date | null, to?: Date | null) {
  if (!from || !to) return false;
  const t = startOfDay(d).getTime();
  return t > startOfDay(from).getTime() && t < startOfDay(to).getTime();
}


/** Build the 6×7 grid of dates for the month containing `viewDate`. */
function buildGrid(viewDate: Date, weekStartsOn: number) {
  const first = new Date(viewDate.getFullYear(), viewDate.getMonth(), 1);
  const offset = (first.getDay() - weekStartsOn + 7) % 7;
  const start = new Date(first.getFullYear(), first.getMonth(), 1 - offset);
  return Array.from({ length: 42 }, (_, i) =>
    new Date(start.getFullYear(), start.getMonth(), start.getDate() + i),
  );
}

export type DateRange = { from: Date | null; to: Date | null };

export interface CalendarProps {
  /** "single" → a Date; "range" → a { from, to }. Default "single". */
  mode?: "single" | "range";
  /** Controlled value. */
  value?: Date | DateRange | null;
  defaultValue?: Date | DateRange | null;
  onChange?: (value: Date | DateRange | null) => void;
  min?: Date;
  max?: Date;
  /** Disable specific days, e.g. weekends. */
  disabled?: (date: Date) => boolean;
  /** 0 = Sunday, 1 = Monday. Default 1. */
  weekStartsOn?: 0 | 1;
  /** Shape of the day highlight: "circle" (default) or "square" (rounded-corner square). */
  dayShape?: "circle" | "square";
  /** How many months to show side by side. Default 1. */
  numberOfMonths?: number;
  /** Header style: "buttons" (prev/next only) or "dropdown" (month + year menus). */
  captionLayout?: "buttons" | "dropdown";
  /** Year-dropdown range. Default: 100 years back to 10 years ahead. */
  fromYear?: number;
  toYear?: number;
  /** BCP 47 locale for month/weekday names + date formatting (e.g. "de-DE", "ar"). */
  locale?: string;
  /** Override the control labels (screen-reader text) for i18n. */
  messages?: CalendarMessages;
  className?: string;
}

export interface CalendarMessages {
  calendar?: string;
  previousMonth?: string;
  nextMonth?: string;
  month?: string;
  year?: string;
  /** Clear button on the DatePicker trigger. */
  clear?: string;
  /** DatePicker `confirm` footer — discard the draft. */
  cancel?: string;
  /** DatePicker `confirm` footer — commit the draft. */
  apply?: string;
}

const DEFAULT_CALENDAR_MESSAGES = {
  calendar: "Calendar",
  previousMonth: "Previous month",
  nextMonth: "Next month",
  month: "Month",
  year: "Year",
  clear: "Clear",
  cancel: "Cancel",
  apply: "Apply",
};

// Aug 1 2021 is a Sunday → index 0 = Sunday for weekday names.
const SUNDAY_2021 = new Date(2021, 7, 1);

/**
 * Month calendar built on native dates — single date or a range, with month/year
 * navigation, min/max and per-day `disabled`, today + selection highlights, and
 * a full WAI-ARIA grid: roving focus moves real DOM focus to the active day so
 * screen readers announce it. Keyboard: arrows move (RTL-aware), Home/End jump to
 * the week edges, PageUp/Down change month, Enter/Space selects.
 */
export function Calendar({
  mode = "single",
  value: valueProp,
  defaultValue = null,
  onChange,
  min,
  max,
  disabled,
  weekStartsOn = 1,
  dayShape = "circle",
  numberOfMonths = 1,
  captionLayout = "buttons",
  fromYear,
  toYear,
  locale,
  messages,
  className,
}: CalendarProps) {
  const t = { ...DEFAULT_CALENDAR_MESSAGES, ...messages };
  const rootRef = React.useRef<HTMLDivElement>(null);
  // locale-driven names + formatting (no hard-coded English)
  const monthNames = React.useMemo(() => {
    const f = new Intl.DateTimeFormat(locale, { month: "long" });
    return Array.from({ length: 12 }, (_, m) => f.format(new Date(2021, m, 1)));
  }, [locale]);
  const weekdayNames = React.useMemo(() => {
    const f = new Intl.DateTimeFormat(locale, { weekday: "short" });
    return Array.from({ length: 7 }, (_, i) =>
      f.format(new Date(SUNDAY_2021.getFullYear(), SUNDAY_2021.getMonth(), 1 + i)),
    );
  }, [locale]);
  const weekdayLongNames = React.useMemo(() => {
    const f = new Intl.DateTimeFormat(locale, { weekday: "long" });
    return Array.from({ length: 7 }, (_, i) =>
      f.format(new Date(SUNDAY_2021.getFullYear(), SUNDAY_2021.getMonth(), 1 + i)),
    );
  }, [locale]);
  const dayLabelFmt = React.useMemo(
    () => new Intl.DateTimeFormat(locale, { dateStyle: "long" }),
    [locale],
  );
  const captionFmt = React.useMemo(
    () => new Intl.DateTimeFormat(locale, { month: "long", year: "numeric" }),
    [locale],
  );
  const round = dayShape === "circle" ? "rounded-full" : "rounded-lg";
  const months = Math.max(1, numberOfMonths);
  const nowYear = new Date().getFullYear();
  const yearFrom = fromYear ?? min?.getFullYear() ?? nowYear - 100;
  const yearTo = toYear ?? max?.getFullYear() ?? nowYear + 10;
  const years = React.useMemo(
    () => Array.from({ length: Math.max(1, yearTo - yearFrom + 1) }, (_, i) => yearFrom + i),
    [yearFrom, yearTo],
  );
  const [value, setValue] = useControllable<Date | DateRange | null>(
    valueProp,
    defaultValue,
    onChange,
  );

  const asRange = (v: Date | DateRange | null): DateRange =>
    v && "from" in (v as DateRange) ? (v as DateRange) : { from: null, to: null };
  const single = mode === "single" ? (value as Date | null) : null;
  const range = mode === "range" ? asRange(value) : { from: null, to: null };

  // the month being viewed — seeded from the selection (or today)
  const seed =
    (mode === "single" ? single : range.from) ?? new Date();
  const [view, setView] = React.useState(() => new Date(seed.getFullYear(), seed.getMonth(), 1));
  const [focused, setFocused] = React.useState<Date>(() => startOfDay(seed));
  const [hover, setHover] = React.useState<Date | null>(null);

  const today = startOfDay(new Date());
  const headers = React.useMemo(
    () => Array.from({ length: 7 }, (_, i) => weekdayNames[(weekStartsOn + i) % 7]),
    [weekStartsOn, weekdayNames],
  );
  const longHeaders = React.useMemo(
    () => Array.from({ length: 7 }, (_, i) => weekdayLongNames[(weekStartsOn + i) % 7]),
    [weekStartsOn, weekdayLongNames],
  );

  const isDisabled = (d: Date) =>
    (min && isBefore(d, min)) || (max && isAfter(d, max)) || (disabled?.(d) ?? false);

  // keep the visible month + roving focus in sync with the selection when it is
  // changed externally (presets, a controlled parent, or a click).
  const anchor = mode === "single" ? single : range.from;
  const anchorKey = anchor ? `${anchor.getFullYear()}-${anchor.getMonth()}-${anchor.getDate()}` : "";
  React.useEffect(() => {
    if (!anchor) return;
    const y = anchor.getFullYear();
    const m = anchor.getMonth();
    setView((v) => (v.getFullYear() === y && v.getMonth() === m ? v : new Date(y, m, 1)));
    setFocused(startOfDay(anchor));
    // anchorKey encodes the anchor's y/m/d; re-run only when the day changes
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [anchorKey]);

  // roving focus: move real DOM focus onto the active day so AT announces it —
  // but only when focus already lives inside the calendar (never steal it).
  React.useEffect(() => {
    const root = rootRef.current;
    if (!root || !root.contains(document.activeElement)) return;
    root
      .querySelector<HTMLButtonElement>(`[data-day="${focused.getTime()}"]`)
      ?.focus();
  }, [focused, view]);

  const goMonth = (n: number) => setView((v) => addMonths(v, n));
  // set a given panel (index) to a year/month; the shared `view` shifts so that
  // this panel lands on the chosen month
  const setPanel = (index: number, year: number, month: number) =>
    setView(new Date(year, month - index, 1));

  const selectCls =
    "cursor-pointer appearance-none rounded-md bg-transparent py-1 ps-2 pe-6 text-sm font-semibold tabular-nums text-foreground transition-colors hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring";

  const select = (d: Date) => {
    if (isDisabled(d)) return;
    const day = startOfDay(d);
    if (mode === "single") {
      setValue(day);
      return;
    }
    // range: first click sets `from`; second completes (ordering handled)
    const r = range;
    if (!r.from || (r.from && r.to)) {
      setValue({ from: day, to: null });
    } else {
      setValue(isBefore(day, r.from) ? { from: day, to: r.from } : { from: r.from, to: day });
    }
  };

  const onKeyDown = (e: React.KeyboardEvent) => {
    // let the month/year dropdowns (and any other native control) keep their keys
    const tag = (e.target as HTMLElement).tagName;
    if (tag === "SELECT" || tag === "OPTION" || tag === "INPUT") return;
    // arrows follow the visual layout, so they flip under RTL
    const rtl = getComputedStyle(e.currentTarget as HTMLElement).direction === "rtl";
    const dow = (focused.getDay() - weekStartsOn + 7) % 7; // column within the row
    let next: Date;
    switch (e.key) {
      case "ArrowLeft":
        next = addDays(focused, rtl ? 1 : -1);
        break;
      case "ArrowRight":
        next = addDays(focused, rtl ? -1 : 1);
        break;
      case "ArrowUp":
        next = addDays(focused, -7);
        break;
      case "ArrowDown":
        next = addDays(focused, 7);
        break;
      case "Home":
        next = addDays(focused, -dow);
        break;
      case "End":
        next = addDays(focused, 6 - dow);
        break;
      case "PageUp":
        next = addMonths(focused, -1);
        break;
      case "PageDown":
        next = addMonths(focused, 1);
        break;
      case "Enter":
      case " ":
        e.preventDefault();
        select(focused);
        return;
      default:
        return;
    }
    e.preventDefault();
    const clamped = clampDay(next, min, max);
    setFocused(clamped);
    if (clamped.getMonth() !== view.getMonth() || clamped.getFullYear() !== view.getFullYear()) {
      setView(new Date(clamped.getFullYear(), clamped.getMonth(), 1));
    }
  };

  const isSelected = (d: Date) =>
    mode === "single" ? sameDay(single, d) : sameDay(range.from, d) || sameDay(range.to, d);

  // live range preview while picking the second endpoint
  const previewTo = mode === "range" && range.from && !range.to ? hover : range.to;
  const isInRange = (d: Date) =>
    mode === "range" && inRange(d, range.from, previewTo);

  // the grid dates only depend on the visible month(s) + week start, so build them
  // once per view — not on every hover/focus/selection re-render.
  const monthGrids = React.useMemo(
    () =>
      Array.from({ length: months }, (_, i) => {
        const monthDate = addMonths(view, i);
        return { monthDate, grid: buildGrid(monthDate, weekStartsOn) };
      }),
    [view, months, weekStartsOn],
  );

  const renderMonth = ({ monthDate, grid }: { monthDate: Date; grid: Date[] }, index: number) => {
    const isFirst = index === 0;
    const isLast = index === months - 1;
    return (
      <div key={`${monthDate.getFullYear()}-${monthDate.getMonth()}`} data-bpdm-slot="calendar-month" className="w-[17rem]">
        {/* header — kept OUTSIDE role="grid" so its nav + selects aren't grid rows */}
        <div data-bpdm-slot="calendar-header" className="mb-2 flex items-center justify-between px-1">
          <button
            type="button"
            aria-label={t.previousMonth}
            onClick={() => goMonth(-1)}
            className={cn(
              "inline-flex size-7 cursor-pointer items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-muted hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring [&_svg]:size-4",
              !isFirst && "invisible",
            )}
          >
            <ChevronLeft className="rtl:-scale-x-100" aria-hidden="true" />
          </button>
          {captionLayout === "dropdown" ? (
            <div className="flex items-center gap-1">
              <div className="relative inline-flex items-center">
                <select
                  aria-label={t.month}
                  value={monthDate.getMonth()}
                  onChange={(e) => setPanel(index, monthDate.getFullYear(), Number(e.target.value))}
                  className={selectCls}
                >
                  {monthNames.map((m, mi) => (
                    <option key={m} value={mi}>
                      {m}
                    </option>
                  ))}
                </select>
                <ChevronDown className="pointer-events-none absolute end-1.5 size-3.5 text-muted-foreground" aria-hidden="true" />
              </div>
              <div className="relative inline-flex items-center">
                <select
                  aria-label={t.year}
                  value={monthDate.getFullYear()}
                  onChange={(e) => setPanel(index, Number(e.target.value), monthDate.getMonth())}
                  className={selectCls}
                >
                  {years.map((y) => (
                    <option key={y} value={y}>
                      {y}
                    </option>
                  ))}
                </select>
                <ChevronDown className="pointer-events-none absolute end-1.5 size-3.5 text-muted-foreground" aria-hidden="true" />
              </div>
            </div>
          ) : (
            <span className="text-sm font-semibold tabular-nums">
              {captionFmt.format(monthDate)}
            </span>
          )}
          <button
            type="button"
            aria-label={t.nextMonth}
            onClick={() => goMonth(1)}
            className={cn(
              "inline-flex size-7 cursor-pointer items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-muted hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring [&_svg]:size-4",
              !isLast && "invisible",
            )}
          >
            <ChevronRight className="rtl:-scale-x-100" aria-hidden="true" />
          </button>
        </div>

        {/* the grid: weekday header row + week rows are its only (direct) children */}
        <div
          role="grid"
          aria-label={captionFmt.format(monthDate)}
          aria-multiselectable={mode === "range" ? true : undefined}
          onKeyDown={onKeyDown}
          data-bpdm-slot="calendar-grid"
          className="flex flex-col gap-0.5 outline-none"
        >
          <div role="row" data-bpdm-slot="calendar-weekdays" className="grid grid-cols-7">
            {headers.map((w, i) => (
              <div
                key={i}
                role="columnheader"
                aria-label={longHeaders[i]}
                className="grid h-8 place-items-center text-xs font-medium text-muted-foreground"
              >
                {w}
              </div>
            ))}
          </div>
          {Array.from({ length: 6 }, (_, wk) => (
            <div key={wk} role="row" data-bpdm-slot="calendar-week" className="grid grid-cols-7">
              {grid.slice(wk * 7, wk * 7 + 7).map((d) => {
                const outside = d.getMonth() !== monthDate.getMonth();
                const selected = isSelected(d);
                const disabledDay = isDisabled(d);
                const rangeMid = isInRange(d);
                const isToday = sameDay(d, today);
                const isFocused = sameDay(d, focused);
                const rangeStart = mode === "range" && sameDay(range.from, d) && (range.to || previewTo);
                const rangeEnd = mode === "range" && sameDay(range.to ?? previewTo, d) && range.from && !sameDay(range.from, d);

                return (
                  <div
                    key={d.getTime()}
                    role="gridcell"
                    aria-selected={selected}
                    className={cn(
                      "relative grid place-items-center",
                      // soft range-band background spanning the row
                      (rangeMid || rangeStart || rangeEnd) && "bg-[color-mix(in_srgb,var(--primary)_14%,transparent)]",
                      rangeStart && (dayShape === "circle" ? "rounded-s-full" : "rounded-s-lg"),
                      rangeEnd && (dayShape === "circle" ? "rounded-e-full" : "rounded-e-lg"),
                    )}
                  >
                    <button
                      type="button"
                      data-day={d.getTime()}
                      tabIndex={isFocused ? 0 : -1}
                      disabled={disabledDay}
                      onClick={() => select(d)}
                      onMouseEnter={mode === "range" ? () => setHover(d) : undefined}
                      onMouseLeave={mode === "range" ? () => setHover(null) : undefined}
                      aria-label={dayLabelFmt.format(d)}
                      aria-current={isToday ? "date" : undefined}
                      data-bpdm-slot="calendar-day"
                      className={cn(
                    "grid size-9 cursor-pointer place-items-center text-sm tabular-nums transition-[background-color,color,transform] duration-[var(--bpdm-duration-fast)] focus:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 focus-visible:ring-offset-background",
                    round,
                    "hover:bg-muted active:scale-90",
                    outside && "text-muted-foreground",
                    !outside && !selected && "text-foreground",
                    isToday && !selected && "font-semibold text-foreground ring-1 ring-inset ring-primary",
                    selected &&
                      "bg-primary font-semibold text-primary-foreground hover:bg-primary animate-[bpdm-indicator-in_var(--bpdm-duration-base)_var(--bpdm-ease-overshoot)]",
                    disabledDay && "pointer-events-none text-muted-foreground/30 line-through",
                  )}
                    >
                      {d.getDate()}
                    </button>
                  </div>
                );
              })}
            </div>
          ))}
        </div>
      </div>
    );
  };

  return (
    <div
      ref={rootRef}
      role="group"
      aria-label={t.calendar}
      data-bpdm="" data-bpdm-slot="calendar"
      className={cn(
        "flex w-fit select-none gap-5 rounded-[var(--radius)] p-3",
        className,
      )}
    >
      {monthGrids.map((m, i) => renderMonth(m, i))}
    </div>
  );
}

// DatePicker (trigger + popover calendar)
function fmt(d: Date, locale?: string) {
  return d.toLocaleDateString(locale, { day: "numeric", month: "short", year: "numeric" });
}
function fmtValue(mode: "single" | "range", v: Date | DateRange | null, locale?: string): string {
  if (!v) return "";
  if (mode === "single") return fmt(v as Date, locale);
  const r = v as DateRange;
  if (r.from && r.to) return `${fmt(r.from, locale)} – ${fmt(r.to, locale)}`;
  if (r.from) return `${fmt(r.from, locale)} – …`;
  return "";
}

export interface DateRangePreset {
  label: string;
  /** Computed at click time so "today"-relative ranges stay correct. */
  range: () => DateRange;
}

/** Common range presets for dashboards — pass to `<DatePicker mode="range" presets={…} />`. */
export const defaultRangePresets: DateRangePreset[] = [
  {
    label: "Last 7 days",
    range: () => {
      const to = startOfDay(new Date());
      return { from: new Date(to.getFullYear(), to.getMonth(), to.getDate() - 6), to };
    },
  },
  {
    label: "Last 30 days",
    range: () => {
      const to = startOfDay(new Date());
      return { from: new Date(to.getFullYear(), to.getMonth(), to.getDate() - 29), to };
    },
  },
  {
    label: "This month",
    range: () => {
      const n = new Date();
      return { from: new Date(n.getFullYear(), n.getMonth(), 1), to: startOfDay(n) };
    },
  },
  {
    label: "This year",
    range: () => {
      const n = new Date();
      return { from: new Date(n.getFullYear(), 0, 1), to: startOfDay(n) };
    },
  },
  {
    label: "Previous year",
    range: () => {
      const y = new Date().getFullYear() - 1;
      return { from: new Date(y, 0, 1), to: new Date(y, 11, 31) };
    },
  },
];

export interface DatePickerProps extends Omit<CalendarProps, "className"> {
  /** Range-mode quick presets shown beside the calendar (e.g. defaultRangePresets). */
  presets?: DateRangePreset[];
  placeholder?: string;
  /** Show a clear (×) button when a value is set. Default true. */
  clearable?: boolean;
  /** Disable the whole trigger (distinct from `disabled`, which filters days). */
  disabledInput?: boolean;
  /**
   * Buffer the selection and only commit on **Apply**. Adds a Cancel/Apply
   * footer; Cancel, Escape and outside-click discard the draft. Default false
   * (pick commits immediately).
   */
  confirm?: boolean;
  /** aria-invalid styling on the trigger. */
  invalid?: boolean;
  id?: string;
  className?: string;
  /** Classes on the popover panel. */
  contentClassName?: string;
}

const rangeComplete = (v: Date | DateRange | null, mode: "single" | "range") =>
  mode === "single" ? !!v : !!((v as DateRange | null)?.from && (v as DateRange | null)?.to);

/**
 * Date (or range) picker — a trigger showing the formatted value that opens a
 * `Calendar` in a popover. Without `confirm`, single mode closes on pick and range
 * closes once both ends are chosen. With `confirm`, the selection is buffered and
 * only committed on Apply. Controlled or uncontrolled, clearable, min/max + disabled days.
 */
export function DatePicker({
  mode = "single",
  value: valueProp,
  defaultValue = null,
  onChange,
  placeholder = "Pick a date",
  clearable = true,
  disabledInput = false,
  confirm = false,
  invalid = false,
  id,
  className,
  contentClassName,
  numberOfMonths,
  presets,
  ...calendarProps
}: DatePickerProps) {
  // range pickers show two months by default; single shows one
  const monthsToShow = numberOfMonths ?? (mode === "range" ? 2 : 1);
  const [open, setOpen] = React.useState(false);
  const [value, setValue] = useControllable<Date | DateRange | null>(
    valueProp,
    defaultValue,
    onChange,
  );
  // in confirm mode the popover edits a draft; nothing is committed until Apply
  const [draft, setDraft] = React.useState<Date | DateRange | null>(value);

  const handleOpenChange = (o: boolean) => {
    if (o && confirm) setDraft(value); // seed the draft from the committed value
    setOpen(o);
  };

  // commit + auto-close (non-confirm), else just update the draft
  const commit = (v: Date | DateRange | null) => {
    setValue(v);
    if (mode === "single") setOpen(false);
    else if (v && (v as DateRange).from && (v as DateRange).to) setOpen(false);
  };
  const pick = confirm ? setDraft : commit;

  const cancel = () => setOpen(false); // draft is discarded (re-seeded on next open)
  const apply = () => {
    setValue(draft);
    setOpen(false);
  };

  const calValue = confirm ? draft : value;
  const text = fmtValue(mode, value, calendarProps.locale);
  const hasValue = mode === "single" ? !!value : !!(value as DateRange | null)?.from;
  const showClear = clearable && hasValue && !disabledInput;
  const messages = calendarProps.messages;

  const calendar = (
    <Calendar
      mode={mode}
      value={calValue}
      onChange={pick}
      numberOfMonths={monthsToShow}
      {...calendarProps}
    />
  );

  return (
    <div data-bpdm="" data-bpdm-slot="date-picker" className="relative w-full">
      <Popover
        open={open}
        onOpenChange={handleOpenChange}
        align="start"
        className={cn("w-auto p-0", contentClassName)}
        trigger={
          <button
            type="button"
            id={id}
            disabled={disabledInput}
            aria-invalid={invalid || undefined}
            data-bpdm-slot="date-picker-trigger"
            className={cn(
              "group inline-flex h-10 w-full min-w-[14rem] cursor-pointer items-center gap-2 rounded-[var(--radius)] border border-input bg-background ps-3 text-start text-sm transition-colors hover:border-ring/60 focus-visible:border-ring focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 aria-[invalid=true]:border-destructive aria-[invalid=true]:focus-visible:ring-destructive",
              showClear ? "pe-9" : "pe-3",
              className,
            )}
          >
            <CalendarDays className="size-4 shrink-0 text-muted-foreground" aria-hidden="true" />
            <span className={cn("flex-1 truncate", !hasValue && "text-muted-foreground")}>
              {text || placeholder}
            </span>
          </button>
        }
      >
        <div className="flex flex-col">
          {mode === "range" && presets && presets.length > 0 ? (
            <div className="flex flex-col sm:flex-row">
              <div className="flex shrink-0 gap-1 overflow-x-auto border-b border-border p-2 sm:max-w-[9rem] sm:flex-col sm:gap-0.5 sm:overflow-visible sm:border-b-0 sm:border-e">
                {presets.map((p) => {
                  const r = calValue as DateRange | null;
                  const pr = p.range();
                  const active = !!r && sameDay(r.from, pr.from) && sameDay(r.to, pr.to);
                  return (
                    <button
                      key={p.label}
                      type="button"
                      onClick={() => pick(p.range())}
                      data-bpdm-slot="date-picker-preset"
                      className={cn(
                        "shrink-0 cursor-pointer whitespace-nowrap rounded-md px-2.5 py-1.5 text-start text-sm transition-colors hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
                        active ? "bg-muted font-medium text-foreground" : "text-muted-foreground",
                      )}
                    >
                      {p.label}
                    </button>
                  );
                })}
              </div>
              {calendar}
            </div>
          ) : (
            calendar
          )}
          {confirm && (
            <div className="flex items-center justify-end gap-2 border-t border-border p-2">
              <button
                type="button"
                onClick={cancel}
                className="cursor-pointer rounded-md px-3 py-1.5 text-sm font-medium text-muted-foreground transition-colors hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
              >
                {messages?.cancel ?? "Cancel"}
              </button>
              <button
                type="button"
                onClick={apply}
                disabled={!rangeComplete(draft, mode)}
                className="cursor-pointer rounded-md bg-primary px-3 py-1.5 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 focus-visible:ring-offset-background disabled:cursor-not-allowed disabled:opacity-50"
              >
                {messages?.apply ?? "Apply"}
              </button>
            </div>
          )}
        </div>
      </Popover>
      {showClear && (
        <button
          type="button"
          aria-label={messages?.clear ?? "Clear"}
          onClick={() => commit(mode === "single" ? null : { from: null, to: null })}
          data-bpdm-slot="date-picker-clear"
          className="absolute end-2 top-1/2 z-10 inline-flex size-5 -translate-y-1/2 cursor-pointer items-center justify-center rounded-full text-muted-foreground/70 transition-colors hover:bg-muted hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring [&_svg]:size-3.5"
        >
          <X aria-hidden="true" />
        </button>
      )}
    </div>
  );
}

// packages/angular/src/lib/calendar/calendar.ts
import {
  afterEveryRender,
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  inject,
  input,
  model,
  signal,
} from "@angular/core";
import { cn } from "@bpdm/variants";
import {
  addMonths,
  buildGrid,
  clampDay,
  type DatePredicate,
  type DateRange,
  inRange,
  isAfter,
  isBefore,
  sameDay,
  startOfDay,
} from "./date-utils";

export type CalendarMode = "single" | "range";
export type CalendarDayShape = "circle" | "square";
export type CalendarCaptionLayout = "buttons" | "dropdown";

export interface CalendarMessages {
  calendar?: string;
  previousMonth?: string;
  nextMonth?: string;
  month?: string;
  year?: string;
  clear?: string;
  /** DatePicker `confirm` footer — discard the draft. */
  cancel?: string;
  /** DatePicker `confirm` footer — commit the draft. */
  apply?: string;
}

// Aug 1 2021 is a Sunday → index 0 = Sunday for weekday names.
const SUNDAY_2021 = new Date(2021, 7, 1);

function addDays(d: Date, n: number): Date {
  return new Date(d.getFullYear(), d.getMonth(), d.getDate() + n);
}

interface DayCell {
  key: number;
  date: Date;
  label: number;
  ariaLabel: string;
  disabled: boolean;
  selected: boolean;
  today: boolean;
  focused: boolean;
  wrapperClass: string;
  buttonClass: string;
}
interface MonthView {
  key: string;
  index: number;
  isFirst: boolean;
  isLast: boolean;
  monthIndex: number;
  year: number;
  label: string;
  weeks: DayCell[][];
}

/**
 * `<bpdm-calendar>` — month calendar built on native dates: single date or a
 * range, with month/year navigation, `min`/`max` and per-day `disabled`, today +
 * selection highlights, and a full WAI-ARIA grid: roving focus moves real DOM
 * focus to the active day so screen readers announce it. Keyboard: arrows move
 * (RTL-aware), Home/End jump to the week edges, PageUp/Down change month,
 * Enter/Space selects. Controlled or uncontrolled via `[(value)]`.
 *
 * ```html
 * <bpdm-calendar [(value)]="date" />
 * <bpdm-calendar mode="range" [(value)]="range" [numberOfMonths]="2" />
 * <bpdm-calendar captionLayout="dropdown" [(value)]="date" />
 * ```
 */
@Component({
  selector: "bpdm-calendar",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: "block w-fit" },
  template: `
    <div role="group" data-bpdm="" data-bpdm-slot="calendar" [attr.aria-label]="t().calendar" [class]="rootClass()">
      @for (m of months(); track m.key) {
        <div data-bpdm-slot="calendar-month" class="w-[17rem]">
          <!-- header — kept OUTSIDE role="grid" so its nav + selects aren't grid rows -->
          <div data-bpdm-slot="calendar-header" class="mb-2 flex items-center justify-between px-1">
            <button
              type="button"
              [attr.aria-label]="t().previousMonth"
              (click)="goMonth(-1)"
              [class]="navClass(m.isFirst)"
            >
              <svg viewBox="0 0 24 24" fill="none" class="size-4 rtl:-scale-x-100" aria-hidden="true">
                <path d="m15 18-6-6 6-6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
              </svg>
            </button>

            @if (captionLayout() === "dropdown") {
              <div class="flex items-center gap-1">
                <div class="relative inline-flex items-center">
                  <select
                    [attr.aria-label]="t().month"
                    [value]="m.monthIndex"
                    (change)="setPanel(m.index, m.year, +$any($event.target).value)"
                    [class]="selectCls"
                  >
                    @for (mo of monthOptions(); track mo.value) {
                      <option [value]="mo.value">{{ mo.label }}</option>
                    }
                  </select>
                  <svg viewBox="0 0 24 24" fill="none" class="pointer-events-none absolute end-1.5 size-3.5 text-muted-foreground" aria-hidden="true">
                    <path d="m6 9 6 6 6-6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                  </svg>
                </div>
                <div class="relative inline-flex items-center">
                  <select
                    [attr.aria-label]="t().year"
                    [value]="m.year"
                    (change)="setPanel(m.index, +$any($event.target).value, m.monthIndex)"
                    [class]="selectCls"
                  >
                    @for (y of years(); track y) {
                      <option [value]="y">{{ y }}</option>
                    }
                  </select>
                  <svg viewBox="0 0 24 24" fill="none" class="pointer-events-none absolute end-1.5 size-3.5 text-muted-foreground" aria-hidden="true">
                    <path d="m6 9 6 6 6-6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                  </svg>
                </div>
              </div>
            } @else {
              <span class="text-sm font-semibold tabular-nums">{{ m.label }}</span>
            }

            <button
              type="button"
              [attr.aria-label]="t().nextMonth"
              (click)="goMonth(1)"
              [class]="navClass(m.isLast)"
            >
              <svg viewBox="0 0 24 24" fill="none" class="size-4 rtl:-scale-x-100" aria-hidden="true">
                <path d="m9 18 6-6-6-6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
              </svg>
            </button>
          </div>

          <!-- the grid: weekday header row + week rows are its only (direct) children -->
          <div
            role="grid"
            data-bpdm-slot="calendar-grid"
            [attr.aria-label]="m.label"
            [attr.aria-multiselectable]="mode() === 'range' ? true : null"
            (keydown)="onKeyDown($event)"
            class="flex flex-col gap-0.5 outline-none"
          >
            <div role="row" data-bpdm-slot="calendar-weekdays" class="grid grid-cols-7">
              @for (w of headers(); track $index) {
                <div role="columnheader" [attr.aria-label]="longHeaders()[$index]" class="grid h-8 place-items-center text-xs font-medium text-muted-foreground">{{ w }}</div>
              }
            </div>
            @for (week of m.weeks; track $index) {
              <div role="row" data-bpdm-slot="calendar-week" class="grid grid-cols-7">
                @for (d of week; track d.key) {
                  <div role="gridcell" [attr.aria-selected]="d.selected" [class]="d.wrapperClass">
                    <button
                      type="button"
                      data-bpdm-slot="calendar-day"
                      [attr.data-day]="d.key"
                      [tabindex]="d.focused ? 0 : -1"
                      [disabled]="d.disabled"
                      (click)="select(d.date)"
                      (mouseenter)="onHover(d.date)"
                      (mouseleave)="onHover(null)"
                      [attr.aria-label]="d.ariaLabel"
                      [attr.aria-current]="d.today ? 'date' : null"
                      [class]="d.buttonClass"
                    >
                      {{ d.label }}
                    </button>
                  </div>
                }
              </div>
            }
          </div>
        </div>
      }
    </div>
  `,
})
export class BpdmCalendar {
  /** "single" → a Date; "range" → a { from, to }. Default "single". */
  readonly mode = input<CalendarMode>("single");
  /** Controlled / uncontrolled value — `[(value)]`. */
  readonly value = model<Date | DateRange | null>(null);
  readonly min = input<Date | undefined>(undefined);
  readonly max = input<Date | undefined>(undefined);
  /** Disable specific days, e.g. weekends. */
  readonly disabled = input<DatePredicate | undefined>(undefined);
  /** 0 = Sunday, 1 = Monday. Default 1. */
  readonly weekStartsOn = input<0 | 1>(1);
  /** Shape of the day highlight: "circle" (default) or "square" (rounded-corner square). */
  readonly dayShape = input<CalendarDayShape>("circle");
  /** How many months to show side by side. Default 1. */
  readonly numberOfMonths = input<number>(1);
  /** Header style: "buttons" (prev/next only) or "dropdown" (month + year menus). */
  readonly captionLayout = input<CalendarCaptionLayout>("buttons");
  /** Year-dropdown range. Default: 100 years back to 10 years ahead. */
  readonly fromYear = input<number | undefined>(undefined);
  readonly toYear = input<number | undefined>(undefined);
  readonly classInput = input<string>("", { alias: "class" });
  /** BCP 47 locale for month/weekday names + date formatting (e.g. "de-DE", "ar"). */
  readonly locale = input<string | undefined>(undefined);
  /** Override the control labels (screen-reader text) for i18n. */
  readonly messages = input<CalendarMessages>({});

  private readonly host = inject(ElementRef<HTMLElement>);
  // day (getTime) to move real DOM focus onto after the next render (keyboard nav)
  private pendingFocusKey: number | null = null;

  constructor() {
    afterEveryRender(() => {
      const key = this.pendingFocusKey;
      if (key == null) return;
      this.pendingFocusKey = null;
      (
        this.host.nativeElement.querySelector(`[data-day="${key}"]`) as HTMLButtonElement | null
      )?.focus();
    });
  }

  protected readonly t = computed(() => ({
    calendar: "Calendar",
    previousMonth: "Previous month",
    nextMonth: "Next month",
    month: "Month",
    year: "Year",
    clear: "Clear",
    cancel: "Cancel",
    apply: "Apply",
    ...this.messages(),
  }));
  protected readonly monthNames = computed(() => {
    const f = new Intl.DateTimeFormat(this.locale(), { month: "long" });
    return Array.from({ length: 12 }, (_, m) => f.format(new Date(2021, m, 1)));
  });
  private readonly weekdayNames = computed(() => {
    const f = new Intl.DateTimeFormat(this.locale(), { weekday: "short" });
    return Array.from({ length: 7 }, (_, i) =>
      f.format(new Date(SUNDAY_2021.getFullYear(), SUNDAY_2021.getMonth(), 1 + i)),
    );
  });
  private readonly weekdayLongNames = computed(() => {
    const f = new Intl.DateTimeFormat(this.locale(), { weekday: "long" });
    return Array.from({ length: 7 }, (_, i) =>
      f.format(new Date(SUNDAY_2021.getFullYear(), SUNDAY_2021.getMonth(), 1 + i)),
    );
  });
  private readonly dayLabelFmt = computed(() => new Intl.DateTimeFormat(this.locale(), { dateStyle: "long" }));
  private readonly captionFmt = computed(
    () => new Intl.DateTimeFormat(this.locale(), { month: "long", year: "numeric" }),
  );
  protected readonly monthOptions = computed(() =>
    this.monthNames().map((label, value) => ({ label, value })),
  );
  protected readonly selectCls =
    "cursor-pointer appearance-none rounded-md bg-transparent py-1 ps-2 pe-6 text-sm font-semibold tabular-nums text-foreground transition-colors hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring";

  protected readonly hover = signal<Date | null>(null);
  // null = "follow the selection"; set explicitly once the user navigates
  private readonly viewOverride = signal<Date | null>(null);
  private readonly focusOverride = signal<Date | null>(null);

  private get today(): Date {
    return startOfDay(new Date());
  }
  private readonly monthsCount = computed(() => Math.max(1, this.numberOfMonths()));

  private asRange(v: Date | DateRange | null): DateRange {
    return v && "from" in (v as DateRange) ? (v as DateRange) : { from: null, to: null };
  }
  private get single(): Date | null {
    return this.mode() === "single" ? (this.value() as Date | null) : null;
  }
  private get range(): DateRange {
    return this.mode() === "range" ? this.asRange(this.value()) : { from: null, to: null };
  }

  private readonly seed = computed<Date>(() => {
    const s = this.mode() === "single" ? this.single : this.range.from;
    return s ?? new Date();
  });
  private readonly viewMonth = computed<Date>(() => {
    const o = this.viewOverride();
    return o ?? new Date(this.seed().getFullYear(), this.seed().getMonth(), 1);
  });
  private readonly focused = computed<Date>(() => this.focusOverride() ?? startOfDay(this.seed()));

  protected readonly headers = computed(() =>
    Array.from({ length: 7 }, (_, i) => this.weekdayNames()[(this.weekStartsOn() + i) % 7]),
  );
  protected readonly longHeaders = computed(() =>
    Array.from({ length: 7 }, (_, i) => this.weekdayLongNames()[(this.weekStartsOn() + i) % 7]),
  );

  protected readonly years = computed(() => {
    const now = new Date().getFullYear();
    const from = this.fromYear() ?? this.min()?.getFullYear() ?? now - 100;
    const to = this.toYear() ?? this.max()?.getFullYear() ?? now + 10;
    return Array.from({ length: Math.max(1, to - from + 1) }, (_, i) => from + i);
  });

  protected readonly rootClass = computed(() =>
    cn("flex w-fit select-none gap-5 rounded-[var(--radius)] p-3", this.classInput()),
  );

  private isDisabled(d: Date): boolean {
    const min = this.min();
    const max = this.max();
    return (
      (!!min && isBefore(d, min)) ||
      (!!max && isAfter(d, max)) ||
      (this.disabled()?.(d) ?? false)
    );
  }

  protected readonly months = computed<MonthView[]>(() => {
    const count = this.monthsCount();
    const view = this.viewMonth();
    const mode = this.mode();
    const range = this.range;
    const single = this.single;
    const focused = this.focused();
    const hover = this.hover();
    const today = this.today;
    const shape = this.dayShape();
    const round = shape === "circle" ? "rounded-full" : "rounded-lg";

    // live range preview while picking the second endpoint
    const previewTo = mode === "range" && range.from && !range.to ? hover : range.to;

    const out: MonthView[] = [];
    for (let index = 0; index < count; index++) {
      const monthDate = addMonths(view, index);
      const grid = buildGrid(monthDate, this.weekStartsOn());
      const days: DayCell[] = grid.map((d) => {
        const outside = d.getMonth() !== monthDate.getMonth();
        const selected =
          mode === "single" ? sameDay(single, d) : sameDay(range.from, d) || sameDay(range.to, d);
        const disabledDay = this.isDisabled(d);
        const rangeMid = mode === "range" && inRange(d, range.from, previewTo);
        const isToday = sameDay(d, today);
        const isFocused = sameDay(d, focused);
        const rangeStart =
          mode === "range" && sameDay(range.from, d) && !!(range.to || previewTo);
        const rangeEnd =
          mode === "range" &&
          sameDay(range.to ?? previewTo, d) &&
          !!range.from &&
          !sameDay(range.from, d);

        const wrapperClass = cn(
          "relative grid place-items-center",
          (rangeMid || rangeStart || rangeEnd) &&
            "bg-[color-mix(in_srgb,var(--primary)_14%,transparent)]",
          rangeStart && (shape === "circle" ? "rounded-s-full" : "rounded-s-lg"),
          rangeEnd && (shape === "circle" ? "rounded-e-full" : "rounded-e-lg"),
        );
        const buttonClass = cn(
          "grid size-9 cursor-pointer place-items-center text-sm tabular-nums transition-[background-color,color,transform] duration-[var(--bpdm-duration-fast)] focus:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 focus-visible:ring-offset-background",
          round,
          "hover:bg-muted active:scale-90",
          outside && "text-muted-foreground",
          !outside && !selected && "text-foreground",
          isToday && !selected && "font-semibold text-foreground ring-1 ring-inset ring-primary",
          selected &&
            "bg-primary font-semibold text-primary-foreground hover:bg-primary animate-[bpdm-indicator-in_var(--bpdm-duration-base)_var(--bpdm-ease-overshoot)]",
          disabledDay && "pointer-events-none text-muted-foreground/30 line-through",
        );

        return {
          key: d.getTime(),
          date: d,
          label: d.getDate(),
          ariaLabel: this.dayLabelFmt().format(d),
          disabled: disabledDay,
          selected,
          today: isToday,
          focused: isFocused,
          wrapperClass,
          buttonClass,
        };
      });

      out.push({
        key: `${monthDate.getFullYear()}-${monthDate.getMonth()}`,
        index,
        isFirst: index === 0,
        isLast: index === count - 1,
        monthIndex: monthDate.getMonth(),
        year: monthDate.getFullYear(),
        label: this.captionFmt().format(monthDate),
        weeks: Array.from({ length: 6 }, (_, w) => days.slice(w * 7, w * 7 + 7)),
      });
    }
    return out;
  });

  protected navClass(visible: boolean): string {
    return cn(
      "inline-flex size-7 cursor-pointer items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-muted hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
      !visible && "invisible",
    );
  }

  protected goMonth(n: number): void {
    this.viewOverride.set(addMonths(this.viewMonth(), n));
  }

  // set a given panel (index) to a year/month; the shared view shifts so this
  // panel lands on the chosen month
  protected setPanel(index: number, year: number, month: number): void {
    this.viewOverride.set(new Date(year, month - index, 1));
  }

  // hover only drives the range preview; skip it in single mode so the grid
  // doesn't recompute on every mouse move.
  protected onHover(d: Date | null): void {
    if (this.mode() === "range") this.hover.set(d);
  }

  protected select(d: Date): void {
    if (this.isDisabled(d)) return;
    const day = startOfDay(d);
    // selection becomes the new anchor: let view + focus follow it again
    this.viewOverride.set(null);
    this.focusOverride.set(null);
    if (this.mode() === "single") {
      this.value.set(day);
      return;
    }
    const r = this.range;
    if (!r.from || (r.from && r.to)) {
      this.value.set({ from: day, to: null });
    } else {
      this.value.set(
        isBefore(day, r.from) ? { from: day, to: r.from } : { from: r.from, to: day },
      );
    }
  }

  protected onKeyDown(e: KeyboardEvent): void {
    // let the month/year dropdowns (and any other native control) keep their keys
    const tag = (e.target as HTMLElement).tagName;
    if (tag === "SELECT" || tag === "OPTION" || tag === "INPUT") return;
    const f = this.focused();
    // arrows follow the visual layout, so they flip under RTL
    const rtl = getComputedStyle(e.currentTarget as HTMLElement).direction === "rtl";
    const dow = (f.getDay() - this.weekStartsOn() + 7) % 7; // column within the row
    let next: Date;
    switch (e.key) {
      case "ArrowLeft":
        next = addDays(f, rtl ? 1 : -1);
        break;
      case "ArrowRight":
        next = addDays(f, rtl ? -1 : 1);
        break;
      case "ArrowUp":
        next = addDays(f, -7);
        break;
      case "ArrowDown":
        next = addDays(f, 7);
        break;
      case "Home":
        next = addDays(f, -dow);
        break;
      case "End":
        next = addDays(f, 6 - dow);
        break;
      case "PageUp":
        next = addMonths(f, -1);
        break;
      case "PageDown":
        next = addMonths(f, 1);
        break;
      case "Enter":
      case " ":
        e.preventDefault();
        this.select(f);
        return;
      default:
        return;
    }
    e.preventDefault();
    const clamped = clampDay(next, this.min(), this.max());
    this.focusOverride.set(clamped);
    const view = this.viewMonth();
    if (clamped.getMonth() !== view.getMonth() || clamped.getFullYear() !== view.getFullYear()) {
      this.viewOverride.set(new Date(clamped.getFullYear(), clamped.getMonth(), 1));
    }
    this.pendingFocusKey = clamped.getTime();
  }
}
