// packages/angular/src/lib/float-label/float-label.ts
import {
  afterNextRender,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  computed,
  inject,
  input,
} from "@angular/core";
import { cn, floatFloated, floatResting, type FloatLabelVariant } from "@bpdm/variants";

/**
 * `<bpdm-float-label>` — wraps a single input/textarea; the label rests as a
 * placeholder and floats up on focus or when filled (`over` / `in` / `on`).
 * Pure CSS via the Tailwind `peer` + `:placeholder-shown` trick — the wrapped
 * control automatically gets `peer` and a blank placeholder. Same look as React.
 *
 * ```html
 * <bpdm-float-label label="Email">
 *   <input bpdmInput id="email" [(ngModel)]="email" />
 * </bpdm-float-label>
 * ```
 */
@Component({
  selector: "bpdm-float-label",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: "relative block" },
  template: `
    <ng-content />
    <label [attr.for]="htmlFor()" [class]="labelClass()">{{ label() }}</label>
  `,
})
export class BpdmFloatLabel {
  readonly label = input.required<string>();
  /** id of the wrapped control; the label's `for` points here. */
  readonly htmlFor = input<string>();
  /** `over` floats above · `in` top-inside · `on` a notch on the border. */
  readonly variant = input<FloatLabelVariant>("over");

  private readonly el = inject<ElementRef<HTMLElement>>(ElementRef);

  protected readonly labelClass = computed(() =>
    cn(floatResting, floatFloated[this.variant()]),
  );

  constructor() {
    // mirror React's clone: give the wrapped control `peer` + a blank placeholder
    // (so :placeholder-shown drives the float) without the consumer wiring it up
    afterNextRender(() => {
      const control = this.el.nativeElement.querySelector<HTMLInputElement>(
        "input, textarea, select",
      );
      if (!control) return;
      control.classList.add("peer");
      if (this.variant() === "in") control.classList.add("pt-4");
      if (!control.getAttribute("placeholder")) control.setAttribute("placeholder", " ");
    });
  }
}

// packages/react/src/components/float-label.tsx
import * as React from "react";
import {
  floatFloated,
  floatResting,
  type FloatLabelVariant as Variant,
} from "@bpdm/variants";
import { cn } from "@/lib/utils";

export interface FloatLabelProps {
  label: string;
  /** id of the wrapped control; the label's htmlFor points here. */
  htmlFor?: string;
  /** over = floats above the field; in = top inside; on = notch on the border. */
  variant?: Variant;
  className?: string;
  /** A single input-like control (needs to be the label's previous sibling). */
  children: React.ReactElement<{
    id?: string;
    placeholder?: string;
    className?: string;
  }>;
}

// local aliases so the component body reads the same as before
const resting = floatResting;
const floated = floatFloated;

/**
 * Floating label wrapper. Wrap a single input; the label sits as
 * a placeholder and floats up on focus or when filled. Drives entirely on CSS via
 * the `peer` + `:placeholder-shown` trick — the input gets `peer` and a blank
 * placeholder injected automatically.
 */
export function FloatLabel({
  label,
  htmlFor,
  variant = "over",
  className,
  children,
}: FloatLabelProps) {
  const id = htmlFor ?? children.props.id;
  const control = React.cloneElement(children, {
    id,
    placeholder: children.props.placeholder ?? " ",
    className: cn(
      "peer",
      variant === "in" && "pt-4",
      children.props.className,
    ),
  });

  return (
    <div className={cn("relative", className)}>
      {control}
      <label htmlFor={id} className={cn(resting, floated[variant])}>
        {label}
      </label>
    </div>
  );
}
