// packages/angular/src/lib/step-dialog/step-dialog.ts
import { NgTemplateOutlet } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  Directive,
  effect,
  inject,
  input,
  model,
  output,
  signal,
  TemplateRef,
} from "@angular/core";
import { cn } from "@bpdm/variants";
import { BpdmButton } from "../button/button";
import { BpdmDialog, BpdmDialogBody, BpdmDialogFooter, type DialogSize } from "../dialog/dialog";

export interface StepDialogStep {
  title: string;
  description?: string;
  content: TemplateRef<unknown>;
}

// --- i18n ---
export interface StepDialogMessages {
  back: string;
  next: string;
  finish: string;
  /** sr-only progress text. Tokens {index} and {total} are interpolated. */
  step: string;
  /** aria-label for the inherited close (X) button. */
  close: string;
}

export const DEFAULT_STEP_DIALOG_MESSAGES: StepDialogMessages = {
  back: "Back",
  next: "Next",
  finish: "Finish",
  step: "Step {index} of {total}",
  close: "Close",
};

/**
 * `<bpdm-step-dialog>` — a multi-step "wizard" dialog: a progress stepper, per-step
 * content, and Back / Next / Finish navigation. Built on `<bpdm-dialog>`. The step
 * resets when the dialog closes; `(complete)` fires on Finish. Mirrors the React
 * `StepDialog`.
 *
 * ```html
 * <bpdm-step-dialog title="Set up workspace" [steps]="steps" (complete)="save()">
 *   <button bpdmButton bpdmStepDialogTrigger>Get started</button>
 * </bpdm-step-dialog>
 * ```
 */
@Component({
  selector: "bpdm-step-dialog",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [BpdmDialog, BpdmDialogBody, BpdmDialogFooter, BpdmButton, NgTemplateOutlet],
  host: { class: "contents" },
  template: `
    <ng-content select="[bpdmStepDialogTrigger]" />
    <bpdm-dialog
      [open]="open()"
      (openChange)="open.set($event)"
      [size]="size()"
      [title]="dialogTitle()"
      [description]="currentDescription()"
      [messages]="dialogMessages()"
    >
      <ng-template bpdmDialogBody>
        <div class="flex flex-col gap-8">
          <ol class="m-0 flex list-none items-center gap-2 p-0">
            <li class="sr-only" aria-live="polite">{{ progressText() }}</li>
            @for (s of steps(); track $index) {
              <li class="flex shrink-0 items-center gap-2" [attr.aria-current]="$index === step() ? 'step' : null">
                <span [class]="circleClass($index)">
                  @if ($index < step()) {
                    <svg viewBox="0 0 16 16" class="size-3.5" fill="none" aria-hidden="true">
                      <path d="M3.5 8.5l3 3 6-7" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                    </svg>
                  } @else {
                    {{ $index + 1 }}
                  }
                </span>
                <span [class]="$index === step() ? 'hidden text-sm font-medium text-foreground sm:inline' : 'hidden text-sm text-muted-foreground sm:inline'">
                  {{ s.title }}
                </span>
              </li>
              @if ($index < steps().length - 1) {
                <!-- Decorative connector — an <li> (not a bare <span>) so the <ol> has
                     only list-item children; aria-hidden keeps it out of the AT tree. -->
                <li
                  aria-hidden="true"
                  class="h-px flex-1 transition-colors duration-[var(--bpdm-duration-slow)] ease-[var(--bpdm-ease-out)]"
                  [class]="$index < step() ? 'bg-success' : 'bg-border'"
                ></li>
              }
            }
          </ol>
          @for (k of [step()]; track k) {
            <div class="animate-[bpdm-fade-in_var(--bpdm-duration-base)_var(--bpdm-ease-out)]">
              @if (currentContent()) {
                <ng-container [ngTemplateOutlet]="currentContent()!" />
              }
            </div>
          }
        </div>
      </ng-template>
      <ng-template bpdmDialogFooter>
        @if (step() > 0) {
          <button bpdmButton variant="secondary" appearance="ghost" (click)="back()">{{ t().back }}</button>
        }
        @if (step() < last()) {
          <button bpdmButton (click)="next()">{{ t().next }}</button>
        } @else {
          <button bpdmButton (click)="finish()">{{ finishText() || t().finish }}</button>
        }
      </ng-template>
    </bpdm-dialog>
  `,
})
export class BpdmStepDialog {
  readonly steps = input<StepDialogStep[]>([]);
  /** Overall dialog title (defaults to the current step's title). */
  readonly title = input("");
  readonly size = input<DialogSize>("md");
  readonly finishText = input("");
  /** Screen-reader / navigation strings (Back, Next, Finish, progress, close). */
  readonly messages = input<Partial<StepDialogMessages>>({});
  /** Open state — two-way bindable via `[(open)]`. */
  readonly open = model(false);
  /** Fired when the last step's Finish is clicked. */
  readonly complete = output<void>();

  protected readonly step = signal(0);
  protected readonly last = computed(() => Math.max(0, this.steps().length - 1));
  protected readonly currentStep = computed(() => this.steps()[Math.min(this.step(), this.last())]);
  protected readonly currentContent = computed(() => this.currentStep()?.content ?? null);
  protected readonly currentDescription = computed(() => this.currentStep()?.description ?? "");
  protected readonly dialogTitle = computed(() => this.title() || this.currentStep()?.title || "");
  protected readonly t = computed<StepDialogMessages>(() => ({
    ...DEFAULT_STEP_DIALOG_MESSAGES,
    ...this.messages(),
  }));
  protected readonly dialogMessages = computed(() => ({ close: this.t().close }));
  protected readonly progressText = computed(() =>
    this.t()
      .step.replace("{index}", String(Math.min(this.step(), this.last()) + 1))
      .replace("{total}", String(this.steps().length)),
  );

  constructor() {
    // restart the wizard whenever the dialog is closed
    effect(() => {
      if (!this.open()) this.step.set(0);
    });
  }

  openDialog(): void {
    this.open.set(true);
  }

  protected back(): void {
    this.step.update((s) => Math.max(0, s - 1));
  }

  protected next(): void {
    this.step.update((s) => Math.min(s + 1, this.last()));
  }

  protected finish(): void {
    this.complete.emit();
    this.open.set(false);
  }

  protected circleClass(i: number): string {
    const step = this.step();
    return cn(
      "grid size-6 shrink-0 place-items-center rounded-full text-xs font-medium transition-[background-color,border-color,color,transform] duration-[var(--bpdm-duration-base)] ease-[var(--bpdm-ease-overshoot)]",
      i < step
        ? "bg-success text-success-foreground"
        : i === step
          ? "scale-110 bg-primary text-primary-foreground ring-2 ring-primary ring-offset-2 ring-offset-background"
          : "border border-border text-muted-foreground",
    );
  }
}

/** Opens the nearest `<bpdm-step-dialog>` — put it on any trigger button. */
@Directive({
  selector: "[bpdmStepDialogTrigger]",
  host: { "(click)": "stepDialog.openDialog()" },
})
export class BpdmStepDialogTrigger {
  protected readonly stepDialog = inject(BpdmStepDialog);
}

// packages/react/src/components/step-dialog.tsx
import * as React from "react";
import { cn } from "@/lib/utils";
import { Dialog, DialogClose } from "./dialog";
import { Button } from "./button";

export interface StepDialogStep {
  title: string;
  description?: React.ReactNode;
  content: React.ReactNode;
}

// --- i18n ---
export interface StepDialogMessages {
  back: string;
  next: string;
  finish: string;
  /** sr-only progress text. Tokens {index} and {total} are interpolated. */
  step: string;
  /** aria-label for the inherited close (X) button. */
  close: string;
}

export const DEFAULT_STEP_DIALOG_MESSAGES: StepDialogMessages = {
  back: "Back",
  next: "Next",
  finish: "Finish",
  step: "Step {index} of {total}",
  close: "Close",
};

export interface StepDialogProps {
  steps: StepDialogStep[];
  trigger?: React.ReactNode;
  /** Overall dialog title (defaults to the current step's title). */
  title?: React.ReactNode;
  size?: "sm" | "md" | "lg" | "xl";
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  /** Fired when the last step's Finish is clicked. */
  onComplete?: () => void;
  finishText?: string;
  /** Screen-reader / navigation strings (Back, Next, Finish, progress, close). */
  messages?: Partial<StepDialogMessages>;
}

function CheckGlyph() {
  return (
    <svg viewBox="0 0 16 16" className="size-3.5" fill="none" aria-hidden>
      <path d="M3.5 8.5l3 3 6-7" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}

function Stepper({
  steps,
  current,
  progress,
}: {
  steps: StepDialogStep[];
  current: number;
  progress: string;
}) {
  return (
    <ol className="m-0 flex list-none items-center gap-2 p-0">
      <li className="sr-only" aria-live="polite">
        {progress}
      </li>
      {steps.map((s, i) => {
        const done = i < current;
        const active = i === current;
        return (
          <React.Fragment key={i}>
            <li className="flex shrink-0 items-center gap-2" aria-current={active ? "step" : undefined}>
              <span
                className={cn(
                  "grid size-6 shrink-0 place-items-center rounded-full text-xs font-medium transition-[background-color,border-color,color,transform] duration-[var(--bpdm-duration-base)] ease-[var(--bpdm-ease-overshoot)]",
                  done
                    ? "bg-success text-success-foreground"
                    : active
                      ? "scale-110 bg-primary text-primary-foreground ring-2 ring-primary ring-offset-2 ring-offset-background"
                      : "border border-border text-muted-foreground",
                )}
              >
                {done ? <CheckGlyph /> : i + 1}
              </span>
              <span
                className={cn(
                  "hidden text-sm sm:inline",
                  active ? "font-medium text-foreground" : "text-muted-foreground",
                )}
              >
                {s.title}
              </span>
            </li>
            {i < steps.length - 1 && (
              // Decorative connector — an <li> (not a bare <span>) so the <ol> has only
              // list-item children; aria-hidden keeps it out of the AT tree.
              <li
                aria-hidden="true"
                className={cn(
                  "h-px flex-1 transition-colors duration-[var(--bpdm-duration-slow)] ease-[var(--bpdm-ease-out)]",
                  i < current ? "bg-success" : "bg-border",
                )}
              />
            )}
          </React.Fragment>
        );
      })}
    </ol>
  );
}

/**
 * Multi-step "wizard" dialog — a progress stepper, per-step content, and
 * Back / Next / Finish navigation. Built on the Dialog. The step resets when the
 * dialog closes; `onComplete` fires on Finish.
 */
export function StepDialog({
  steps,
  trigger,
  title,
  size = "md",
  open,
  defaultOpen,
  onOpenChange,
  onComplete,
  finishText,
  messages,
}: StepDialogProps) {
  const [step, setStep] = React.useState(0);
  const last = steps.length - 1;
  const current = steps[Math.min(step, last)];
  const t = React.useMemo(() => ({ ...DEFAULT_STEP_DIALOG_MESSAGES, ...messages }), [messages]);
  const progress = t.step
    .replace("{index}", String(Math.min(step, last) + 1))
    .replace("{total}", String(steps.length));

  return (
    <Dialog
      open={open}
      defaultOpen={defaultOpen}
      onOpenChange={(o) => {
        onOpenChange?.(o);
        if (!o) setStep(0); // restart next time it opens
      }}
      trigger={trigger}
      size={size}
      title={title ?? current.title}
      description={current.description}
      messages={{ close: t.close }}
      // focus the panel itself, not the first field — a freshly opened wizard
      // shouldn't glow a field's focus ring before the user has interacted
      onOpenAutoFocus={(e) => {
        e.preventDefault();
        (e.currentTarget as HTMLElement | null)?.focus();
      }}
      footer={
        <>
          {step > 0 && (
            <Button variant="secondary" appearance="ghost" onClick={() => setStep((s) => s - 1)}>
              {t.back}
            </Button>
          )}
          {step < last ? (
            <Button onClick={() => setStep((s) => Math.min(s + 1, last))}>{t.next}</Button>
          ) : (
            <DialogClose asChild>
              <Button onClick={() => onComplete?.()}>{finishText ?? t.finish}</Button>
            </DialogClose>
          )}
        </>
      }
    >
      <div className="flex flex-col gap-8">
        <Stepper steps={steps} current={step} progress={progress} />
        <div
          key={step}
          className="animate-[bpdm-fade-in_var(--bpdm-duration-base)_var(--bpdm-ease-out)]"
        >
          {current.content}
        </div>
      </div>
    </Dialog>
  );
}
