// packages/angular/src/lib/tree-select/tree-select.ts
import { NgTemplateOutlet } from "@angular/common";
import {
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  ElementRef,
  inject,
  input,
  model,
  OnDestroy,
  signal,
  TemplateRef,
  untracked,
  viewChild,
  ViewContainerRef,
} from "@angular/core";
import { Overlay, OverlayRef } from "@angular/cdk/overlay";
import { TemplatePortal } from "@angular/cdk/portal";
import { cn } from "@bpdm/variants";
import { type FieldSize, FIELD_PANEL, FIELD_TRIGGER_BASE, FIELD_TRIGGER_SIZE } from "../internal/field";

export interface TreeNode {
  value: string;
  label: string;
  disabled?: boolean;
  children?: TreeNode[];
}

// a single visible (expanded) treeitem, in DOM order, for keyboard navigation
interface FlatRow {
  node: TreeNode;
  depth: number;
  hasChildren: boolean;
  isOpen: boolean;
  parentValue: string | null;
}

function leafValues(node: TreeNode): string[] {
  if (!node.children?.length) return node.disabled ? [] : [node.value];
  return node.children.flatMap(leafValues);
}

// keep nodes matching the query (full subtree) + ancestors of matches; collect
// ancestor values to force-expand so matches are visible.
function filterTree(nodes: TreeNode[], q: string): { nodes: TreeNode[]; expand: Set<string> } {
  const expand = new Set<string>();
  const rec = (list: TreeNode[]): TreeNode[] => {
    const out: TreeNode[] = [];
    for (const n of list) {
      if (n.label.toLowerCase().includes(q)) {
        out.push(n);
      } else if (n.children?.length) {
        const kids = rec(n.children);
        if (kids.length) {
          out.push({ ...n, children: kids });
          expand.add(n.value);
        }
      }
    }
    return out;
  };
  return { nodes: rec(nodes), expand };
}

/** Per-instance counter for a stable tree id (aria-controls). */
let treeUid = 0;

/**
 * `<bpdm-tree-select>` — hierarchical multi-select. Expand/collapse branches;
 * checking a parent selects all its (enabled) leaves, and a parent shows
 * indeterminate when only some leaves are selected. Selection is leaf-based —
 * `value` is the array of selected leaf values. Mirrors the React `TreeSelect`.
 */
@Component({
  selector: "bpdm-tree-select",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgTemplateOutlet],
  host: { class: "block" },
  template: `
    <div
      #trigger
      data-bpdm=""
      data-bpdm-slot="tree-select-trigger"
      role="combobox"
      aria-haspopup="tree"
      [attr.id]="id() || null"
      [attr.aria-expanded]="open()"
      [attr.aria-controls]="open() ? treeId : null"
      [attr.aria-label]="ariaLabel() || null"
      [attr.aria-describedby]="ariaDescribedby() || null"
      [attr.aria-invalid]="ariaInvalid() || null"
      [attr.aria-disabled]="disabled() || null"
      [attr.data-disabled]="disabled() ? '' : null"
      [tabindex]="disabled() ? -1 : 0"
      [class]="triggerClass()"
      (click)="!disabled() && toggleOpen()"
      (keydown)="onTriggerKeydown($event)"
    >
      <div class="flex min-w-0 flex-1 items-center gap-1 overflow-hidden">
        @if (selectedLeaves().length === 0) {
          <span class="text-muted-foreground">{{ placeholder() }}</span>
        } @else if (maxDisplay() === 0) {
          <span>{{ t().selected(selectedLeaves().length) }}</span>
        } @else {
          @for (o of chips(); track o.value) {
            <span data-bpdm-slot="tree-select-chip" class="inline-flex max-w-[140px] shrink-0 items-center gap-1 rounded-[calc(var(--radius)-4px)] bg-muted px-1.5 py-0.5 text-xs">
              <span class="truncate">{{ o.label }}</span>
            </span>
          }
          @if (extra() > 0) {
            <span class="shrink-0 text-xs text-muted-foreground">+{{ extra() }}</span>
          }
        }
      </div>
      <div class="flex shrink-0 items-center gap-1">
        @if (selectedLeaves().length > 0 && !disabled()) {
          <button type="button" data-bpdm-slot="tree-select-clear" [attr.aria-label]="t().clearAll" tabindex="-1" (pointerdown)="$event.stopPropagation()" (click)="$event.stopPropagation(); clearAll()" class="grid size-4 cursor-pointer place-items-center rounded-full text-muted-foreground hover:text-foreground">
            <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" class="size-3"><path d="M4 4l8 8M12 4l-8 8" stroke="currentColor" stroke-width="2" stroke-linecap="round" /></svg>
          </button>
        }
        <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" class="size-4 shrink-0 opacity-60 transition-transform duration-[var(--bpdm-duration-base)] ease-[var(--bpdm-ease-out)]" [class.rotate-180]="open()"><path d="M4 6l4 4 4-4" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" /></svg>
      </div>
    </div>

    <ng-template #panel>
      <div data-bpdm="" data-bpdm-slot="tree-select-content" [class]="panelClass()" [style.width.px]="panelWidth()" (keydown.escape)="close()">
        @if (searchable() || (selectAll() && visibleLeaves().length > 0)) {
          <div class="flex shrink-0 items-center gap-2 border-b border-border px-3">
            @if (selectAll() && visibleLeaves().length > 0) {
              <button type="button" data-bpdm-slot="tree-select-select-all" role="checkbox" [attr.aria-checked]="allSel() ? 'true' : someSel() ? 'mixed' : 'false'" (click)="toggleAll()" [attr.aria-label]="t().selectAll" [attr.title]="t().selectAll" [class]="searchable() ? 'flex shrink-0 cursor-pointer items-center gap-2 py-2 text-sm font-medium text-foreground' : 'flex w-full shrink-0 cursor-pointer items-center gap-2 py-2 text-sm font-medium text-foreground'">
                <span [class]="boxClass(allSel() || someSel())">
                  @if (allSel()) {
                    <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" class="size-3.5"><path d="M3.5 8.5l3 3 6-7" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round" /></svg>
                  } @else if (someSel()) {
                    <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" class="size-3.5"><path d="M4 8h8" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" /></svg>
                  }
                </span>
                @if (!searchable()) { {{ t().selectAll }} }
              </button>
              @if (searchable()) { <span class="w-px shrink-0 self-stretch bg-border" aria-hidden="true"></span> }
            }
            @if (searchable()) {
              <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" class="size-4 shrink-0 text-muted-foreground"><circle cx="7" cy="7" r="4.5" stroke="currentColor" stroke-width="1.6" /><path d="M11 11l3 3" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" /></svg>
              <input #search data-bpdm-slot="tree-select-search" [value]="query()" (input)="query.set($any($event.target).value)" [attr.placeholder]="searchPlaceholder()" [attr.aria-label]="searchPlaceholder()" class="h-9 w-full bg-transparent text-sm text-foreground placeholder:text-muted-foreground focus:outline-none" />
            }
          </div>
        }
        @if (visibleTree().length === 0) {
          <div data-bpdm-slot="tree-select-empty" class="px-3 py-6 text-center text-sm text-muted-foreground">{{ emptyText() }}</div>
        } @else {
          <div
            #tree
            data-bpdm-slot="tree-select-tree"
            role="tree"
            [attr.id]="treeId"
            [attr.aria-label]="ariaLabel() || placeholder()"
            aria-multiselectable="true"
            tabindex="0"
            [attr.aria-activedescendant]="activeDescId()"
            (keydown)="onTreeKeydown($event)"
            class="min-h-0 flex-1 overflow-auto p-1 focus:outline-none"
            [style.maxHeight.px]="maxHeight()"
          >
            @for (n of visibleTree(); track n.value; let i = $index) {
              <ng-container [ngTemplateOutlet]="nodeTpl" [ngTemplateOutletContext]="{ $implicit: n, depth: 0, pos: i + 1, size: visibleTree().length }" />
            }
          </div>
        }
      </div>
    </ng-template>

    <ng-template #nodeTpl let-n let-depth="depth" let-pos="pos" let-size="size">
      <div
        data-bpdm-slot="tree-select-item"
        [attr.id]="itemId(n.value)"
        role="treeitem"
        [attr.aria-level]="depth + 1"
        [attr.aria-setsize]="size"
        [attr.aria-posinset]="pos"
        [attr.aria-selected]="nodeChecked(n)"
        [attr.aria-checked]="nodeIndeterminate(n) ? 'mixed' : nodeChecked(n)"
        [attr.aria-expanded]="n.children?.length ? isExpanded(n) : null"
        [attr.aria-disabled]="n.disabled || null"
      >
        <div [class]="rowClass(n)" [style.paddingInlineStart.px]="8 + depth * 18" (mousemove)="activeValue.set(n.value)">
          @if (n.children?.length) {
            <button type="button" tabindex="-1" [attr.aria-label]="isExpanded(n) ? t().collapse : t().expand" (click)="toggleExpand(n.value)" class="grid size-4 shrink-0 cursor-pointer place-items-center text-muted-foreground hover:text-foreground">
              <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" class="size-3.5 transition-transform rtl:-scale-x-100" [class.rotate-90]="isExpanded(n)"><path d="M6 4l4 4-4 4" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" /></svg>
            </button>
          } @else {
            <span class="size-4 shrink-0"></span>
          }
          <button type="button" tabindex="-1" [disabled]="n.disabled || null" (click)="toggleNode(n)" class="flex min-w-0 flex-1 cursor-pointer items-center gap-2 text-start text-sm text-foreground disabled:pointer-events-none disabled:opacity-50">
            <span aria-hidden="true" [class]="boxClass(nodeChecked(n) || nodeIndeterminate(n))">
              @if (nodeChecked(n)) {
                <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" class="size-3.5"><path d="M3.5 8.5l3 3 6-7" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round" /></svg>
              } @else if (nodeIndeterminate(n)) {
                <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" class="size-3.5"><path d="M4 8h8" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" /></svg>
              }
            </span>
            <span class="truncate">{{ n.label }}</span>
          </button>
        </div>
        @if (n.children?.length && isExpanded(n)) {
          <div data-bpdm-slot="tree-select-group" role="group">
            @for (c of n.children; track c.value; let i = $index) {
              <ng-container [ngTemplateOutlet]="nodeTpl" [ngTemplateOutletContext]="{ $implicit: c, depth: depth + 1, pos: i + 1, size: n.children.length }" />
            }
          </div>
        }
      </div>
    </ng-template>
  `,
})
export class BpdmTreeSelect implements OnDestroy {
  private readonly overlay = inject(Overlay);
  private readonly vcr = inject(ViewContainerRef);

  readonly options = input<TreeNode[]>([]);
  readonly value = model<string[]>([]);
  readonly defaultValue = input<string[]>([]);
  readonly placeholder = input("Select…");
  /** Show a filter box at the top of the dropdown. */
  readonly searchable = input(false, { transform: booleanAttribute });
  readonly searchPlaceholder = input("Search…");
  readonly emptyText = input("No results.");
  /** Show a "Select all" row in the header. Default true. */
  readonly selectAll = input(true, { transform: booleanAttribute });
  readonly maxDisplay = input(3);
  /** Max height (px) of the scrollable list. */
  readonly maxHeight = input(280);
  readonly size = input<FieldSize>("md");
  readonly disabled = input(false, { transform: booleanAttribute });
  readonly ariaInvalid = input(false, { alias: "aria-invalid", transform: booleanAttribute });
  readonly classInput = input("", { alias: "class" });
  readonly id = input("");
  /** Accessible name for the trigger + tree — pass a translated string. */
  readonly ariaLabel = input("", { alias: "aria-label" });
  readonly ariaDescribedby = input("", { alias: "aria-describedby" });
  /** Screen-reader labels + count text — override for i18n. */
  readonly messages = input<{
    expand?: string;
    collapse?: string;
    selectAll?: string;
    clearAll?: string;
    selected?: (count: number) => string;
  }>({});

  protected readonly t = computed(() => ({
    expand: "Expand",
    collapse: "Collapse",
    selectAll: "Select all",
    clearAll: "Clear all",
    selected: (n: number) => `${n} selected`,
    ...this.messages(),
  }));
  protected readonly treeId = `bpdm-tree-${(treeUid += 1)}`;

  protected readonly open = signal(false);
  protected readonly query = signal("");
  private readonly expanded = signal<Set<string>>(new Set());
  protected readonly panelWidth = signal(0);
  /** value of the active (aria-activedescendant) treeitem. */
  protected readonly activeValue = signal<string | null>(null);

  private readonly triggerEl = viewChild.required<ElementRef<HTMLElement>>("trigger");
  private readonly panelTpl = viewChild.required<TemplateRef<unknown>>("panel");
  private readonly searchEl = viewChild<ElementRef<HTMLInputElement>>("search");
  private readonly treeEl = viewChild<ElementRef<HTMLElement>>("tree");
  private overlayRef?: OverlayRef;
  private seeded = false;

  constructor() {
    effect(() => {
      const dv = this.defaultValue();
      untracked(() => {
        if (!this.seeded) {
          this.seeded = true;
          if (dv.length) this.value.set([...dv]);
        }
      });
    });
  }

  private readonly q = computed(() => this.query().trim().toLowerCase());
  private readonly filtered = computed(() =>
    this.q() ? filterTree(this.options(), this.q()) : { nodes: this.options(), expand: null },
  );
  protected readonly visibleTree = computed(() => this.filtered().nodes);
  private readonly forceExpand = computed(() => this.filtered().expand);

  protected readonly selectedSet = computed(() => new Set(this.value()));
  private readonly leafLabel = computed(() => {
    const m = new Map<string, string>();
    const walk = (n: TreeNode) => {
      if (!n.children?.length) m.set(n.value, n.label);
      else n.children.forEach(walk);
    };
    this.options().forEach(walk);
    return m;
  });
  protected readonly selectedLeaves = computed(() => {
    const m = this.leafLabel();
    return this.value()
      .filter((v) => m.has(v))
      .map((v) => ({ value: v, label: m.get(v)! }));
  });
  protected readonly chips = computed(() =>
    this.maxDisplay() > 0 ? this.selectedLeaves().slice(0, this.maxDisplay()) : [],
  );
  protected readonly extra = computed(() => this.selectedLeaves().length - this.chips().length);

  protected readonly visibleLeaves = computed(() => this.visibleTree().flatMap(leafValues));
  protected readonly allSel = computed(() => {
    const l = this.visibleLeaves();
    return l.length > 0 && l.every((v) => this.selectedSet().has(v));
  });
  protected readonly someSel = computed(
    () => !this.allSel() && this.visibleLeaves().some((v) => this.selectedSet().has(v)),
  );

  // flatten the currently-visible (expanded) tree into DOM-order rows so the
  // arrow keys can walk exactly what the eye sees.
  protected readonly flatVisible = computed<FlatRow[]>(() => {
    const rows: FlatRow[] = [];
    const walk = (list: TreeNode[], depth: number, parentValue: string | null) => {
      for (const node of list) {
        const hasChildren = !!node.children?.length;
        const isOpen = this.isExpanded(node);
        rows.push({ node, depth, hasChildren, isOpen, parentValue });
        if (hasChildren && isOpen) walk(node.children!, depth + 1, node.value);
      }
    };
    walk(this.visibleTree(), 0, null);
    return rows;
  });
  protected itemId(value: string): string {
    return `${this.treeId}-ti-${value}`;
  }
  protected readonly activeDescId = computed(() => {
    const v = this.activeValue();
    return v && this.flatVisible().some((r) => r.node.value === v) ? this.itemId(v) : null;
  });

  protected readonly triggerClass = computed(() =>
    cn(FIELD_TRIGGER_BASE, FIELD_TRIGGER_SIZE[this.size()], "group", this.classInput()),
  );
  protected readonly panelClass = computed(() => FIELD_PANEL);

  protected boxClass(on: boolean): string {
    return cn(
      "grid size-4 shrink-0 place-items-center rounded-[4px] border",
      on ? "border-primary bg-primary text-primary-foreground" : "border-muted-foreground/50",
    );
  }

  protected rowClass(n: TreeNode): string {
    return cn(
      "flex items-center gap-1.5 rounded-[calc(var(--radius)-3px)] py-1.5 pe-2 transition-colors duration-[var(--bpdm-duration-fast)]",
      // active treeitem — follows both the keyboard (aria-activedescendant) and the
      // pointer (mousemove), so a single highlight tracks the cursor. An amber
      // inline-start bar (ring token, ≥3:1 in every theme) + soft tint + weight —
      // clearly perceptible where bg-muted alone was ~1.05:1. RTL-safe, jitter-free.
      this.activeValue() === n.value &&
        "bg-[var(--bpdm-option-active-bg)] font-medium shadow-[inset_2px_0_0_0_var(--bpdm-option-active-bar)] rtl:shadow-[inset_-2px_0_0_0_var(--bpdm-option-active-bar)]",
    );
  }

  protected nodeChecked(n: TreeNode): boolean {
    const leaves = leafValues(n);
    return leaves.length > 0 && leaves.every((v) => this.selectedSet().has(v));
  }
  protected nodeIndeterminate(n: TreeNode): boolean {
    const leaves = leafValues(n);
    const sel = leaves.filter((v) => this.selectedSet().has(v)).length;
    return sel > 0 && sel < leaves.length;
  }
  protected isExpanded(n: TreeNode): boolean {
    const force = this.forceExpand();
    if (force) return force.has(n.value) || this.expanded().has(n.value);
    return this.expanded().has(n.value);
  }

  protected toggleExpand(value: string): void {
    const next = new Set(this.expanded());
    if (next.has(value)) next.delete(value);
    else next.add(value);
    this.expanded.set(next);
  }

  protected toggleNode(n: TreeNode): void {
    const leaves = leafValues(n);
    if (!leaves.length) return;
    const allSel = leaves.every((v) => this.selectedSet().has(v));
    if (allSel) {
      const rm = new Set(leaves);
      this.value.set(this.value().filter((v) => !rm.has(v)));
    } else {
      this.value.set(Array.from(new Set([...this.value(), ...leaves])));
    }
  }

  protected toggleAll(): void {
    const l = this.visibleLeaves();
    if (this.allSel()) {
      const rm = new Set(l);
      this.value.set(this.value().filter((v) => !rm.has(v)));
    } else {
      this.value.set(Array.from(new Set([...this.value(), ...l])));
    }
  }

  protected clearAll(): void {
    this.value.set([]);
  }

  protected toggleOpen(): void {
    if (this.open()) this.close();
    else this.openPanel();
  }

  private openPanel(): void {
    if (this.disabled() || this.overlayRef) return;
    const trigger = this.triggerEl().nativeElement;
    this.panelWidth.set(trigger.offsetWidth);
    const positionStrategy = this.overlay
      .position()
      .flexibleConnectedTo(trigger)
      .withPositions([
        { originX: "start", originY: "bottom", overlayX: "start", overlayY: "top", offsetY: 4 },
        { originX: "start", originY: "top", overlayX: "start", overlayY: "bottom", offsetY: -4 },
      ])
      .withFlexibleDimensions(false)
      .withPush(false);
    this.overlayRef = this.overlay.create({
      positionStrategy,
      scrollStrategy: this.overlay.scrollStrategies.reposition(),
    });
    this.overlayRef.attach(new TemplatePortal(this.panelTpl(), this.vcr));
    this.open.set(true);
    this.activeValue.set(this.flatVisible()[0]?.node.value ?? null);
    this.overlayRef.outsidePointerEvents().subscribe((e) => {
      if (!trigger.contains(e.target as Node)) this.close();
    });
    // focus the search box (editable combobox) or the tree itself, so
    // aria-activedescendant is announced from the focused element and the
    // (non-searchable) tree is keyboard-reachable
    setTimeout(() => {
      const search = this.searchEl()?.nativeElement;
      if (search) search.focus();
      else this.treeEl()?.nativeElement.focus();
    });
  }

  protected close(): void {
    this.overlayRef?.dispose();
    this.overlayRef = undefined;
    this.open.set(false);
    this.query.set("");
    this.activeValue.set(null);
    this.triggerEl().nativeElement.focus();
  }

  protected onTriggerKeydown(e: KeyboardEvent): void {
    if (this.disabled()) return;
    if (!this.open() && (e.key === "Enter" || e.key === " " || e.key === "ArrowDown")) {
      e.preventDefault();
      this.openPanel();
    }
  }

  private moveActive(rows: FlatRow[], i: number): void {
    const r = rows[i];
    if (!r) return;
    this.activeValue.set(r.node.value);
    setTimeout(() => document.getElementById(this.itemId(r.node.value))?.scrollIntoView({ block: "nearest" }));
  }

  protected onTreeKeydown(e: KeyboardEvent): void {
    const rows = this.flatVisible();
    if (rows.length === 0) return;
    const rtl = getComputedStyle(e.currentTarget as HTMLElement).direction === "rtl";
    const forward = rtl ? "ArrowLeft" : "ArrowRight";
    const backward = rtl ? "ArrowRight" : "ArrowLeft";
    let idx = rows.findIndex((r) => r.node.value === this.activeValue());
    if (idx < 0) idx = 0;
    const cur = rows[idx];
    switch (e.key) {
      case "ArrowDown":
        e.preventDefault();
        this.moveActive(rows, Math.min(idx + 1, rows.length - 1));
        break;
      case "ArrowUp":
        e.preventDefault();
        this.moveActive(rows, Math.max(idx - 1, 0));
        break;
      case "Home":
        e.preventDefault();
        this.moveActive(rows, 0);
        break;
      case "End":
        e.preventDefault();
        this.moveActive(rows, rows.length - 1);
        break;
      case forward:
        e.preventDefault();
        if (cur?.hasChildren) {
          if (!cur.isOpen) this.toggleExpand(cur.node.value);
          else this.moveActive(rows, idx + 1); // first child is the next visible row
        }
        break;
      case backward:
        e.preventDefault();
        if (cur?.hasChildren && cur.isOpen) {
          this.toggleExpand(cur.node.value);
        } else if (cur?.parentValue) {
          const p = rows.findIndex((r) => r.node.value === cur.parentValue);
          if (p >= 0) this.moveActive(rows, p);
        }
        break;
      case "Enter":
      case " ":
        e.preventDefault();
        if (cur && !cur.node.disabled) this.toggleNode(cur.node);
        break;
      case "Escape":
        e.preventDefault();
        this.close();
        break;
      default:
        // type-ahead: jump to the next visible treeitem whose label starts with the key
        if (e.key.length === 1 && !e.ctrlKey && !e.metaKey && !e.altKey) {
          const ch = e.key.toLowerCase();
          for (let k = 1; k <= rows.length; k++) {
            const j = (idx + k) % rows.length;
            if (rows[j].node.label.toLowerCase().startsWith(ch)) {
              this.moveActive(rows, j);
              break;
            }
          }
        }
    }
  }

  ngOnDestroy(): void {
    this.overlayRef?.dispose();
  }
}

// packages/react/src/components/tree-select.tsx
import * as React from "react";
import * as PopoverPrimitive from "@radix-ui/react-popover";
import { type VariantProps } from "class-variance-authority";
import { cn } from "@/lib/utils";
import { FieldChevron, FieldCheck, FieldClearX, FieldDash, FieldSearch } from "./internal/field-icons";
import { fieldTriggerVariants as triggerVariants } from "./internal/field-trigger";

export type TreeNode = {
  value: string;
  label: string;
  icon?: React.ReactNode;
  disabled?: boolean;
  children?: TreeNode[];
};

// a single visible (expanded) treeitem, in DOM order, for keyboard navigation
type FlatRow = {
  node: TreeNode;
  depth: number;
  hasChildren: boolean;
  isOpen: boolean;
  parentValue: string | null;
  posinset: number;
  setsize: number;
};

function Caret({ open }: { open: boolean }) {
  return (
    <svg viewBox="0 0 16 16" fill="none" className={cn("size-3.5 transition-transform rtl:-scale-x-100", open && "rotate-90")} aria-hidden>
      <path d="M6 4l4 4-4 4" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}

function leafValues(node: TreeNode): string[] {
  if (!node.children?.length) return node.disabled ? [] : [node.value];
  return node.children.flatMap(leafValues);
}

// keep nodes matching the query (full subtree) + ancestors of matches; collect
// the ancestor values to force-expand so matches are visible.
function filterTree(
  nodes: TreeNode[],
  q: string,
): { nodes: TreeNode[]; expand: Set<string> } {
  const expand = new Set<string>();
  const rec = (list: TreeNode[]): TreeNode[] => {
    const out: TreeNode[] = [];
    for (const n of list) {
      if (n.label.toLowerCase().includes(q)) {
        out.push(n);
      } else if (n.children?.length) {
        const kids = rec(n.children);
        if (kids.length) {
          out.push({ ...n, children: kids });
          expand.add(n.value);
        }
      }
    }
    return out;
  };
  return { nodes: rec(nodes), expand };
}

export interface TreeSelectProps extends VariantProps<typeof triggerVariants> {
  options: TreeNode[];
  value?: string[];
  defaultValue?: string[];
  onValueChange?: (value: string[]) => void;
  placeholder?: string;
  searchable?: boolean;
  searchPlaceholder?: string;
  emptyText?: string;
  /** Show a "Select all" row in the header. Default true. */
  selectAll?: boolean;
  maxDisplay?: number;
  maxHeight?: number;
  disabled?: boolean;
  className?: string;
  contentClassName?: string;
  "aria-invalid"?: boolean;
  id?: string;
  /** Accessible name for the trigger + tree (when there's no visible `<label>`). */
  "aria-label"?: string;
  "aria-describedby"?: string;
  /** Screen-reader labels + count text — override for i18n. */
  messages?: {
    expand?: string;
    collapse?: string;
    selectAll?: string;
    clearAll?: string;
    selected?: (count: number) => string;
  };
}

const DEFAULT_MESSAGES = {
  expand: "Expand",
  collapse: "Collapse",
  selectAll: "Select all",
  clearAll: "Clear all",
  selected: (count: number) => `${count} selected`,
};

/**
 * Hierarchical multi-select. Expand/collapse branches; checking a parent selects
 * all its (enabled) leaves, and a parent shows indeterminate when only some leaves
 * are selected. Selection is leaf-based — `value` is the array of selected leaf
 * values. Controlled (`value` + `onValueChange`) or uncontrolled (`defaultValue`).
 */
export function TreeSelect({
  options,
  value,
  defaultValue,
  onValueChange,
  placeholder = "Select…",
  searchable = false,
  searchPlaceholder = "Search…",
  emptyText = "No results.",
  selectAll = true,
  maxDisplay = 3,
  maxHeight = 280,
  size,
  disabled,
  className,
  contentClassName,
  "aria-invalid": ariaInvalid,
  id,
  "aria-label": ariaLabel,
  "aria-describedby": ariaDescribedBy,
  messages,
}: TreeSelectProps) {
  const t = { ...DEFAULT_MESSAGES, ...messages };
  const treeId = React.useId();
  const [open, setOpen] = React.useState(false);
  const isControlled = value !== undefined;
  const [internal, setInternal] = React.useState<string[]>(defaultValue ?? []);
  const selected = React.useMemo(
    () => (isControlled ? (value ?? []) : internal),
    [isControlled, value, internal],
  );
  const selectedSet = React.useMemo(() => new Set(selected), [selected]);
  const [expanded, setExpanded] = React.useState<Set<string>>(new Set());
  const [query, setQuery] = React.useState("");
  const q = query.trim().toLowerCase();

  // portal into the nearest dialog (if any) so the dropdown stays interactive
  // inside a modal; outside a dialog this is null → defaults to <body>
  const triggerRef = React.useRef<HTMLDivElement>(null);
  const [portalContainer, setPortalContainer] = React.useState<HTMLElement | null>(null);
  React.useEffect(() => {
    setPortalContainer(triggerRef.current?.closest<HTMLElement>("[role='dialog']") ?? null);
  }, []);
  const { nodes: visibleTree, forceExpand } = React.useMemo(() => {
    if (!q) return { nodes: options, forceExpand: null as Set<string> | null };
    const r = filterTree(options, q);
    return { nodes: r.nodes, forceExpand: r.expand };
  }, [options, q]);

  // label lookup for leaves (for chips)
  const leafLabel = React.useMemo(() => {
    const m = new Map<string, { label: string; icon?: React.ReactNode }>();
    const walk = (n: TreeNode) => {
      if (!n.children?.length) m.set(n.value, { label: n.label, icon: n.icon });
      else n.children.forEach(walk);
    };
    options.forEach(walk);
    return m;
  }, [options]);

  const setSelected = (next: string[]) => {
    if (!isControlled) setInternal(next);
    onValueChange?.(next);
  };

  const toggleNode = (node: TreeNode) => {
    const leaves = leafValues(node);
    if (leaves.length === 0) return;
    const allSel = leaves.every((v) => selectedSet.has(v));
    if (allSel) {
      const remove = new Set(leaves);
      setSelected(selected.filter((v) => !remove.has(v)));
    } else {
      setSelected(Array.from(new Set([...selected, ...leaves])));
    }
  };

  const toggleExpand = (val: string) =>
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(val)) next.delete(val);
      else next.add(val);
      return next;
    });

  // ---- keyboard / focus model (WAI-ARIA tree, aria-activedescendant) --------
  const treeRef = React.useRef<HTMLDivElement>(null);
  const searchRef = React.useRef<HTMLInputElement>(null);
  const [activeValue, setActiveValue] = React.useState<string | null>(null);
  const itemId = (val: string) => `${treeId}-ti-${val}`;

  // flatten the currently-visible (expanded) tree into DOM-order rows so the
  // arrow keys can walk exactly what the eye sees.
  const flatVisible = React.useMemo(() => {
    const rows: FlatRow[] = [];
    const walk = (list: TreeNode[], depth: number, parentValue: string | null) => {
      list.forEach((node, i) => {
        const hasChildren = !!node.children?.length;
        const isOpen = forceExpand
          ? forceExpand.has(node.value) || expanded.has(node.value)
          : expanded.has(node.value);
        rows.push({ node, depth, hasChildren, isOpen, parentValue, posinset: i + 1, setsize: list.length });
        if (hasChildren && isOpen) walk(node.children!, depth + 1, node.value);
      });
    };
    walk(visibleTree, 0, null);
    return rows;
  }, [visibleTree, expanded, forceExpand]);

  // keep the active treeitem valid: seed the first row on open, drop it on close,
  // and re-seed if the active node scrolls out of view (e.g. a collapsed branch).
  React.useEffect(() => {
    if (!open) {
      setActiveValue(null);
      return;
    }
    setActiveValue((cur) =>
      cur && flatVisible.some((r) => r.node.value === cur) ? cur : (flatVisible[0]?.node.value ?? null),
    );
  }, [open, flatVisible]);

  const activeIndex = flatVisible.findIndex((r) => r.node.value === activeValue);
  const activeId = activeIndex >= 0 ? itemId(flatVisible[activeIndex].node.value) : undefined;

  const moveActive = (i: number) => {
    const r = flatVisible[i];
    if (!r) return;
    setActiveValue(r.node.value);
    requestAnimationFrame(() =>
      document.getElementById(itemId(r.node.value))?.scrollIntoView({ block: "nearest" }),
    );
  };

  const onTreeKeyDown = (e: React.KeyboardEvent<HTMLDivElement>) => {
    if (flatVisible.length === 0) return;
    const rtl = getComputedStyle(e.currentTarget).direction === "rtl";
    const forward = rtl ? "ArrowLeft" : "ArrowRight";
    const backward = rtl ? "ArrowRight" : "ArrowLeft";
    const idx = activeIndex < 0 ? 0 : activeIndex;
    const cur = flatVisible[idx];
    switch (e.key) {
      case "ArrowDown":
        e.preventDefault();
        moveActive(Math.min(idx + 1, flatVisible.length - 1));
        break;
      case "ArrowUp":
        e.preventDefault();
        moveActive(Math.max(idx - 1, 0));
        break;
      case "Home":
        e.preventDefault();
        moveActive(0);
        break;
      case "End":
        e.preventDefault();
        moveActive(flatVisible.length - 1);
        break;
      case forward:
        e.preventDefault();
        if (cur?.hasChildren) {
          if (!cur.isOpen) toggleExpand(cur.node.value);
          else moveActive(idx + 1); // first child is the next visible row
        }
        break;
      case backward:
        e.preventDefault();
        if (cur?.hasChildren && cur.isOpen) {
          toggleExpand(cur.node.value);
        } else if (cur?.parentValue) {
          const p = flatVisible.findIndex((r) => r.node.value === cur.parentValue);
          if (p >= 0) moveActive(p);
        }
        break;
      case "Enter":
      case " ":
        e.preventDefault();
        if (cur && !cur.node.disabled) toggleNode(cur.node);
        break;
      default: {
        // type-ahead: jump to the next visible treeitem whose label starts with the key
        if (e.key.length === 1 && !e.ctrlKey && !e.metaKey && !e.altKey) {
          const ch = e.key.toLowerCase();
          for (let k = 1; k <= flatVisible.length; k++) {
            const j = (idx + k) % flatVisible.length;
            if (flatVisible[j].node.label.toLowerCase().startsWith(ch)) {
              moveActive(j);
              break;
            }
          }
        }
      }
    }
  };

  // "Select all" operates on all leaves currently visible (after filtering)
  const allVisibleLeaves = React.useMemo(
    () => visibleTree.flatMap(leafValues),
    [visibleTree],
  );
  const allSel =
    allVisibleLeaves.length > 0 && allVisibleLeaves.every((v) => selectedSet.has(v));
  const someSel = !allSel && allVisibleLeaves.some((v) => selectedSet.has(v));
  const toggleAll = () => {
    if (allSel) {
      const rm = new Set(allVisibleLeaves);
      setSelected(selected.filter((v) => !rm.has(v)));
    } else {
      setSelected(Array.from(new Set([...selected, ...allVisibleLeaves])));
    }
  };

  const selectedLeaves = selected
    .map((v) => leafLabel.get(v))
    .filter(Boolean) as { label: string; icon?: React.ReactNode }[];
  const chips = maxDisplay > 0 ? selectedLeaves.slice(0, maxDisplay) : [];
  const extra = selectedLeaves.length - chips.length;

  const renderNode = (
    node: TreeNode,
    depth: number,
    posinset: number,
    setsize: number,
  ): React.ReactNode => {
    const hasChildren = !!node.children?.length;
    const leaves = leafValues(node);
    const selCount = leaves.filter((v) => selectedSet.has(v)).length;
    const checked = leaves.length > 0 && selCount === leaves.length;
    const indeterminate = selCount > 0 && !checked;
    const isOpen = forceExpand
      ? forceExpand.has(node.value) || expanded.has(node.value)
      : expanded.has(node.value);
    const isActive = activeValue === node.value;

    return (
      <div
        key={node.value}
        data-bpdm-slot="tree-select-item"
        id={itemId(node.value)}
        role="treeitem"
        aria-level={depth + 1}
        aria-setsize={setsize}
        aria-posinset={posinset}
        aria-selected={checked}
        aria-checked={indeterminate ? "mixed" : checked}
        aria-expanded={hasChildren ? isOpen : undefined}
        aria-disabled={node.disabled || undefined}
      >
        <div
          onMouseMove={() => setActiveValue(node.value)}
          className={cn(
            "flex items-center gap-1.5 rounded-[calc(var(--radius)-3px)] py-1.5 pe-2 transition-colors duration-[var(--bpdm-duration-fast)]",
            // active treeitem — follows both the keyboard (aria-activedescendant) and
            // the pointer (onMouseMove), so there's a single highlight that tracks the
            // cursor. An amber inline-start bar (ring token, ≥3:1 in every theme) + soft
            // tint + weight — clearly perceptible where bg-muted alone was ~1.05:1.
            // RTL-safe (logical shadow mirror), jitter-free (inset shadow takes no space).
            isActive &&
              "bg-[var(--bpdm-option-active-bg)] font-medium shadow-[inset_2px_0_0_0_var(--bpdm-option-active-bar)] rtl:shadow-[inset_-2px_0_0_0_var(--bpdm-option-active-bar)]",
          )}
          style={{ paddingInlineStart: 8 + depth * 18 }}
        >
          {hasChildren ? (
            <button
              type="button"
              tabIndex={-1}
              aria-label={isOpen ? t.collapse : t.expand}
              onClick={() => toggleExpand(node.value)}
              className="grid size-4 shrink-0 cursor-pointer place-items-center text-muted-foreground hover:text-foreground"
            >
              <Caret open={isOpen} />
            </button>
          ) : (
            <span className="size-4 shrink-0" />
          )}

          <button
            type="button"
            tabIndex={-1}
            disabled={node.disabled}
            onClick={() => toggleNode(node)}
            className="flex min-w-0 flex-1 cursor-pointer items-center gap-2 text-start text-sm text-foreground disabled:pointer-events-none disabled:opacity-50"
          >
            <span
              aria-hidden="true"
              className={cn(
                "grid size-4 shrink-0 place-items-center rounded-[4px] border",
                checked || indeterminate
                  ? "border-primary bg-primary text-primary-foreground"
                  : "border-muted-foreground/50",
              )}
            >
              {checked ? <FieldCheck /> : indeterminate ? <FieldDash /> : null}
            </span>
            {node.icon}
            <span className="truncate">{node.label}</span>
          </button>
        </div>
        {hasChildren && isOpen && (
          <div data-bpdm-slot="tree-select-group" role="group">
            {node.children!.map((c, i) => renderNode(c, depth + 1, i + 1, node.children!.length))}
          </div>
        )}
      </div>
    );
  };

  return (
    <PopoverPrimitive.Root open={open} onOpenChange={setOpen}>
      <PopoverPrimitive.Trigger asChild>
        <div
          ref={triggerRef}
          id={id}
          role="combobox"
          aria-haspopup="tree"
          aria-expanded={open}
          aria-controls={open ? treeId : undefined}
          aria-label={ariaLabel}
          aria-describedby={ariaDescribedBy}
          aria-invalid={ariaInvalid}
          aria-disabled={disabled}
          data-disabled={disabled ? "" : undefined}
          tabIndex={disabled ? -1 : 0}
          onKeyDown={(e) => {
            if (!disabled && (e.key === "Enter" || e.key === " ")) {
              e.preventDefault();
              setOpen((o) => !o);
            }
          }}
          data-bpdm="" data-bpdm-slot="tree-select-trigger"
          className={cn(triggerVariants({ size }), "group", className)}
        >
          <div className="flex min-w-0 flex-1 items-center gap-1 overflow-hidden">
            {selectedLeaves.length === 0 ? (
              <span className="text-muted-foreground">{placeholder}</span>
            ) : maxDisplay === 0 ? (
              <span>{t.selected(selectedLeaves.length)}</span>
            ) : (
              <>
                {chips.map((o, i) => (
                  <span
                    key={i}
                    data-bpdm-slot="tree-select-chip"
                    className="inline-flex max-w-[140px] shrink-0 items-center gap-1 rounded-[calc(var(--radius)-4px)] bg-muted px-1.5 py-0.5 text-xs"
                  >
                    <span className="truncate">{o.label}</span>
                  </span>
                ))}
                {extra > 0 && <span className="shrink-0 text-xs text-muted-foreground">+{extra}</span>}
              </>
            )}
          </div>
          <div className="flex shrink-0 items-center gap-1">
            {selectedLeaves.length > 0 && !disabled && (
              <button
                type="button"
                aria-label={t.clearAll}
                tabIndex={-1}
                onPointerDown={(e) => e.stopPropagation()}
                onClick={(e) => {
                  e.stopPropagation();
                  setSelected([]);
                }}
                data-bpdm-slot="tree-select-clear"
                className="grid size-4 cursor-pointer place-items-center rounded-full text-muted-foreground hover:text-foreground"
              >
                <FieldClearX />
              </button>
            )}
            <FieldChevron />
          </div>
        </div>
      </PopoverPrimitive.Trigger>

      <PopoverPrimitive.Portal container={portalContainer ?? undefined}>
        <PopoverPrimitive.Content
          align="start"
          sideOffset={4}
          collisionPadding={8}
          onOpenAutoFocus={(e) => {
            // focus the search box (editable combobox) or the tree itself, so
            // aria-activedescendant is announced from the focused element
            e.preventDefault();
            (searchable ? searchRef.current : treeRef.current)?.focus();
          }}
          style={{ maxHeight: "var(--radix-popover-content-available-height)" }}
          data-bpdm="" data-bpdm-slot="tree-select-content"
          className={cn(
            "z-50 flex w-[var(--radix-popover-trigger-width)] flex-col overflow-hidden rounded-[var(--radius)] border border-border bg-popover text-popover-foreground shadow-md",
            "origin-[var(--radix-popover-content-transform-origin)] data-[state=open]:animate-[bpdm-pop-in_var(--bpdm-duration-fast)_var(--bpdm-ease-out)] data-[state=closed]:animate-[bpdm-pop-out_var(--bpdm-duration-fast)_ease-in]",
            contentClassName,
          )}
        >
          {(searchable || (selectAll && allVisibleLeaves.length > 0)) && (
            <div className="flex shrink-0 items-center gap-2 border-b border-border px-3">
              {selectAll && allVisibleLeaves.length > 0 && (
                <button
                  type="button"
                  role="checkbox"
                  aria-checked={allSel ? true : someSel ? "mixed" : false}
                  onClick={toggleAll}
                  aria-label={t.selectAll}
                  title={t.selectAll}
                  data-bpdm-slot="tree-select-select-all"
                  className={cn(
                    "flex shrink-0 cursor-pointer items-center gap-2 py-2 text-sm font-medium text-foreground",
                    !searchable && "w-full",
                  )}
                >
                  <span
                    className={cn(
                      "grid size-4 shrink-0 place-items-center rounded-[4px] border",
                      allSel || someSel
                        ? "border-primary bg-primary text-primary-foreground"
                        : "border-muted-foreground/50",
                    )}
                  >
                    {allSel ? <FieldCheck /> : someSel ? <FieldDash /> : null}
                  </span>
                  {!searchable && t.selectAll}
                </button>
              )}
              {selectAll && allVisibleLeaves.length > 0 && searchable && (
                <span className="w-px shrink-0 self-stretch bg-border" aria-hidden />
              )}
              {searchable && (
                <>
                  <FieldSearch />
                  <input
                    ref={searchRef}
                    value={query}
                    onChange={(e) => setQuery(e.target.value)}
                    placeholder={searchPlaceholder}
                    aria-label={searchPlaceholder}
                    data-bpdm-slot="tree-select-search"
                    className="h-9 w-full bg-transparent text-sm text-foreground placeholder:text-muted-foreground focus:outline-none"
                  />
                </>
              )}
            </div>
          )}
          {visibleTree.length === 0 ? (
            <div data-bpdm-slot="tree-select-empty" className="px-3 py-6 text-center text-sm text-muted-foreground">{emptyText}</div>
          ) : (
            <div
              ref={treeRef}
              role="tree"
              id={treeId}
              aria-label={ariaLabel ?? placeholder}
              aria-multiselectable="true"
              tabIndex={0}
              aria-activedescendant={activeId}
              onKeyDown={onTreeKeyDown}
              style={{ maxHeight }}
              data-bpdm-slot="tree-select-tree"
              className="min-h-0 flex-1 overflow-auto p-1 focus:outline-none"
            >
              {visibleTree.map((n, i) => renderNode(n, 0, i + 1, visibleTree.length))}
            </div>
          )}
        </PopoverPrimitive.Content>
      </PopoverPrimitive.Portal>
    </PopoverPrimitive.Root>
  );
}
