// packages/react/src/components/multi-select.tsx
import * as React from "react";
import * as PopoverPrimitive from "@radix-ui/react-popover";
import { useVirtualizer } from "@tanstack/react-virtual";
import { type VariantProps } from "class-variance-authority";
import { cn } from "@/lib/utils";
import { FieldChevron, FieldCheck, FieldClearX, FieldDash, FieldSearch } from "./internal/field-icons";
import { fieldTriggerVariants as triggerVariants } from "./internal/field-trigger";
import type { SelectItems, SelectOption, SelectOptionGroup } from "./select";

const isGroup = (x: SelectOption | SelectOptionGroup): x is SelectOptionGroup =>
  Array.isArray((x as SelectOptionGroup).options);

type Row =
  | { kind: "group"; label: string; icon?: React.ReactNode }
  | { kind: "item"; option: SelectOption };

const ITEM_H = 36;
const GROUP_H = 30;


export interface MultiSelectProps extends VariantProps<typeof triggerVariants> {
  options: SelectItems;
  value?: string[];
  defaultValue?: string[];
  onValueChange?: (value: string[]) => void;
  placeholder?: string;
  searchable?: boolean;
  searchPlaceholder?: string;
  emptyText?: string;
  /** Max selected chips shown before "+N". 0 → show "N selected" count. Default 3. */
  maxDisplay?: number;
  /** Show a "Select all" row at the top of the dropdown. Default true. */
  selectAll?: boolean;
  maxHeight?: number;
  disabled?: boolean;
  className?: string;
  contentClassName?: string;
  "aria-invalid"?: boolean;
  id?: string;
  /** Accessible name for the trigger + option list (when there's no visible `<label>`). */
  "aria-label"?: string;
  "aria-describedby"?: string;
  /** Screen-reader labels + count text — override for i18n. */
  messages?: {
    selectAll?: string;
    clearAll?: string;
    remove?: (label: string) => string;
    selected?: (count: number) => string;
  };
}

const DEFAULT_MESSAGES = {
  selectAll: "Select all",
  clearAll: "Clear all",
  remove: (label: string) => `Remove ${label}`,
  selected: (count: number) => `${count} selected`,
};

/**
 * Searchable, virtualized multi-select (Select's bigger sibling). Same options
 * (flat or grouped), always virtualized for large lists. The trigger shows up to
 * `maxDisplay` chips then "+N", or a count when `maxDisplay={0}`.
 */
export function MultiSelect({
  options,
  value,
  defaultValue,
  onValueChange,
  placeholder = "Select…",
  searchable = false,
  searchPlaceholder = "Search…",
  emptyText = "No results.",
  maxDisplay = 3,
  selectAll = true,
  maxHeight = 256,
  size,
  disabled,
  className,
  contentClassName,
  "aria-invalid": ariaInvalid,
  id,
  "aria-label": ariaLabel,
  "aria-describedby": ariaDescribedBy,
  messages,
}: MultiSelectProps) {
  const t = { ...DEFAULT_MESSAGES, ...messages };
  const baseId = React.useId();
  const listboxId = `${baseId}-listbox`;
  const optionId = (index: number) => `${baseId}-opt-${index}`;
  const searchRef = React.useRef<HTMLInputElement>(null);
  const listRef = React.useRef<HTMLDivElement | null>(null);
  const [open, setOpen] = React.useState(false);
  const isControlled = value !== undefined;
  const [internal, setInternal] = React.useState<string[]>(defaultValue ?? []);
  const selected = React.useMemo(
    () => (isControlled ? (value ?? []) : internal),
    [isControlled, value, internal],
  );
  const selectedSet = React.useMemo(() => new Set(selected), [selected]);
  const [query, setQuery] = React.useState("");
  const [active, setActive] = React.useState(0);
  const [listEl, setListEl] = React.useState<HTMLDivElement | null>(null);

  // portal into the nearest dialog (if any) so the dropdown stays interactive
  // inside a modal; outside a dialog this is null → defaults to <body>
  const triggerRef = React.useRef<HTMLDivElement>(null);
  const [portalContainer, setPortalContainer] = React.useState<HTMLElement | null>(null);
  React.useEffect(() => {
    setPortalContainer(triggerRef.current?.closest<HTMLElement>("[role='dialog']") ?? null);
  }, []);

  const allRows = React.useMemo<Row[]>(() => {
    const rows: Row[] = [];
    for (const entry of options) {
      if (isGroup(entry)) {
        rows.push({ kind: "group", label: entry.label, icon: entry.icon });
        for (const o of entry.options) rows.push({ kind: "item", option: o });
      } else {
        rows.push({ kind: "item", option: entry });
      }
    }
    return rows;
  }, [options]);

  const rows = React.useMemo<Row[]>(() => {
    const q = query.trim().toLowerCase();
    if (!q) return allRows;
    const out: Row[] = [];
    let pending: Row | null = null;
    let used = false;
    for (const r of allRows) {
      if (r.kind === "group") {
        pending = r;
        used = false;
      } else if (r.option.label.toLowerCase().includes(q)) {
        if (pending && !used) {
          out.push(pending);
          used = true;
        }
        out.push(r);
      }
    }
    return out;
  }, [allRows, query]);

  // flat list of all options for resolving selected labels
  const optionByValue = React.useMemo(() => {
    const m = new Map<string, SelectOption>();
    for (const r of allRows) if (r.kind === "item") m.set(r.option.value, r.option);
    return m;
  }, [allRows]);
  const selectedOptions = selected
    .map((v) => optionByValue.get(v))
    .filter(Boolean) as SelectOption[];

  const firstItem = React.useMemo(() => rows.findIndex((r) => r.kind === "item"), [rows]);
  const virtualizer = useVirtualizer({
    count: rows.length,
    getScrollElement: () => listEl,
    estimateSize: (i) => (rows[i]?.kind === "group" ? GROUP_H : ITEM_H),
    overscan: 12,
  });

  // Reset the active option ONLY when the menu opens or the filter changes — not
  // on every `rows` identity change. Inline `options` props re-create the array
  // each render, so keying off `rows` would snap the highlight + scroll back to
  // the top on every selection (the click appears to "jump" to the first item).
  React.useEffect(() => {
    setActive(firstItem === -1 ? 0 : firstItem);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, query]);
  React.useEffect(() => {
    if (open && rows.length) virtualizer.scrollToIndex(active);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [active, open]);

  const setSelected = (next: string[]) => {
    if (!isControlled) setInternal(next);
    onValueChange?.(next);
  };
  const toggle = (val: string) =>
    setSelected(selectedSet.has(val) ? selected.filter((v) => v !== val) : [...selected, val]);
  const clearAll = () => setSelected([]);

  // "Select all" operates on the currently visible (filtered) items
  const filteredItemValues = React.useMemo(() => {
    const vals: string[] = [];
    for (const r of rows) if (r.kind === "item" && !r.option.disabled) vals.push(r.option.value);
    return vals;
  }, [rows]);
  const allSel =
    filteredItemValues.length > 0 && filteredItemValues.every((v) => selectedSet.has(v));
  const someSel = !allSel && filteredItemValues.some((v) => selectedSet.has(v));
  const toggleAll = () =>
    allSel
      ? setSelected(selected.filter((v) => !filteredItemValues.includes(v)))
      : setSelected(Array.from(new Set([...selected, ...filteredItemValues])));

  const move = (dir: 1 | -1) =>
    setActive((cur) => {
      let i = cur;
      do {
        i += dir;
      } while (i >= 0 && i < rows.length && rows[i].kind === "group");
      return i < 0 || i >= rows.length ? cur : i;
    });

  const onKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "ArrowDown") {
      e.preventDefault();
      move(1);
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      move(-1);
    } else if (e.key === "Enter") {
      e.preventDefault();
      const r = rows[active];
      if (r?.kind === "item" && !r.option.disabled) toggle(r.option.value);
    }
  };

  const chips = maxDisplay > 0 ? selectedOptions.slice(0, maxDisplay) : [];
  const extra = selectedOptions.length - chips.length;

  // id of the highlighted option, exposed via aria-activedescendant
  const activeId = rows[active]?.kind === "item" ? optionId(active) : undefined;

  return (
    <PopoverPrimitive.Root open={open} onOpenChange={setOpen}>
      <PopoverPrimitive.Trigger asChild>
        <div
          ref={triggerRef}
          id={id}
          role="combobox"
          aria-haspopup="listbox"
          aria-expanded={open}
          aria-controls={open ? listboxId : undefined}
          aria-label={ariaLabel}
          aria-describedby={ariaDescribedBy}
          aria-invalid={ariaInvalid}
          aria-disabled={disabled}
          data-disabled={disabled ? "" : undefined}
          tabIndex={disabled ? -1 : 0}
          onKeyDown={(e) => {
            if (disabled) return;
            if (e.key === "Enter" || e.key === " ") {
              e.preventDefault();
              setOpen((o) => !o);
            } else if ((e.key === "Backspace" || e.key === "Delete") && selected.length > 0) {
              // remove the last selected chip straight from the (focused) trigger
              e.preventDefault();
              setSelected(selected.slice(0, -1));
            }
          }}
          data-bpdm="" data-bpdm-slot="multi-select-trigger"
          className={cn(triggerVariants({ size }), "group", className)}
        >
          <div className="flex min-w-0 flex-1 items-center gap-1 overflow-hidden">
            {selected.length === 0 ? (
              <span className="text-muted-foreground">{placeholder}</span>
            ) : maxDisplay === 0 ? (
              <span>{t.selected(selected.length)}</span>
            ) : (
              <>
                {chips.map((o) => (
                  <span
                    key={o.value}
                    data-bpdm-slot="multi-select-chip"
                    className="inline-flex max-w-[140px] shrink-0 items-center gap-1 rounded-[calc(var(--radius)-4px)] bg-muted px-1.5 py-0.5 text-xs"
                  >
                    <span className="truncate">{o.label}</span>
                    <button
                      type="button"
                      aria-label={t.remove(o.label)}
                      onPointerDown={(e) => e.stopPropagation()}
                      // keep Enter/Space/Backspace on the chip's own button — don't
                      // bubble to the trigger (which would toggle the panel / clear)
                      onKeyDown={(e) => e.stopPropagation()}
                      onClick={(e) => {
                        e.stopPropagation();
                        toggle(o.value);
                      }}
                      className="grid cursor-pointer place-items-center rounded-full text-muted-foreground hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                    >
                      <FieldClearX />
                    </button>
                  </span>
                ))}
                {extra > 0 && (
                  <span className="shrink-0 text-xs text-muted-foreground">+{extra}</span>
                )}
              </>
            )}
          </div>

          <div className="flex shrink-0 items-center gap-1">
            {selected.length > 0 && !disabled && (
              <button
                type="button"
                aria-label={t.clearAll}
                onPointerDown={(e) => e.stopPropagation()}
                // keyboard-reachable (native button): Enter/Space activate it; stop
                // the key from bubbling to the trigger's open/backspace handler
                onKeyDown={(e) => e.stopPropagation()}
                onClick={(e) => {
                  e.stopPropagation();
                  clearAll();
                }}
                data-bpdm-slot="multi-select-clear"
                className="grid size-4 cursor-pointer place-items-center rounded-full text-muted-foreground hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
              >
                <FieldClearX />
              </button>
            )}
            <FieldChevron />
          </div>
        </div>
      </PopoverPrimitive.Trigger>

      <PopoverPrimitive.Portal container={portalContainer ?? undefined}>
        <PopoverPrimitive.Content
          align="start"
          sideOffset={4}
          collisionPadding={8}
          onKeyDown={onKeyDown}
          onOpenAutoFocus={(e) => {
            e.preventDefault();
            (searchable ? searchRef.current : listRef.current)?.focus();
          }}
          style={{ maxHeight: "var(--radix-popover-content-available-height)" }}
          data-bpdm="" data-bpdm-slot="multi-select-content"
          className={cn(
            "z-50 flex w-[var(--radix-popover-trigger-width)] flex-col overflow-hidden rounded-[var(--radius)] border border-border bg-popover text-popover-foreground shadow-md",
            "origin-[var(--radix-popover-content-transform-origin)] data-[state=open]:animate-[bpdm-pop-in_var(--bpdm-duration-fast)_var(--bpdm-ease-out)] data-[state=closed]:animate-[bpdm-pop-out_var(--bpdm-duration-fast)_ease-in]",
            contentClassName,
          )}
        >
          {(searchable || (selectAll && filteredItemValues.length > 0)) && (
            <div className="flex shrink-0 items-center gap-2 border-b border-border px-3">
              {selectAll && filteredItemValues.length > 0 && (
                <button
                  type="button"
                  role="checkbox"
                  aria-checked={allSel ? true : someSel ? "mixed" : false}
                  onClick={toggleAll}
                  aria-label={t.selectAll}
                  title={t.selectAll}
                  data-bpdm-slot="multi-select-select-all"
                  className={cn(
                    "flex shrink-0 cursor-pointer items-center gap-2 py-2 text-sm font-medium text-foreground",
                    !searchable && "w-full",
                  )}
                >
                  <span
                    className={cn(
                      "grid size-4 shrink-0 place-items-center rounded-[4px] border",
                      allSel || someSel
                        ? "border-primary bg-primary text-primary-foreground"
                        : "border-muted-foreground",
                    )}
                  >
                    {allSel ? <FieldCheck /> : someSel ? <FieldDash /> : null}
                  </span>
                  {!searchable && t.selectAll}
                </button>
              )}
              {selectAll && filteredItemValues.length > 0 && searchable && (
                <span className="w-px shrink-0 self-stretch bg-border" aria-hidden />
              )}
              {searchable && (
                <>
                  <FieldSearch />
                  <input
                    ref={searchRef}
                    value={query}
                    onChange={(e) => setQuery(e.target.value)}
                    placeholder={searchPlaceholder}
                    aria-label={searchPlaceholder}
                    role="combobox"
                    aria-expanded
                    aria-controls={listboxId}
                    aria-autocomplete="list"
                    aria-activedescendant={activeId}
                    data-bpdm-slot="multi-select-search"
                    className="h-9 w-full bg-transparent text-sm text-foreground placeholder:text-muted-foreground focus:outline-none"
                  />
                </>
              )}
            </div>
          )}

          {rows.length === 0 ? (
            <div data-bpdm-slot="multi-select-empty" className="px-3 py-6 text-center text-sm text-muted-foreground">{emptyText}</div>
          ) : (
            <div
              ref={(el) => {
                listRef.current = el;
                setListEl(el);
              }}
              id={listboxId}
              role="listbox"
              aria-multiselectable
              aria-label={ariaLabel ?? placeholder}
              tabIndex={-1}
              aria-activedescendant={searchable ? undefined : activeId}
              style={{ maxHeight }}
              data-bpdm-slot="multi-select-list"
              className="min-h-0 flex-1 overflow-auto p-1 focus:outline-none"
            >
              <div style={{ height: virtualizer.getTotalSize(), position: "relative" }}>
                {virtualizer.getVirtualItems().map((vi) => {
                  const r = rows[vi.index];
                  const common = {
                    style: { height: vi.size, transform: `translateY(${vi.start}px)` } as React.CSSProperties,
                  };
                  if (r.kind === "group") {
                    return (
                      <div
                        key={`g-${vi.index}`}
                        aria-hidden="true"
                        data-bpdm-slot="multi-select-group"
                        className="absolute start-0 top-0 flex w-full items-center gap-2 px-2 text-sm font-semibold text-foreground [&_img]:size-4 [&_svg]:size-4"
                        {...common}
                      >
                        {r.icon}
                        {r.label}
                      </div>
                    );
                  }
                  const o = r.option;
                  const isSelected = selectedSet.has(o.value);
                  const isActive = vi.index === active;
                  return (
                    <button
                      key={o.value}
                      id={optionId(vi.index)}
                      type="button"
                      role="option"
                      aria-selected={isSelected}
                      disabled={o.disabled}
                      onClick={() => !o.disabled && toggle(o.value)}
                      onMouseMove={() => setActive(vi.index)}
                      data-bpdm-slot="multi-select-option"
                      className={cn(
                        "absolute start-0 top-0 flex w-full cursor-pointer items-center gap-2 rounded-[calc(var(--radius)-3px)] px-2 text-start text-sm text-foreground transition-colors duration-[var(--bpdm-duration-fast)] disabled:pointer-events-none disabled:opacity-50",
                        // keyboard-active / hovered row: an amber inline-start bar (ring
                        // token, ≥3:1 in every theme) + soft tint + weight — clearly
                        // perceptible where bg-muted alone was ~1.05:1. RTL-safe (logical
                        // shadow mirror), jitter-free (inset shadow takes no layout space).
                        isActive &&
                          "bg-[var(--bpdm-option-active-bg)] font-medium shadow-[inset_2px_0_0_0_var(--bpdm-option-active-bar)] rtl:shadow-[inset_-2px_0_0_0_var(--bpdm-option-active-bar)]",
                      )}
                      {...common}
                    >
                      <span
                        className={cn(
                          "grid size-4 shrink-0 place-items-center rounded-[4px] border transition-colors duration-[var(--bpdm-duration-fast)]",
                          isSelected
                            ? "border-primary bg-primary text-primary-foreground"
                            : "border-muted-foreground",
                        )}
                      >
                        {isSelected && <FieldCheck className="animate-[bpdm-indicator-in_var(--bpdm-duration-base)_var(--bpdm-ease-overshoot)]" />}
                      </span>
                      {o.icon}
                      <span className="truncate">{o.label}</span>
                    </button>
                  );
                })}
              </div>
            </div>
          )}
        </PopoverPrimitive.Content>
      </PopoverPrimitive.Portal>
    </PopoverPrimitive.Root>
  );
}

// packages/angular/src/lib/multi-select/multi-select.ts
import {
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  ElementRef,
  inject,
  input,
  model,
  OnDestroy,
  signal,
  TemplateRef,
  untracked,
  viewChild,
  ViewContainerRef,
} from "@angular/core";
import {
  CdkFixedSizeVirtualScroll,
  CdkVirtualForOf,
  CdkVirtualScrollViewport,
} from "@angular/cdk/scrolling";
import { Overlay, OverlayRef } from "@angular/cdk/overlay";
import { TemplatePortal } from "@angular/cdk/portal";
import { cn } from "@bpdm/variants";
import { type FieldSize, FIELD_PANEL, FIELD_TRIGGER_BASE, FIELD_TRIGGER_SIZE } from "../internal/field";
import {
  filterSelectRows,
  flattenSelectRows,
  type SelectItems,
  type SelectOption,
} from "../select/select";

const ROW_H = 36;

/** Per-instance counter for stable listbox/option ids (aria-activedescendant). */
let multiUid = 0;

/**
 * `<bpdm-multi-select>` — searchable, virtualized multi-select (Select's bigger
 * sibling). Same `options` (flat or grouped), always virtualized. The trigger
 * shows up to `maxDisplay` chips then "+N", or a count when `maxDisplay=0`.
 * Mirrors the React `MultiSelect`.
 */
@Component({
  selector: "bpdm-multi-select",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CdkVirtualScrollViewport, CdkFixedSizeVirtualScroll, CdkVirtualForOf],
  host: { class: "block" },
  template: `
    <div
      #trigger
      data-bpdm=""
      data-bpdm-slot="multi-select-trigger"
      role="combobox"
      aria-haspopup="listbox"
      [attr.id]="id() || null"
      [attr.aria-expanded]="open()"
      [attr.aria-controls]="open() ? listboxId : null"
      [attr.aria-label]="ariaLabel() || null"
      [attr.aria-describedby]="ariaDescribedby() || null"
      [attr.aria-invalid]="ariaInvalid() || null"
      [attr.aria-disabled]="disabled() || null"
      [attr.data-disabled]="disabled() ? '' : null"
      [tabindex]="disabled() ? -1 : 0"
      [class]="triggerClass()"
      (click)="!disabled() && toggle()"
      (keydown)="onTriggerKeydown($event)"
    >
      <div class="flex min-w-0 flex-1 items-center gap-1 overflow-hidden">
        @if (selected().length === 0) {
          <span class="text-muted-foreground">{{ placeholder() }}</span>
        } @else if (maxDisplay() === 0) {
          <span>{{ t().selected(selected().length) }}</span>
        } @else {
          @for (o of chips(); track o.value) {
            <span data-bpdm-slot="multi-select-chip" class="inline-flex max-w-[140px] shrink-0 items-center gap-1 rounded-[calc(var(--radius)-4px)] bg-muted px-1.5 py-0.5 text-xs">
              <span class="truncate">{{ o.label }}</span>
              <button type="button" [attr.aria-label]="t().remove(o.label)" (pointerdown)="$event.stopPropagation()" (keydown)="$event.stopPropagation()" (click)="$event.stopPropagation(); toggle(o.value)" class="grid cursor-pointer place-items-center rounded-full text-muted-foreground hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">
                <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" class="size-3"><path d="M4 4l8 8M12 4l-8 8" stroke="currentColor" stroke-width="2" stroke-linecap="round" /></svg>
              </button>
            </span>
          }
          @if (extra() > 0) {
            <span class="shrink-0 text-xs text-muted-foreground">+{{ extra() }}</span>
          }
        }
      </div>
      <div class="flex shrink-0 items-center gap-1">
        @if (selected().length > 0 && !disabled()) {
          <button type="button" data-bpdm-slot="multi-select-clear" [attr.aria-label]="t().clearAll" (pointerdown)="$event.stopPropagation()" (keydown)="$event.stopPropagation()" (click)="$event.stopPropagation(); clearAll()" class="grid size-4 cursor-pointer place-items-center rounded-full text-muted-foreground hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">
            <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" class="size-3"><path d="M4 4l8 8M12 4l-8 8" stroke="currentColor" stroke-width="2" stroke-linecap="round" /></svg>
          </button>
        }
        <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" class="size-4 shrink-0 opacity-60 transition-transform duration-[var(--bpdm-duration-base)] ease-[var(--bpdm-ease-out)]" [class.rotate-180]="open()"><path d="M4 6l4 4 4-4" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" /></svg>
      </div>
    </div>

    <ng-template #panel>
      <div #panelRoot data-bpdm="" data-bpdm-slot="multi-select-content" tabindex="-1" [class]="panelClass()" [style.width.px]="panelWidth()" (keydown)="onKeydown($event)">
        @if (searchable() || (selectAll() && filteredValues().length > 0)) {
          <div class="flex shrink-0 items-center gap-2 border-b border-border px-3">
            @if (selectAll() && filteredValues().length > 0) {
              <button type="button" data-bpdm-slot="multi-select-select-all" role="checkbox" [attr.aria-checked]="allSel() ? 'true' : someSel() ? 'mixed' : 'false'" (click)="toggleAll()" [attr.aria-label]="t().selectAll" [attr.title]="t().selectAll" [class]="searchable() ? 'flex shrink-0 cursor-pointer items-center gap-2 py-2 text-sm font-medium text-foreground' : 'flex w-full shrink-0 cursor-pointer items-center gap-2 py-2 text-sm font-medium text-foreground'">
                <span [class]="boxClass(allSel() || someSel())">
                  @if (allSel()) {
                    <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" class="size-3.5"><path d="M3.5 8.5l3 3 6-7" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round" /></svg>
                  } @else if (someSel()) {
                    <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" class="size-3.5"><path d="M4 8h8" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" /></svg>
                  }
                </span>
                @if (!searchable()) { {{ t().selectAll }} }
              </button>
              @if (searchable()) { <span class="w-px shrink-0 self-stretch bg-border" aria-hidden="true"></span> }
            }
            @if (searchable()) {
              <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" class="size-4 shrink-0 text-muted-foreground"><circle cx="7" cy="7" r="4.5" stroke="currentColor" stroke-width="1.6" /><path d="M11 11l3 3" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" /></svg>
              <input #search data-bpdm-slot="multi-select-search" [value]="query()" (input)="onSearch($any($event.target).value)" [attr.placeholder]="searchPlaceholder()" [attr.aria-label]="searchPlaceholder()" role="combobox" aria-expanded="true" aria-autocomplete="list" [attr.aria-controls]="listboxId" [attr.aria-activedescendant]="activeDescId()" class="h-9 w-full bg-transparent text-sm text-foreground placeholder:text-muted-foreground focus:outline-none" />
            }
          </div>
        }
        @if (rows().length === 0) {
          <div data-bpdm-slot="multi-select-empty" class="px-3 py-6 text-center text-sm text-muted-foreground">{{ emptyText() }}</div>
        } @else {
          <cdk-virtual-scroll-viewport #viewport data-bpdm-slot="multi-select-list" role="listbox" aria-multiselectable="true" tabindex="-1" [attr.id]="listboxId" [attr.aria-label]="ariaLabel() || placeholder()" [attr.aria-activedescendant]="searchable() ? null : activeDescId()" [itemSize]="36" [style.height.px]="viewportHeight()" class="overflow-auto px-1 focus:outline-none">
            <ng-container *cdkVirtualFor="let r of rows(); let i = index">
              @if (r.kind === "group") {
                <div data-bpdm-slot="multi-select-group" aria-hidden="true" class="flex h-9 items-center gap-2 px-2 text-sm font-semibold text-foreground">{{ r.label }}</div>
              } @else {
                <button type="button" data-bpdm-slot="multi-select-option" role="option" [attr.id]="optionId(i)" [attr.aria-selected]="selectedSet().has(r.option.value)" [disabled]="r.option.disabled || null" (click)="toggle(r.option.value)" (mousemove)="active.set(i)" [class]="optionClass(i)">
                  <span [class]="boxClass(selectedSet().has(r.option.value))">
                    @if (selectedSet().has(r.option.value)) {
                      <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" class="size-3.5 animate-[bpdm-indicator-in_var(--bpdm-duration-base)_var(--bpdm-ease-overshoot)]"><path d="M3.5 8.5l3 3 6-7" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round" /></svg>
                    }
                  </span>
                  <span class="truncate">{{ r.option.label }}</span>
                </button>
              }
            </ng-container>
          </cdk-virtual-scroll-viewport>
        }
      </div>
    </ng-template>
  `,
})
export class BpdmMultiSelect implements OnDestroy {
  private readonly overlay = inject(Overlay);
  private readonly vcr = inject(ViewContainerRef);

  readonly options = input<SelectItems>([]);
  readonly value = model<string[]>([]);
  readonly defaultValue = input<string[]>([]);
  readonly placeholder = input("Select…");
  /** Show a filter box at the top of the dropdown. */
  readonly searchable = input(false, { transform: booleanAttribute });
  readonly searchPlaceholder = input("Search…");
  readonly emptyText = input("No results.");
  /** Max selected chips shown before "+N". 0 → show "N selected" count. Default 3. */
  readonly maxDisplay = input(3);
  /** Show a "Select all" row at the top of the dropdown. Default true. */
  readonly selectAll = input(true, { transform: booleanAttribute });
  /** Max height (px) of the scrollable option list. */
  readonly maxHeight = input(256);
  readonly size = input<FieldSize>("md");
  readonly disabled = input(false, { transform: booleanAttribute });
  readonly ariaInvalid = input(false, { alias: "aria-invalid", transform: booleanAttribute });
  readonly classInput = input("", { alias: "class" });
  readonly id = input("");
  /** Accessible name for the trigger + option list — pass a translated string. */
  readonly ariaLabel = input("", { alias: "aria-label" });
  readonly ariaDescribedby = input("", { alias: "aria-describedby" });
  /** Screen-reader labels + count text — override for i18n. */
  readonly messages = input<{
    selectAll?: string;
    clearAll?: string;
    remove?: (label: string) => string;
    selected?: (count: number) => string;
  }>({});

  protected readonly t = computed(() => ({
    selectAll: "Select all",
    clearAll: "Clear all",
    remove: (l: string) => `Remove ${l}`,
    selected: (n: number) => `${n} selected`,
    ...this.messages(),
  }));

  protected readonly open = signal(false);
  protected readonly query = signal("");
  protected readonly active = signal(0);
  protected readonly panelWidth = signal(0);

  /** Stable ids linking trigger → listbox → active option (aria-activedescendant). */
  protected readonly baseId = `bpdm-multiselect-${(multiUid += 1)}`;
  protected readonly listboxId = `${this.baseId}-listbox`;
  protected optionId(index: number): string {
    return `${this.baseId}-opt-${index}`;
  }
  protected readonly activeDescId = computed(() => {
    const r = this.rows()[this.active()];
    return r?.kind === "item" ? this.optionId(this.active()) : null;
  });

  private readonly triggerEl = viewChild.required<ElementRef<HTMLElement>>("trigger");
  private readonly panelTpl = viewChild.required<TemplateRef<unknown>>("panel");
  private readonly searchEl = viewChild<ElementRef<HTMLInputElement>>("search");
  private readonly viewport = viewChild<CdkVirtualScrollViewport>("viewport");
  private overlayRef?: OverlayRef;
  private seeded = false;

  constructor() {
    // seed the selection from defaultValue once (uncontrolled use)
    effect(() => {
      const dv = this.defaultValue();
      untracked(() => {
        if (!this.seeded) {
          this.seeded = true;
          if (dv.length) this.value.set([...dv]);
        }
      });
    });
  }

  protected readonly selected = computed(() => this.value());
  protected readonly selectedSet = computed(() => new Set(this.value()));
  private readonly allRows = computed(() => flattenSelectRows(this.options()));
  protected readonly rows = computed(() => filterSelectRows(this.allRows(), this.query()));
  private readonly optionByValue = computed(() => {
    const m = new Map<string, SelectOption>();
    for (const r of this.allRows()) if (r.kind === "item") m.set(r.option.value, r.option);
    return m;
  });
  protected readonly chips = computed(() => {
    if (this.maxDisplay() <= 0) return [];
    const m = this.optionByValue();
    return this.value()
      .map((v) => m.get(v))
      .filter((o): o is SelectOption => !!o)
      .slice(0, this.maxDisplay());
  });
  protected readonly extra = computed(() => {
    const m = this.optionByValue();
    const total = this.value().filter((v) => m.has(v)).length;
    return total - this.chips().length;
  });
  protected readonly filteredValues = computed(() => {
    const out: string[] = [];
    for (const r of this.rows()) if (r.kind === "item" && !r.option.disabled) out.push(r.option.value);
    return out;
  });
  protected readonly allSel = computed(() => {
    const f = this.filteredValues();
    return f.length > 0 && f.every((v) => this.selectedSet().has(v));
  });
  protected readonly someSel = computed(
    () => !this.allSel() && this.filteredValues().some((v) => this.selectedSet().has(v)),
  );
  protected readonly viewportHeight = computed(() =>
    Math.min(this.maxHeight(), this.rows().length * ROW_H),
  );

  protected readonly triggerClass = computed(() =>
    cn(FIELD_TRIGGER_BASE, FIELD_TRIGGER_SIZE[this.size()], "group", this.classInput()),
  );
  protected readonly panelClass = computed(() => FIELD_PANEL);

  protected boxClass(on: boolean): string {
    return cn(
      "grid size-4 shrink-0 place-items-center rounded-[4px] border transition-colors duration-[var(--bpdm-duration-fast)]",
      on ? "border-primary bg-primary text-primary-foreground" : "border-muted-foreground",
    );
  }
  protected optionClass(i: number): string {
    return cn(
      "flex h-9 w-full cursor-pointer items-center gap-2 rounded-[calc(var(--radius)-3px)] px-2 text-start text-sm text-foreground transition-colors duration-[var(--bpdm-duration-fast)] disabled:pointer-events-none disabled:opacity-50",
      // keyboard-active / hovered row: an amber inline-start bar (ring token, ≥3:1
      // in every theme) + soft tint + weight — clearly perceptible where bg-muted
      // alone was ~1.05:1. RTL-safe (logical shadow mirror), jitter-free (inset).
      i === this.active() &&
        "bg-[var(--bpdm-option-active-bg)] font-medium shadow-[inset_2px_0_0_0_var(--bpdm-option-active-bar)] rtl:shadow-[inset_-2px_0_0_0_var(--bpdm-option-active-bar)]",
    );
  }

  protected toggle(val?: string): void {
    if (val === undefined) {
      if (this.open()) this.close();
      else this.openPanel();
      return;
    }
    const has = this.selectedSet().has(val);
    this.value.set(has ? this.value().filter((v) => v !== val) : [...this.value(), val]);
  }

  protected clearAll(): void {
    this.value.set([]);
  }

  protected toggleAll(): void {
    const f = this.filteredValues();
    if (this.allSel()) {
      this.value.set(this.value().filter((v) => !f.includes(v)));
    } else {
      this.value.set(Array.from(new Set([...this.value(), ...f])));
    }
  }

  private openPanel(): void {
    if (this.disabled() || this.overlayRef) return;
    const trigger = this.triggerEl().nativeElement;
    this.panelWidth.set(trigger.offsetWidth);
    const positionStrategy = this.overlay
      .position()
      .flexibleConnectedTo(trigger)
      .withPositions([
        { originX: "start", originY: "bottom", overlayX: "start", overlayY: "top", offsetY: 4 },
        { originX: "start", originY: "top", overlayX: "start", overlayY: "bottom", offsetY: -4 },
      ])
      .withFlexibleDimensions(false)
      .withPush(false);
    this.overlayRef = this.overlay.create({
      positionStrategy,
      scrollStrategy: this.overlay.scrollStrategies.reposition(),
    });
    this.overlayRef.attach(new TemplatePortal(this.panelTpl(), this.vcr));
    this.open.set(true);
    this.resetActive();
    this.overlayRef.outsidePointerEvents().subscribe((e) => {
      if (!trigger.contains(e.target as Node)) this.close();
    });
    setTimeout(() => {
      this.viewport()?.checkViewportSize();
      const search = this.searchEl()?.nativeElement;
      // focus the search box (editable combobox) or the listbox itself, so
      // aria-activedescendant is announced from the focused element
      if (search) search.focus();
      else this.viewport()?.elementRef.nativeElement.focus();
    });
  }

  protected close(): void {
    this.overlayRef?.dispose();
    this.overlayRef = undefined;
    this.open.set(false);
    this.query.set("");
    this.triggerEl().nativeElement.focus();
  }

  protected onSearch(v: string): void {
    this.query.set(v);
    this.resetActive();
  }

  private resetActive(): void {
    const first = this.rows().findIndex((r) => r.kind === "item");
    this.active.set(first === -1 ? 0 : first);
  }

  private move(dir: 1 | -1): void {
    const rows = this.rows();
    let i = this.active();
    do {
      i += dir;
    } while (i >= 0 && i < rows.length && rows[i].kind === "group");
    if (i < 0 || i >= rows.length) return;
    this.active.set(i);
    this.viewport()?.scrollToIndex(i, "smooth");
  }

  protected onTriggerKeydown(e: KeyboardEvent): void {
    if (this.disabled()) return;
    if (!this.open() && (e.key === "Enter" || e.key === " " || e.key === "ArrowDown")) {
      e.preventDefault();
      this.openPanel();
    } else if ((e.key === "Backspace" || e.key === "Delete") && this.value().length > 0) {
      // remove the last selected chip straight from the (focused) trigger
      e.preventDefault();
      this.value.set(this.value().slice(0, -1));
    }
  }

  protected onKeydown(e: KeyboardEvent): void {
    if (e.key === "ArrowDown") {
      e.preventDefault();
      this.move(1);
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      this.move(-1);
    } else if (e.key === "Enter") {
      e.preventDefault();
      const r = this.rows()[this.active()];
      if (r?.kind === "item" && !r.option.disabled) this.toggle(r.option.value);
    } else if (e.key === "Escape") {
      e.preventDefault();
      this.close();
    }
  }

  ngOnDestroy(): void {
    this.overlayRef?.dispose();
  }
}
