// packages/react/src/components/popover.tsx
import * as React from "react";
import * as PopoverPrimitive from "@radix-ui/react-popover";
import { cn } from "@/lib/utils";

/** Close the popover from inside its content (wrap a button with `asChild`). */
export const PopoverClose = PopoverPrimitive.Close;

export interface PopoverProps {
  /** The trigger — a single focusable element (button, etc.). */
  trigger: React.ReactNode;
  /** Panel content. */
  children: React.ReactNode;
  side?: "top" | "right" | "bottom" | "left";
  align?: "start" | "center" | "end";
  /** Gap from the trigger, in px. Default 8. */
  sideOffset?: number;
  /** Fixed panel width, e.g. 280 or "20rem". Defaults to fit-content. */
  width?: number | string;
  /** Trap focus + block outside interaction (like a mini-modal). Default false. */
  modal?: boolean;
  /** Show a little arrow pointing at the trigger. Default false. */
  showArrow?: boolean;
  /** Draw a border around the panel. Default true; set false for a borderless panel. */
  bordered?: boolean;
  /**
   * Accessible name for the panel. A `role="dialog"` panel should carry an
   * accessible name; supply a (translatable) one here when the content has no
   * visible heading to name it. Optional — omit to leave the panel unnamed.
   */
  ariaLabel?: string;
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  /** Classes on the panel — override padding, width, etc. */
  className?: string;
}

/**
 * Click-triggered floating panel built on Radix — accessible, portaled (escapes
 * `overflow: hidden`), collision-aware, and theme-aware. Low-config: pass a
 * `trigger` and the panel content as children. Use `PopoverClose` inside the
 * content to add a close/confirm button.
 */
export function Popover({
  trigger,
  children,
  side = "bottom",
  align = "center",
  sideOffset = 8,
  width,
  modal = false,
  showArrow = false,
  bordered = true,
  ariaLabel,
  open,
  defaultOpen,
  onOpenChange,
  className,
}: PopoverProps) {
  // portal into the nearest dialog (if any) so the panel stays interactive
  // inside a modal; outside a dialog this is null → defaults to <body>
  const triggerRef = React.useRef<HTMLButtonElement>(null);
  const [portalContainer, setPortalContainer] = React.useState<HTMLElement | null>(null);
  React.useEffect(() => {
    setPortalContainer(triggerRef.current?.closest<HTMLElement>("[role='dialog']") ?? null);
  }, []);

  return (
    <PopoverPrimitive.Root
      open={open}
      defaultOpen={defaultOpen}
      onOpenChange={onOpenChange}
      modal={modal}
    >
      <PopoverPrimitive.Trigger asChild ref={triggerRef}>
        {trigger}
      </PopoverPrimitive.Trigger>
      <PopoverPrimitive.Portal container={portalContainer ?? undefined}>
        <PopoverPrimitive.Content
          aria-label={ariaLabel}
          side={side}
          align={align}
          sideOffset={sideOffset}
          collisionPadding={8}
          style={width !== undefined ? { width } : undefined}
          className={cn(
            "z-50 rounded-[var(--radius)] bg-popover p-4 text-popover-foreground shadow-lg outline-none",
            bordered && "border border-border",
            "origin-[var(--radix-popover-content-transform-origin)] data-[state=open]:animate-[bpdm-pop-in_var(--bpdm-duration-fast)_var(--bpdm-ease-out)] data-[state=closed]:animate-[bpdm-pop-out_var(--bpdm-duration-fast)_ease-in]",
            className,
          )}
        >
          {children}
          {showArrow && (
            // fill matches the panel; when bordered, a border-coloured stroke keeps
            // the notch visible against any background and consistent with the edge
            <PopoverPrimitive.Arrow
              className={cn("fill-popover", bordered && "stroke-border [stroke-width:1px]")}
              width={12}
              height={6}
            />
          )}
        </PopoverPrimitive.Content>
      </PopoverPrimitive.Portal>
    </PopoverPrimitive.Root>
  );
}

// packages/angular/src/lib/popover/popover.ts
import { NgTemplateOutlet } from "@angular/common";
import {
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  ComponentRef,
  computed,
  Directive,
  effect,
  ElementRef,
  inject,
  InjectionToken,
  Injector,
  input,
  model,
  OnDestroy,
  TemplateRef,
  untracked,
  viewChild,
  ViewContainerRef,
} from "@angular/core";
import { CdkTrapFocus } from "@angular/cdk/a11y";
import { Directionality } from "@angular/cdk/bidi";
import { Overlay, OverlayRef } from "@angular/cdk/overlay";
import { ComponentPortal } from "@angular/cdk/portal";
import { cn } from "@bpdm/variants";
import {
  connectedPositions,
  OVERLAY_ARROW,
  OVERLAY_ORIGIN,
  type OverlayAlign,
  type OverlaySide,
  sideFromPair,
} from "../overlay/overlay";

export type PopoverSide = OverlaySide;
export type PopoverAlign = OverlayAlign;

let pid = 0;

/** Handle handed to the popover content so a close button can dismiss the panel. */
interface PopoverRef {
  close: () => void;
}
const BPDM_POPOVER_REF = new InjectionToken<PopoverRef>("BpdmPopoverRef");

/**
 * Dismiss the popover from inside its content — put it on any button.
 *
 * ```html
 * <button bpdmButton bpdmPopoverClose>Done</button>
 * ```
 */
@Directive({
  selector: "[bpdmPopoverClose]",
  host: { "(click)": "ref?.close()" },
})
export class BpdmPopoverClose {
  protected readonly ref = inject(BPDM_POPOVER_REF, { optional: true });
}

/** Internal styled panel rendered into the CDK overlay. Not part of the public API. */
@Component({
  selector: "bpdm-popover-panel",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgTemplateOutlet, CdkTrapFocus],
  host: { class: "contents" },
  template: `
    <div
      #panel
      role="dialog"
      tabindex="-1"
      [attr.id]="id()"
      [attr.aria-label]="ariaLabel() || null"
      [class]="boxClass()"
      [style.width]="widthStyle()"
      [cdkTrapFocus]="modal()"
      [cdkTrapFocusAutoCapture]="modal()"
    >
      <ng-container
        [ngTemplateOutlet]="tpl()!"
        [ngTemplateOutletContext]="ctx()"
        [ngTemplateOutletInjector]="injector()"
      />
      @if (showArrow()) {
        <span [class]="arrowClass()" aria-hidden="true">
          <svg width="12" height="6" viewBox="0 0 12 6" class="block fill-popover">
            <!-- open path (no base line) so the bordered stroke only outlines the
                 two visible sides — no seam where the arrow meets the panel -->
            <path
              d="M0 0L6 6L12 0"
              [attr.stroke]="bordered() ? 'var(--border)' : null"
              [attr.stroke-width]="bordered() ? 1 : null"
              stroke-linejoin="round"
            />
          </svg>
        </span>
      }
    </div>
  `,
})
class BpdmPopoverPanel {
  readonly tpl = input<TemplateRef<unknown> | null>(null);
  readonly ctx = input<unknown>(undefined);
  readonly injector = input<Injector | null>(null);
  readonly side = input<PopoverSide>("bottom");
  readonly showArrow = input(false);
  readonly bordered = input(true);
  readonly modal = input(false);
  readonly closing = input(false);
  readonly width = input<number | string | undefined>(undefined);
  readonly id = input("");
  readonly panelClassInput = input("");
  // a11y: a `role="dialog"` panel should carry an accessible name; this holds
  // the (translatable) one supplied when the content has no visible heading.
  readonly ariaLabel = input<string | undefined>(undefined);

  private readonly panel = viewChild<ElementRef<HTMLElement>>("panel");

  protected readonly arrowClass = computed(() => OVERLAY_ARROW[this.side()]);

  protected readonly widthStyle = computed(() => {
    const w = this.width();
    return w === undefined ? null : typeof w === "number" ? `${w}px` : w;
  });

  protected readonly boxClass = computed(() =>
    cn(
      "relative z-50 rounded-[var(--radius)] bg-popover p-4 text-popover-foreground shadow-lg outline-none",
      this.bordered() && "border border-border",
      OVERLAY_ORIGIN[this.side()],
      this.closing()
        ? // `forwards` holds the faded-out frame until teardown — without it the
          // element snaps back to its visible base state for a frame (a flicker)
          "animate-[bpdm-pop-out_var(--bpdm-duration-fast)_ease-in_forwards]"
        : "animate-[bpdm-pop-in_var(--bpdm-duration-fast)_var(--bpdm-ease-out)]",
      this.panelClassInput(),
    ),
  );

  /** Move focus into the panel (non-modal case; the modal trap auto-captures). */
  focus(): void {
    this.panel()?.nativeElement.focus();
  }
}

/**
 * `bpdmPopover` — a click-triggered floating panel on any trigger, built on the
 * Angular CDK overlay (escapes `overflow: hidden` and CSS transforms),
 * collision-aware, and theme-aware. Pass the panel as a `TemplateRef`. Mirrors
 * the React `Popover`; use `bpdmPopoverClose` inside the content to dismiss it.
 *
 * ```html
 * <button bpdmButton [bpdmPopover]="panel">Open</button>
 * <ng-template #panel>
 *   <p>Anything can go here.</p>
 *   <button bpdmButton bpdmPopoverClose>Done</button>
 * </ng-template>
 * ```
 */
@Directive({
  selector: "[bpdmPopover]",
  exportAs: "bpdmPopover",
  host: {
    "(click)": "toggle()",
    "(keydown.escape)": "close()",
    "[attr.aria-haspopup]": "'dialog'",
    "[attr.aria-expanded]": "open()",
    "[attr.aria-controls]": "open() ? panelId : null",
  },
})
export class BpdmPopover implements OnDestroy {
  private readonly overlay = inject(Overlay);
  private readonly host = inject<ElementRef<HTMLElement>>(ElementRef);
  private readonly vcr = inject(ViewContainerRef);
  private readonly parentInjector = inject(Injector);
  // ambient text direction — fed to the overlay so `align="start"/"end"` resolve
  // to physical left/right correctly (they flip under `dir="rtl"`).
  private readonly directionality = inject(Directionality);

  /** The panel content. */
  readonly content = input<TemplateRef<unknown> | null>(null, { alias: "bpdmPopover" });
  readonly side = input<PopoverSide>("bottom", { alias: "bpdmPopoverSide" });
  readonly align = input<PopoverAlign>("center", { alias: "bpdmPopoverAlign" });
  /** Gap from the trigger, in px. Default 8. */
  readonly offset = input(8, { alias: "bpdmPopoverOffset" });
  /** Fixed panel width, e.g. 280 or "20rem". Defaults to fit-content. */
  readonly width = input<number | string | undefined>(undefined, { alias: "bpdmPopoverWidth" });
  /** Trap focus + block outside interaction (a mini-modal). Default false. */
  readonly modal = input(false, { alias: "bpdmPopoverModal", transform: booleanAttribute });
  /** Show a little arrow pointing at the trigger. Default false. */
  /** Draw a border around the panel. Default true; set false for a borderless panel. */
  readonly bordered = input(true, { alias: "bpdmPopoverBordered", transform: booleanAttribute });
  readonly showArrow = input(false, {
    alias: "bpdmPopoverShowArrow",
    transform: booleanAttribute,
  });
  readonly classInput = input("", { alias: "bpdmPopoverClass" });
  /**
   * Accessible name for the panel. A `role="dialog"` panel should carry an
   * accessible name; supply a (translatable) one here when the content has no
   * visible heading to name it. Optional — omit to leave the panel unnamed.
   */
  readonly ariaLabel = input<string | undefined>(undefined, { alias: "bpdmPopoverAriaLabel" });
  /** Open state — two-way bindable via `[(bpdmPopoverOpen)]`. */
  readonly open = model(false, { alias: "bpdmPopoverOpen" });

  protected readonly panelId = `bpdm-popover-${++pid}`;

  private overlayRef?: OverlayRef;
  private panelRef?: ComponentRef<BpdmPopoverPanel>;
  private closeTimer?: ReturnType<typeof setTimeout>;
  // return focus to the trigger on keyboard/programmatic close, but not when the
  // user clicked elsewhere (yanking focus back would fight where they clicked)
  private restoreFocus = true;

  constructor() {
    // `open` is the single source of truth; only track it (read the rest untracked)
    effect(() => {
      const want = this.open();
      untracked(() => (want ? this.show() : this.hide()));
    });
  }

  protected toggle(): void {
    if (this.content()) this.open.set(!this.open());
  }

  close(): void {
    this.open.set(false);
  }

  private show(): void {
    clearTimeout(this.closeTimer);
    const tpl = this.content();
    if (!tpl) return;
    if (this.overlayRef) {
      this.panelRef?.setInput("closing", false);
      return;
    }

    const positionStrategy = this.overlay
      .position()
      .flexibleConnectedTo(this.host)
      .withPositions(connectedPositions(this.side(), this.align(), this.offset()))
      .withPush(true);

    this.overlayRef = this.overlay.create({
      positionStrategy,
      scrollStrategy: this.overlay.scrollStrategies.reposition(),
      hasBackdrop: this.modal(),
      backdropClass: "cdk-overlay-transparent-backdrop",
      // without this the overlay defaults to LTR and `start`/`end` never flip
      direction: this.directionality,
    });

    const ref: PopoverRef = { close: () => this.close() };
    const tplInjector = Injector.create({
      providers: [{ provide: BPDM_POPOVER_REF, useValue: ref }],
      parent: this.parentInjector,
    });

    const p = this.overlayRef.attach(new ComponentPortal(BpdmPopoverPanel, this.vcr));
    this.panelRef = p;
    p.setInput("tpl", tpl);
    p.setInput("ctx", { $implicit: ref, close: ref.close });
    p.setInput("injector", tplInjector);
    p.setInput("side", this.side());
    p.setInput("showArrow", this.showArrow());
    p.setInput("bordered", this.bordered());
    p.setInput("modal", this.modal());
    p.setInput("width", this.width());
    p.setInput("panelClassInput", this.classInput());
    p.setInput("id", this.panelId);
    p.setInput("ariaLabel", this.ariaLabel());

    positionStrategy.positionChanges.subscribe((change) => {
      this.panelRef?.setInput("side", sideFromPair(change.connectionPair));
    });

    if (this.modal()) {
      this.overlayRef.backdropClick().subscribe(() => this.close());
    } else {
      this.overlayRef.outsidePointerEvents().subscribe((e) => {
        if (!this.host.nativeElement.contains(e.target as Node)) {
          this.restoreFocus = false;
          this.close();
        }
      });
      // move focus into the panel without trapping (so the user can still tab out)
      setTimeout(() => this.panelRef?.instance.focus(), 0);
    }
  }

  private hide(): void {
    if (!this.overlayRef) return;
    this.panelRef?.setInput("closing", true);
    const wasModal = this.modal();
    clearTimeout(this.closeTimer);
    this.closeTimer = setTimeout(() => {
      this.teardown();
      // modal focus-trap restores focus itself; restore it ourselves otherwise
      if (!wasModal && this.restoreFocus) this.host.nativeElement.focus();
      this.restoreFocus = true;
    }, 150);
  }

  private teardown(): void {
    this.overlayRef?.dispose();
    this.overlayRef = undefined;
    this.panelRef = undefined;
  }

  ngOnDestroy(): void {
    clearTimeout(this.closeTimer);
    this.teardown();
  }
}
