// packages/angular/src/lib/avatar/avatar.ts
import {
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  signal,
} from "@angular/core";
import {
  avatarInitials,
  avatarSize,
  avatarStatusColor,
  avatarTint,
  cn,
  type AvatarShape,
  type AvatarSize,
  type AvatarStatus,
} from "@bpdm/variants";

/**
 * `<bpdm-avatar>` — an image with a graceful fallback to initials (auto-tinted
 * from the name) and then a person icon. Circle or square, six sizes, an optional
 * presence dot. Same look as the React avatar.
 *
 * ```html
 * <bpdm-avatar name="Aria Lindqvist" src="/aria.jpg" status="online" />
 * <bpdm-avatar name="Theo Brandt" />  <!-- initials, auto-colored -->
 * ```
 */
@Component({
  selector: "bpdm-avatar",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { "[class]": "hostClass()" },
  template: `
    <span
      class="flex size-full items-center justify-center overflow-hidden"
      [class]="shape() === 'circle' ? 'rounded-full' : 'rounded-[28%]'"
      [class.ring-2]="ring()"
      [class.ring-background]="ring()"
    >
      @if (src() && !failed()) {
        <img
          [src]="src()"
          [alt]="alt() ?? name() ?? ''"
          (error)="failed.set(true)"
          class="size-full object-cover animate-[bpdm-fade-in_var(--bpdm-duration-base)_var(--bpdm-ease-out)]"
        />
      } @else {
        <span
          class="flex size-full items-center justify-center font-semibold animate-[bpdm-pop-in_var(--bpdm-duration-base)_var(--bpdm-ease-out)] [&_svg]:size-[55%]"
          [class]="tint()"
        >
          @if (initials()) {
            {{ initials() }}
          } @else {
            <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
              <circle cx="12" cy="8.5" r="3.5" fill="currentColor" />
              <path d="M4.5 19.5a7.5 7.5 0 0 1 15 0" stroke="currentColor" stroke-width="2" stroke-linecap="round" />
            </svg>
          }
        </span>
      }
    </span>

    @if (status()) {
      <span
        class="absolute z-10 rounded-full ring-2 ring-background size-[28%] min-h-2 min-w-2"
        [class]="statusDotClass()"
        [attr.aria-label]="status()"
      ></span>
    }
  `,
})
export class BpdmAvatar {
  /** Image URL. Falls back to initials, then a person icon, if it fails to load. */
  readonly src = input<string>();
  /** Name — drives the initials, the auto color, and the alt text. */
  readonly name = input<string>();
  readonly alt = input<string>();
  readonly size = input<AvatarSize>("md");
  readonly shape = input<AvatarShape>("circle");
  /** Presence dot: online / busy / away / offline. */
  readonly status = input<AvatarStatus>();
  /** Auto-tint initials from the name. Set false for a neutral look. */
  readonly colorful = input(true, { transform: booleanAttribute });
  /** Background-colored ring around the avatar (used by the group). */
  readonly ring = input(false, { transform: booleanAttribute });
  readonly classInput = input<string>("", { alias: "class" });

  protected readonly failed = signal(false);
  protected readonly initials = computed(() => {
    const n = this.name();
    return n ? avatarInitials(n) : "";
  });
  protected readonly tint = computed(() =>
    this.colorful() && this.initials()
      ? avatarTint(this.name() ?? "")
      : "bg-muted text-muted-foreground",
  );
  protected readonly statusDotClass = computed(() => {
    const st = this.status();
    if (!st) return "";
    return cn(
      avatarStatusColor[st],
      this.shape() === "circle" ? "bottom-[6%] right-[6%]" : "-bottom-0.5 -right-0.5",
    );
  });
  protected readonly hostClass = computed(() =>
    cn(
      "relative inline-flex shrink-0 select-none items-center justify-center overflow-visible",
      avatarSize[this.size()],
      this.classInput(),
    ),
  );
}

export interface AvatarGroupUser {
  name?: string;
  src?: string;
  status?: AvatarStatus;
}

/**
 * `<bpdm-avatar-group>` — an overlapping stack of avatars with a `+N` overflow
 * tile; each lifts on hover. Pass the people via `users` (an Angular-idiomatic
 * array rather than projected children).
 */
@Component({
  selector: "bpdm-avatar-group",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [BpdmAvatar],
  host: { class: "flex items-center" },
  template: `
    @for (u of shown(); track $index) {
      <bpdm-avatar
        [name]="u.name"
        [src]="u.src"
        [status]="u.status"
        [size]="size()"
        ring
        class="transition-transform duration-[var(--bpdm-duration-base)] ease-[var(--bpdm-ease-out)] hover:z-10 hover:-translate-y-1"
        [class.-ml-2.5]="$index > 0"
      />
    }
    @if (overflow() > 0) {
      <span
        class="relative -ml-2.5 inline-flex shrink-0 items-center justify-center rounded-full bg-muted font-semibold text-muted-foreground ring-2 ring-background transition-transform duration-[var(--bpdm-duration-base)] ease-[var(--bpdm-ease-out)] hover:z-10 hover:-translate-y-1"
        [class]="sizeClass()"
      >+{{ overflow() }}</span>
    }
  `,
})
export class BpdmAvatarGroup {
  readonly users = input.required<AvatarGroupUser[]>();
  /** Show at most this many avatars; the rest collapse into a "+N" tile. */
  readonly max = input<number>();
  readonly size = input<AvatarSize>("md");

  protected readonly shown = computed(() => {
    const m = this.max();
    return m ? this.users().slice(0, m) : this.users();
  });
  protected readonly overflow = computed(() => this.users().length - this.shown().length);
  protected readonly sizeClass = computed(() => avatarSize[this.size()]);
}

// src/components/avatar.tsx
import * as React from "react";
import * as AvatarPrimitive from "@radix-ui/react-avatar";
import { cn } from "@/lib/utils";

export type AvatarSize = "xs" | "sm" | "md" | "lg" | "xl" | "2xl";
export type AvatarShape = "circle" | "square";
export type AvatarStatus = "online" | "offline" | "busy" | "away";

const SIZE: Record<AvatarSize, string> = {
  xs: "size-6 text-[0.625rem]",
  sm: "size-8 text-xs",
  md: "size-10 text-sm",
  lg: "size-12 text-base",
  xl: "size-14 text-lg",
  "2xl": "size-16 text-xl",
};

const STATUS_COLOR: Record<AvatarStatus, string> = {
  online: "bg-success",
  offline: "bg-muted-foreground",
  busy: "bg-destructive",
  away: "bg-warning",
};

// deterministic, pleasant tint per name — so initials avatars aren't all grey
const PALETTE = [
  "bg-[color-mix(in_srgb,var(--info)_20%,transparent)] text-info",
  "bg-[color-mix(in_srgb,var(--success)_20%,transparent)] text-success",
  "bg-[color-mix(in_srgb,var(--accent)_22%,transparent)] text-accent",
  "bg-[color-mix(in_srgb,#8b5cf6_22%,transparent)] text-[#8b5cf6]",
  "bg-[color-mix(in_srgb,#ec4899_22%,transparent)] text-[#ec4899]",
  "bg-[color-mix(in_srgb,#14b8a6_22%,transparent)] text-[#14b8a6]",
];

function initialsOf(name: string) {
  const parts = name.trim().split(/\s+/).filter(Boolean);
  if (parts.length === 0) return "";
  if (parts.length === 1) return parts[0].slice(0, 2).toUpperCase();
  return (parts[0][0] + parts[parts.length - 1][0]).toUpperCase();
}

function hashOf(str: string) {
  let h = 0;
  for (let i = 0; i < str.length; i++) h = (h * 31 + str.charCodeAt(i)) >>> 0;
  return h;
}

export interface AvatarProps {
  /** Image URL. Falls back to initials, then the icon, if it fails to load. */
  src?: string;
  /** Person/entity name — drives the initials, the auto color, and the alt text. */
  name?: string;
  /** Icon shown when there's no image and no name. */
  icon?: React.ReactNode;
  alt?: string;
  size?: AvatarSize;
  shape?: AvatarShape;
  /** Presence dot: online / busy / away / offline. */
  status?: AvatarStatus;
  /** Auto-tint initials from the name. Default true. Set false for a neutral look. */
  colorful?: boolean;
  /** Draw a background-colored ring around the circle (used by AvatarGroup). */
  ring?: boolean;
  className?: string;
}

/**
 * Avatar built on Radix — shows an image with a graceful fallback to initials
 * (auto-tinted from the name) and then an icon. Circle or square, six sizes, an
 * optional presence dot. Compose with `NotificationBadge` for a count overlay.
 */
export const Avatar = React.forwardRef<
  React.ElementRef<typeof AvatarPrimitive.Root>,
  AvatarProps
>(
  (
    {
      src,
      name,
      icon,
      alt,
      size = "md",
      shape = "circle",
      status,
      colorful = true,
      ring = false,
      className,
    },
    ref,
  ) => {
    const initials = name ? initialsOf(name) : "";
    const tint =
      colorful && initials
        ? PALETTE[hashOf(name ?? "") % PALETTE.length]
        : "bg-muted text-muted-foreground";

    return (
      <AvatarPrimitive.Root
        ref={ref}
        className={cn(
          "relative inline-flex shrink-0 select-none items-center justify-center overflow-visible",
          SIZE[size],
          className,
        )}
      >
        <span
          className={cn(
            "flex size-full items-center justify-center overflow-hidden",
            shape === "circle" ? "rounded-full" : "rounded-[28%]",
            ring && "ring-2 ring-background",
          )}
        >
          {src && (
            <AvatarPrimitive.Image
              src={src}
              alt={alt ?? name ?? ""}
              className="size-full object-cover animate-[bpdm-fade-in_var(--bpdm-duration-base)_var(--bpdm-ease-out)]"
            />
          )}
          <AvatarPrimitive.Fallback
            delayMs={src ? 300 : 0}
            className={cn(
              "flex size-full items-center justify-center font-semibold animate-[bpdm-pop-in_var(--bpdm-duration-base)_var(--bpdm-ease-out)]",
              tint,
              "[&_svg]:size-[55%]",
            )}
          >
            {initials || icon || <DefaultUserIcon />}
          </AvatarPrimitive.Fallback>
        </span>

        {status && (
          <span
            className={cn(
              "absolute z-10 rounded-full ring-2 ring-background",
              STATUS_COLOR[status],
              // ~28% of the avatar, nudged onto the lower-right edge
              "size-[28%] min-h-2 min-w-2",
              shape === "circle" ? "bottom-[6%] right-[6%]" : "-bottom-0.5 -right-0.5",
            )}
            aria-label={status}
          />
        )}
      </AvatarPrimitive.Root>
    );
  },
);
Avatar.displayName = "Avatar";

function DefaultUserIcon() {
  return (
    <svg viewBox="0 0 24 24" fill="none" aria-hidden>
      <circle cx="12" cy="8.5" r="3.5" fill="currentColor" />
      <path
        d="M4.5 19.5a7.5 7.5 0 0 1 15 0"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
      />
    </svg>
  );
}

export interface AvatarGroupProps {
  children: React.ReactNode;
  /** Show at most this many avatars; the rest collapse into a "+N" tile. */
  max?: number;
  /** Applied to every avatar (and the overflow tile). */
  size?: AvatarSize;
  className?: string;
}

/**
 * Overlapping stack of avatars with a `+N` overflow tile. Each avatar lifts on
 * hover so the one under the cursor comes forward.
 */
export function AvatarGroup({ children, max, size = "md", className }: AvatarGroupProps) {
  const all = React.Children.toArray(children).filter(React.isValidElement);
  const shown = max ? all.slice(0, max) : all;
  const overflow = all.length - shown.length;

  return (
    <div className={cn("flex items-center", className)}>
      {shown.map((child, i) =>
        React.cloneElement(child as React.ReactElement<AvatarProps>, {
          key: i,
          size,
          ring: true,
          className: cn(
            (child as React.ReactElement<AvatarProps>).props.className,
            "transition-transform duration-[var(--bpdm-duration-base)] ease-[var(--bpdm-ease-out)] hover:z-10 hover:-translate-y-1",
            i > 0 && "-ml-2.5",
          ),
        }),
      )}
      {overflow > 0 && (
        <span
          className={cn(
            "relative -ml-2.5 inline-flex shrink-0 items-center justify-center rounded-full bg-muted font-semibold text-muted-foreground ring-2 ring-background transition-transform duration-[var(--bpdm-duration-base)] ease-[var(--bpdm-ease-out)] hover:z-10 hover:-translate-y-1",
            SIZE[size],
          )}
        >
          +{overflow}
        </span>
      )}
    </div>
  );
}
