// packages/angular/src/lib/input-otp/input-otp.ts
import {
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  input,
  model,
  viewChildren,
} from "@angular/core";
import { cn } from "@bpdm/variants";

export type InputOtpSize = "sm" | "md" | "lg";

const cellSize: Record<InputOtpSize, string> = {
  sm: "size-9 text-sm",
  md: "size-11 text-base",
  lg: "size-14 text-lg",
};

// Group sizes: explicit groupSize wins (last group = remainder); otherwise auto
// into 2 balanced groups (even → equal halves, odd → ceil + floor).
function getGroups(length: number, groupSize?: number, grouped?: boolean): number[] {
  if (groupSize && groupSize > 0) {
    const out: number[] = [];
    for (let i = 0; i < length; i += groupSize) out.push(Math.min(groupSize, length - i));
    return out;
  }
  if (grouped) {
    return length % 2 === 0
      ? [length / 2, length / 2]
      : [Math.ceil(length / 2), Math.floor(length / 2)];
  }
  return [length];
}

interface OtpCell {
  i: number;
  isFirst: boolean;
  isLast: boolean;
}

const BASE_CELL =
  "relative border border-input bg-background text-center font-medium text-foreground shadow-sm transition-[color,border-color,box-shadow,transform] duration-[var(--bpdm-duration-fast)] ease-[var(--bpdm-ease-overshoot)] focus:z-10 focus:scale-[1.08] focus:border-ring focus:outline-none focus:ring-1 focus:ring-ring disabled:cursor-not-allowed disabled:opacity-50";

/**
 * `<bpdm-input-otp>` — one-time-code input: one box per character with
 * auto-advance, backspace-to-previous, arrow navigation, and paste-to-fill.
 * Controlled (`[(value)]`) or uncontrolled (`defaultValue`); value is a string.
 *
 * ```html
 * <bpdm-input-otp [length]="6" integerOnly />
 * <bpdm-input-otp [length]="4" mask integerOnly />        <!-- hidden PIN -->
 * <bpdm-input-otp [(value)]="code" />
 * ```
 */
@Component({
  selector: "bpdm-input-otp",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: "inline-flex" },
  template: `
    @if (isGrouped()) {
      <div role="group" [attr.aria-label]="ariaLabel()" class="flex items-center gap-3">
        @for (group of groups(); track groupIndex; let groupIndex = $index) {
          @if (groupIndex > 0) {
            <span class="select-none px-1 text-muted-foreground">{{ separator() }}</span>
          }
          <div class="flex items-center">
            @for (cell of group; track cell.i) {
              <input
                #cellInput
                type="text"
                [attr.inputmode]="integerOnly() ? 'numeric' : 'text'"
                [attr.autocomplete]="cell.i === 0 ? 'one-time-code' : 'off'"
                data-1p-ignore
                data-lpignore="true"
                maxlength="1"
                [disabled]="disabled()"
                [attr.aria-label]="'Character ' + (cell.i + 1)"
                [value]="cells()[cell.i]"
                [style.-webkit-text-security]="mask() ? 'disc' : null"
                [class]="cellClass(cell)"
                (input)="onInput(cell.i, $any($event.target).value)"
                (keydown)="onKeydown(cell.i, $event)"
                (paste)="onPaste($event)"
                (focus)="$any($event.target).select()"
              />
            }
          </div>
        }
      </div>
    } @else {
      <div role="group" [attr.aria-label]="ariaLabel()" class="flex items-center gap-2">
        @for (cell of groups()[0]; track cell.i) {
          <input
            #cellInput
            type="text"
            [attr.inputmode]="integerOnly() ? 'numeric' : 'text'"
            [attr.autocomplete]="cell.i === 0 ? 'one-time-code' : 'off'"
            data-1p-ignore
            data-lpignore="true"
            maxlength="1"
            [disabled]="disabled()"
            [attr.aria-label]="'Character ' + (cell.i + 1)"
            [value]="cells()[cell.i]"
            [style.-webkit-text-security]="mask() ? 'disc' : null"
            [class]="cellClass(cell)"
            (input)="onInput(cell.i, $any($event.target).value)"
            (keydown)="onKeydown(cell.i, $event)"
            (paste)="onPaste($event)"
            (focus)="$any($event.target).select()"
          />
        }
      </div>
    }
  `,
})
export class BpdmInputOtp {
  /** Number of cells. */
  readonly length = input<number>(6);
  /** Controlled value — `[(value)]`. */
  readonly value = model<string | undefined>(undefined);
  /** Uncontrolled initial value. */
  readonly defaultValue = input<string>("");
  /** Hide characters (one-time PINs). */
  readonly mask = input(false, { transform: booleanAttribute });
  /** Restrict input to digits 0-9. */
  readonly integerOnly = input(false, { transform: booleanAttribute });
  readonly size = input<InputOtpSize>("md");
  /** Connect cells into fixed groups of this size (e.g. 3 → 3-3, last = remainder). */
  readonly groupSize = input<number | undefined>(undefined);
  /** Auto-group into 2 balanced segments. Ignored if `groupSize` is set. */
  readonly grouped = input(false, { transform: booleanAttribute });
  /** Character shown between groups. */
  readonly separator = input<string>("−");
  readonly disabled = input(false, { transform: booleanAttribute });
  readonly ariaLabel = input<string>("One-time code", { alias: "aria-label" });

  private readonly cellInputs = viewChildren<ElementRef<HTMLInputElement>>("cellInput");

  protected readonly isGrouped = computed(
    () => (!!this.groupSize() && this.groupSize()! > 0) || this.grouped(),
  );

  // re-sizes to the current `length` every render, so changing length grows /
  // shrinks the cells (works for a string source).
  protected readonly cells = computed<string[]>(() => {
    const v = this.value();
    const src = v === undefined ? this.defaultValue() : v;
    return Array.from({ length: this.length() }, (_, i) => src[i] ?? "");
  });

  protected readonly groups = computed<OtpCell[][]>(() => {
    const sizes = getGroups(this.length(), this.groupSize(), this.grouped());
    const out: OtpCell[][] = [];
    let offset = 0;
    for (const sz of sizes) {
      const group: OtpCell[] = [];
      for (let k = 0; k < sz; k++) {
        group.push({ i: offset + k, isFirst: k === 0, isLast: k === sz - 1 });
      }
      out.push(group);
      offset += sz;
    }
    return out;
  });

  protected cellClass(cell: OtpCell): string {
    return cn(
      BASE_CELL,
      cellSize[this.size()],
      this.isGrouped()
        ? cn(
            "rounded-none",
            !cell.isFirst && "-ml-px",
            cell.isFirst && "rounded-l-[var(--radius)]",
            cell.isLast && "rounded-r-[var(--radius)]",
          )
        : "rounded-[var(--radius)]",
    );
  }

  protected onInput(i: number, raw: string): void {
    const ch = raw.slice(-1);
    if (this.integerOnly() && ch && !/\d/.test(ch)) {
      // reject — restore the cell to its committed value
      this.syncCell(i);
      return;
    }
    const next = this.cells().slice();
    next[i] = ch;
    this.commit(next);
    if (ch) this.focusCell(i + 1);
  }

  protected onKeydown(i: number, e: KeyboardEvent): void {
    if (e.key === "Backspace") {
      e.preventDefault();
      const next = this.cells().slice();
      if (this.cells()[i]) {
        next[i] = "";
        this.commit(next);
        this.syncCell(i);
      } else if (i > 0) {
        next[i - 1] = "";
        this.commit(next);
        this.focusCell(i - 1);
      }
    } else if (e.key === "ArrowLeft") {
      e.preventDefault();
      this.focusCell(i - 1);
    } else if (e.key === "ArrowRight") {
      e.preventDefault();
      this.focusCell(i + 1);
    }
  }

  protected onPaste(e: ClipboardEvent): void {
    e.preventDefault();
    let chars = (e.clipboardData?.getData("text") ?? "").trim().split("");
    if (this.integerOnly()) chars = chars.filter((c) => /\d/.test(c));
    const len = this.length();
    const next = Array.from({ length: len }, (_, k) => chars[k] ?? "");
    this.commit(next);
    this.focusCell(Math.min(chars.length, len - 1));
  }

  private commit(next: string[]): void {
    this.value.set(next.join(""));
  }

  private focusCell(i: number): void {
    const idx = Math.max(0, Math.min(this.length() - 1, i));
    this.cellInputs()[idx]?.nativeElement.focus();
  }

  // restore a cell's DOM value to the committed model value (after a rejected
  // keystroke the native input keeps the typed char until we overwrite it)
  private syncCell(i: number): void {
    const el = this.cellInputs()[i]?.nativeElement;
    if (el) el.value = this.cells()[i] ?? "";
  }
}

// src/components/input-otp.tsx
import * as React from "react";
import { cn } from "@/lib/utils";

type Size = "sm" | "md" | "lg";

export interface InputOtpProps {
  /** Number of cells. */
  length?: number;
  value?: string;
  defaultValue?: string;
  onValueChange?: (value: string) => void;
  /** Hide characters (one-time PINs). */
  mask?: boolean;
  /** Restrict input to digits 0-9. */
  integerOnly?: boolean;
  size?: Size;
  /** Connect cells into fixed groups of this size (e.g. 3 → 3-3, last = remainder). */
  groupSize?: number;
  /** Auto-group into 2 balanced segments (even → equal, odd → ceil+floor). Ignored if `groupSize` is set. */
  grouped?: boolean;
  /** Node shown between groups. */
  separator?: React.ReactNode;
  disabled?: boolean;
  className?: string;
  "aria-label"?: string;
}

const cellSize: Record<Size, string> = {
  sm: "size-9 text-sm",
  md: "size-11 text-base",
  lg: "size-14 text-lg",
};

// Group sizes: explicit groupSize wins (last group = remainder); otherwise auto
// into 2 balanced groups (even → equal halves, odd → ceil + floor).
function getGroups(
  length: number,
  groupSize?: number,
  grouped?: boolean,
): number[] {
  if (groupSize && groupSize > 0) {
    const out: number[] = [];
    for (let i = 0; i < length; i += groupSize)
      out.push(Math.min(groupSize, length - i));
    return out;
  }
  if (grouped) {
    return length % 2 === 0
      ? [length / 2, length / 2]
      : [Math.ceil(length / 2), Math.floor(length / 2)];
  }
  return [length];
}

/**
 * One-time-code input: one box per character with auto-advance,
 * backspace-to-previous, arrow navigation, and paste-to-fill. Controlled
 * (`value` + `onValueChange`) or uncontrolled (`defaultValue`); value is a string.
 */
export function InputOtp({
  length = 6,
  value,
  defaultValue = "",
  onValueChange,
  mask = false,
  integerOnly = false,
  size = "md",
  groupSize,
  grouped,
  separator = "−",
  disabled,
  className,
  "aria-label": ariaLabel = "One-time code",
}: InputOtpProps) {
  const refs = React.useRef<(HTMLInputElement | null)[]>([]);
  const isControlled = value !== undefined;

  // re-sizes to the current `length` every render, so changing length grows/
  // shrinks the cells (works for a string or an array source).
  const toCells = (src: string | string[]) =>
    Array.from({ length }, (_, i) => src[i] ?? "");
  const [internal, setInternal] = React.useState<string[]>(() =>
    toCells(defaultValue),
  );
  const cells = toCells(isControlled ? (value ?? "") : internal);

  const commit = (next: string[]) => {
    if (!isControlled) setInternal(next);
    onValueChange?.(next.join(""));
  };

  const focusCell = (i: number) =>
    refs.current[Math.max(0, Math.min(length - 1, i))]?.focus();

  const handleChange = (i: number, raw: string) => {
    const ch = raw.slice(-1);
    if (integerOnly && ch && !/\d/.test(ch)) return;
    const next = cells.slice();
    next[i] = ch;
    commit(next);
    if (ch) focusCell(i + 1);
  };

  const handleKeyDown = (i: number, e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Backspace") {
      e.preventDefault();
      const next = cells.slice();
      if (cells[i]) {
        next[i] = "";
        commit(next);
      } else if (i > 0) {
        next[i - 1] = "";
        commit(next);
        focusCell(i - 1);
      }
    } else if (e.key === "ArrowLeft") {
      e.preventDefault();
      focusCell(i - 1);
    } else if (e.key === "ArrowRight") {
      e.preventDefault();
      focusCell(i + 1);
    }
  };

  const handlePaste = (e: React.ClipboardEvent<HTMLInputElement>) => {
    e.preventDefault();
    let chars = e.clipboardData.getData("text").trim().split("");
    if (integerOnly) chars = chars.filter((c) => /\d/.test(c));
    const next = Array.from({ length }, (_, k) => chars[k] ?? "");
    commit(next);
    focusCell(Math.min(chars.length, length - 1));
  };

  const isGrouped = (!!groupSize && groupSize > 0) || !!grouped;

  const baseCell =
    "border border-input bg-background text-center font-medium text-foreground shadow-sm transition-colors focus:z-10 focus:border-ring focus:outline-none focus:ring-1 focus:ring-ring disabled:cursor-not-allowed disabled:opacity-50";

  // isFirst/isLast = position within the cell's group (for connected rounding)
  const renderCell = (i: number, isFirst: boolean, isLast: boolean) => (
    <input
      key={i}
      ref={(el) => {
        refs.current[i] = el;
      }}
      // keep type=text (not password) so password managers don't hijack the
      // field; mask visually with -webkit-text-security instead.
      type="text"
      inputMode={integerOnly ? "numeric" : "text"}
      autoComplete={i === 0 ? "one-time-code" : "off"}
      data-1p-ignore
      data-lpignore="true"
      maxLength={1}
      disabled={disabled}
      aria-label={`Character ${i + 1}`}
      value={cells[i]}
      onChange={(e) => handleChange(i, e.target.value)}
      onKeyDown={(e) => handleKeyDown(i, e)}
      onPaste={handlePaste}
      onFocus={(e) => e.currentTarget.select()}
      style={
        mask ? ({ WebkitTextSecurity: "disc" } as React.CSSProperties) : undefined
      }
      className={cn(
        "relative",
        baseCell,
        cellSize[size],
        isGrouped
          ? cn(
              "rounded-none",
              !isFirst && "-ml-px", // collapse adjacent borders into one divider
              isFirst && "rounded-l-[var(--radius)]",
              isLast && "rounded-r-[var(--radius)]",
            )
          : "rounded-[var(--radius)]",
      )}
    />
  );

  if (!isGrouped) {
    return (
      <div
        role="group"
        aria-label={ariaLabel}
        className={cn("flex items-center gap-2", className)}
      >
        {cells.map((_, i) => renderCell(i, false, false))}
      </div>
    );
  }

  // grouped: connected segments with a separator between groups
  const sizes = getGroups(length, groupSize, grouped);
  let offset = 0;
  return (
    <div
      role="group"
      aria-label={ariaLabel}
      className={cn("flex items-center gap-3", className)}
    >
      {sizes.map((sz, g) => {
        const start = offset;
        offset += sz;
        return (
          <React.Fragment key={g}>
            {g > 0 && (
              <span className="select-none px-1 text-muted-foreground">
                {separator}
              </span>
            )}
            <div className="flex items-center">
              {Array.from({ length: sz }, (_, k) =>
                renderCell(start + k, k === 0, k === sz - 1),
              )}
            </div>
          </React.Fragment>
        );
      })}
    </div>
  );
}
