// packages/react/src/components/textarea.tsx
import * as React from "react";
import { textareaVariants, type VariantProps } from "@bpdm/variants";
import { cn } from "@/lib/utils";

export interface TextareaProps
  extends Omit<React.ComponentProps<"textarea">, "size">,
    VariantProps<typeof textareaVariants> {
  /** Grow to fit content (disables manual resize). */
  autoResize?: boolean;
  /** Show a character counter (pairs with `maxLength`). */
  showCount?: boolean;
}

export const Textarea = React.forwardRef<HTMLTextAreaElement, TextareaProps>(
  (
    {
      className,
      size,
      resize,
      autoResize,
      showCount,
      maxLength,
      value,
      defaultValue,
      onChange,
      "aria-describedby": ariaDescribedBy,
      ...props
    },
    ref,
  ) => {
    const innerRef = React.useRef<HTMLTextAreaElement>(null);
    React.useImperativeHandle(ref, () => innerRef.current as HTMLTextAreaElement);
    const [count, setCount] = React.useState(
      String(value ?? defaultValue ?? "").length,
    );
    // Link the counter to the field for screen readers (a static description, not a per-keystroke
    // live announcement). Preserves any consumer-supplied aria-describedby.
    const countId = `${React.useId()}-count`;
    const describedBy =
      [ariaDescribedBy, showCount ? countId : undefined].filter(Boolean).join(" ") || undefined;

    const adjust = React.useCallback(() => {
      const el = innerRef.current;
      if (!autoResize || !el) return;
      el.style.height = "auto";
      el.style.height = `${el.scrollHeight}px`;
    }, [autoResize]);

    React.useEffect(() => {
      adjust();
    }, [adjust]);
    React.useEffect(() => {
      if (value !== undefined) {
        setCount(String(value).length);
        adjust();
      }
    }, [value, adjust]);

    return (
      <div className="w-full">
        <textarea
          ref={innerRef}
          value={value}
          defaultValue={defaultValue}
          maxLength={maxLength}
          aria-describedby={describedBy}
          onChange={(e) => {
            setCount(e.target.value.length);
            adjust();
            onChange?.(e);
          }}
          data-bpdm="" data-bpdm-slot="textarea"
          className={cn(
            textareaVariants({ size, resize: autoResize ? "none" : resize }),
            className,
          )}
          {...props}
        />
        {showCount && (
          <div
            id={countId}
            data-bpdm-slot="textarea-count"
            className="mt-1 text-end text-xs tabular-nums text-muted-foreground"
          >
            {count}
            {maxLength != null ? ` / ${maxLength}` : ""}
          </div>
        )}
      </div>
    );
  },
);
Textarea.displayName = "Textarea";

export { textareaVariants };

// packages/angular/src/lib/textarea/textarea.ts
import {
  afterNextRender,
  booleanAttribute,
  Directive,
  ElementRef,
  Renderer2,
  computed,
  inject,
  input,
} from "@angular/core";
import { cn, textareaVariants, type TextareaVariants } from "@bpdm/variants";

/** Per-instance counter for a stable character-counter id (aria-describedby). */
let counterUid = 0;

/**
 * `bpdmTextarea` — styles a native `<textarea>` (three sizes, `resize` control).
 * Applied as an attribute so `ngModel` / reactive forms work natively. Set
 * `autoResize` to grow the field to fit its content. Set `showCount` to render a
 * character counter (pairs with `maxlength`) that's linked to the field via
 * `aria-describedby`. Invalid styling is driven by `aria-invalid="true"`.
 *
 * ```html
 * <textarea bpdmTextarea size="lg" autoResize [(ngModel)]="bio"></textarea>
 * <textarea bpdmTextarea showCount maxlength="120" [(ngModel)]="note"></textarea>
 * ```
 */
@Directive({
  selector: "textarea[bpdmTextarea]",
  host: {
    "data-bpdm": "",
    "data-bpdm-slot": "textarea",
    "[class]": "classes()",
    "[attr.aria-describedby]": "describedBy()",
    "(input)": "onInput()",
  },
})
export class BpdmTextarea {
  readonly size = input<NonNullable<TextareaVariants["size"]>>("md");
  readonly resize = input<NonNullable<TextareaVariants["resize"]>>("vertical");
  /** Grow to fit content (disables manual resize). */
  readonly autoResize = input(false, { transform: booleanAttribute });
  /** Show a character counter (pairs with `maxlength`). Mirrors React `showCount`. */
  readonly showCount = input(false, { transform: booleanAttribute });
  readonly classInput = input<string>("", { alias: "class" });

  private readonly el = inject<ElementRef<HTMLTextAreaElement>>(ElementRef);
  private readonly renderer = inject(Renderer2);

  /** Stable id linking the counter to the field via aria-describedby. */
  protected readonly countId = `bpdm-textarea-count-${(counterUid += 1)}`;
  private counterEl: HTMLElement | null = null;
  /** Any consumer-supplied `aria-describedby`, preserved and merged with the counter id. */
  private readonly initialDescribedBy = this.el.nativeElement.getAttribute("aria-describedby");

  protected readonly classes = computed(() =>
    cn(
      textareaVariants({
        size: this.size(),
        resize: this.autoResize() ? "none" : this.resize(),
      }),
      this.classInput(),
    ),
  );

  protected readonly describedBy = computed(() => {
    const parts = [this.initialDescribedBy, this.showCount() ? this.countId : null].filter(Boolean);
    return parts.length ? parts.join(" ") : null;
  });

  constructor() {
    // size to existing content + render the counter once the textarea is in the DOM
    afterNextRender(() => {
      this.adjust();
      if (this.showCount()) this.buildCounter();
    });
  }

  protected onInput(): void {
    this.adjust();
    this.updateCounter();
  }

  protected adjust(): void {
    if (!this.autoResize()) return;
    const el = this.el.nativeElement;
    el.style.height = "auto";
    el.style.height = `${el.scrollHeight}px`;
  }

  private buildCounter(): void {
    const el = this.el.nativeElement;
    const counter = this.renderer.createElement("div") as HTMLElement;
    this.renderer.setAttribute(counter, "id", this.countId);
    this.renderer.setAttribute(counter, "data-bpdm-slot", "textarea-count");
    for (const c of "mt-1 text-end text-xs tabular-nums text-muted-foreground".split(" ")) {
      this.renderer.addClass(counter, c);
    }
    // insert directly after the textarea so it reads as the field's description
    this.renderer.insertBefore(el.parentNode, counter, el.nextSibling);
    this.counterEl = counter;
    this.updateCounter();
  }

  private updateCounter(): void {
    if (!this.counterEl) return;
    const el = this.el.nativeElement;
    const max = el.maxLength;
    const text = max >= 0 ? `${el.value.length} / ${max}` : `${el.value.length}`;
    this.renderer.setProperty(this.counterEl, "textContent", text);
  }
}
