// src/components/badge.tsx
import * as React from "react";
import { Slot } from "@radix-ui/react-slot";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "@/lib/utils";

export type BadgeVariant =
  | "neutral"
  | "primary"
  | "success"
  | "warning"
  | "info"
  | "destructive";

export type BadgeAppearance = "soft" | "solid" | "outline" | "ghost";

// the dot's true color, independent of the label color (so a `ghost` badge can
// keep a foreground label next to a colored status dot)
const DOT: Record<BadgeVariant, string> = {
  neutral: "bg-muted-foreground",
  primary: "bg-primary",
  success: "bg-success",
  warning: "bg-warning",
  info: "bg-info",
  destructive: "bg-destructive",
};

// color × appearance — `soft` (tinted, the default), `solid` (filled), `outline`.
// `ghost` is handled separately (no chrome: just a dot + label).
const TONE: Record<BadgeVariant, Record<"soft" | "solid" | "outline", string>> = {
  neutral: {
    soft: "border-transparent bg-muted text-foreground",
    solid: "border-transparent bg-foreground text-background",
    outline: "border-border text-foreground",
  },
  primary: {
    soft: "border-transparent bg-[color-mix(in_srgb,var(--primary)_18%,transparent)] text-primary",
    solid: "border-transparent bg-primary text-primary-foreground",
    outline: "border-primary/40 text-primary",
  },
  success: {
    soft: "border-transparent bg-[color-mix(in_srgb,var(--success)_18%,transparent)] text-success",
    solid: "border-transparent bg-success text-success-foreground",
    outline: "border-success/40 text-success",
  },
  warning: {
    soft: "border-transparent bg-[color-mix(in_srgb,var(--warning)_18%,transparent)] text-warning",
    solid: "border-transparent bg-warning text-warning-foreground",
    outline: "border-warning/40 text-warning",
  },
  info: {
    soft: "border-transparent bg-[color-mix(in_srgb,var(--info)_18%,transparent)] text-info",
    solid: "border-transparent bg-info text-info-foreground",
    outline: "border-info/40 text-info",
  },
  destructive: {
    soft: "border-transparent bg-[color-mix(in_srgb,var(--destructive)_18%,transparent)] text-destructive",
    solid: "border-transparent bg-destructive text-destructive-foreground",
    outline: "border-destructive/40 text-destructive",
  },
};

const badgeVariants = cva(
  "inline-flex w-fit items-center gap-1 whitespace-nowrap rounded-full border font-medium transition-[color,background-color,border-color,transform] duration-[var(--bpdm-duration-fast)] [&>svg]:size-3 [&>svg]:shrink-0",
  {
    variants: {
      size: {
        sm: "h-5 px-2 text-[0.6875rem]",
        md: "h-6 px-2.5 text-xs",
      },
    },
    defaultVariants: { size: "md" },
  },
);

export interface BadgeProps
  extends React.HTMLAttributes<HTMLSpanElement>,
    VariantProps<typeof badgeVariants> {
  variant?: BadgeVariant;
  appearance?: BadgeAppearance;
  /** Leading status dot, tinted to the variant. */
  dot?: boolean;
  /** Animate the dot with a pulse ring — for "live" / in-progress status. */
  pulse?: boolean;
  /** Show a remove button; the badge collapses + fades out, then calls this. */
  onRemove?: () => void;
  /** Render as the child element (e.g. an <a>) instead of a <span>. */
  asChild?: boolean;
}

export const Badge = React.forwardRef<HTMLSpanElement, BadgeProps>(
  (
    {
      className,
      variant = "neutral",
      appearance = "soft",
      size,
      dot = false,
      pulse = false,
      onRemove,
      asChild = false,
      children,
      onClick,
      ...props
    },
    ref,
  ) => {
    const [removing, setRemoving] = React.useState(false);
    const interactive = asChild || !!onClick;
    const ghost = appearance === "ghost";
    // ghost = no chrome (transparent, no border/padding); else the tinted/solid/outline tone
    const toneClass = ghost
      ? "border-transparent bg-transparent text-foreground"
      : TONE[variant][appearance];
    const ghostClass = ghost && "h-auto gap-1.5 px-0 text-sm font-normal";

    // asChild path: style the child only (no dot/remove affordances)
    if (asChild) {
      return (
        <Slot
          ref={ref as React.Ref<HTMLElement>}
          className={cn(
            badgeVariants({ size }),
            toneClass,
            ghostClass,
            "cursor-pointer active:scale-[0.96]",
            className,
          )}
          onClick={onClick}
          {...props}
        >
          {children}
        </Slot>
      );
    }

    const badge = (
      <span
        ref={ref}
        onClick={onClick}
        className={cn(
          badgeVariants({ size }),
          toneClass,
          ghostClass,
          interactive && "cursor-pointer active:scale-[0.96]",
          // dynamic chips pop in on mount
          onRemove && "animate-[bpdm-pop-in_var(--bpdm-duration-base)_var(--bpdm-ease-out)]",
          className,
        )}
        {...props}
      >
        {dot && (
          <span className="relative flex size-2 shrink-0">
            {pulse && (
              <span
                className={cn(
                  "absolute inset-0 rounded-full animate-[bpdm-ping_1.8s_var(--bpdm-ease-out)_infinite]",
                  DOT[variant],
                )}
                aria-hidden
              />
            )}
            <span className={cn("size-2 rounded-full", DOT[variant])} />
          </span>
        )}
        {children}
        {onRemove && (
          <button
            type="button"
            aria-label="Remove"
            onClick={(e) => {
              e.stopPropagation();
              setRemoving(true);
            }}
            className="-mr-1 ml-0.5 inline-flex size-4 shrink-0 items-center justify-center rounded-full text-current opacity-60 transition-[color,background-color,opacity] hover:bg-foreground/10 hover:opacity-100 focus-visible:opacity-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
          >
            <svg viewBox="0 0 16 16" fill="none" className="size-2.5" aria-hidden>
              <path
                d="M4 4l8 8M12 4l-8 8"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
              />
            </svg>
          </button>
        )}
      </span>
    );

    if (!onRemove) return badge;

    // removable → collapse width + fade on remove, then fire onRemove
    return (
      <span
        className={cn(
          "inline-grid transition-all duration-[var(--bpdm-duration-base)] ease-[var(--bpdm-ease-out)]",
          removing ? "grid-cols-[0fr] opacity-0" : "grid-cols-[1fr] opacity-100",
        )}
        onTransitionEnd={(e) => {
          if (removing && e.propertyName === "grid-template-columns") onRemove();
        }}
      >
        <span className="min-w-0 overflow-hidden">{badge}</span>
      </span>
    );
  },
);
Badge.displayName = "Badge";

export interface NotificationBadgeProps {
  /** The element to overlay onto (an icon, an icon button, an avatar…). */
  children: React.ReactNode;
  /** Numeric count. Omit (with `dot`) for a plain indicator. */
  count?: number;
  /** Cap the displayed number, e.g. max=99 shows "99+". Default 99. */
  max?: number;
  /** Show a small dot instead of a number. */
  dot?: boolean;
  /** Still render when count is 0. Default false (0 hides the badge). */
  showZero?: boolean;
  variant?: BadgeVariant;
  className?: string;
}

/**
 * Overlays a count or dot on the corner of its child — the notification-style
 * indicator (a bell, an avatar, a button). The badge pops in on mount and
 * re-pops whenever the count changes.
 */
export function NotificationBadge({
  children,
  count,
  max = 99,
  dot = false,
  showZero = false,
  variant = "destructive",
  className,
}: NotificationBadgeProps) {
  const show = dot || (count !== undefined && (count > 0 || (count === 0 && showZero)));
  const label = dot
    ? null
    : count !== undefined
      ? count > max
        ? `${max}+`
        : String(count)
      : null;

  return (
    <span className={cn("relative inline-flex", className)}>
      {children}
      {show && (
        // outer span owns the placement (center sits on the icon's top-right
        // corner via translate) so it never fights the inner pop animation. A
        // small dot is nudged inward so it hugs the glyph instead of floating in
        // the icon's corner whitespace (a count badge is wide enough already).
        <span
          className={cn(
            "pointer-events-none absolute z-10 -translate-y-1/2 translate-x-1/2",
            dot ? "right-1 top-1" : "right-0 top-0",
          )}
        >
          <span
            // re-pops when the number changes
            key={label ?? "dot"}
            className={cn(
              "flex items-center justify-center rounded-full font-semibold leading-none ring-2 ring-background animate-[bpdm-indicator-in_var(--bpdm-duration-base)_var(--bpdm-ease-overshoot)]",
              TONE[variant].solid,
              dot ? "size-2.5" : "h-[1.125rem] min-w-[1.125rem] px-1 text-[0.625rem]",
            )}
          >
            {label}
          </span>
        </span>
      )}
    </span>
  );
}

export { badgeVariants };

// packages/angular/src/lib/badge/badge.ts
import {
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
  signal,
} from "@angular/core";
import {
  badgeDot,
  badgeTone,
  badgeVariants,
  cn,
  type BadgeAppearance,
  type BadgeVariant,
  type BadgeVariants,
} from "@bpdm/variants";

/**
 * `<bpdm-badge>` — a compact status/label chip. Six variants × four appearances
 * (`soft`/`solid`/`outline`/`ghost`), an optional status `dot` (with a `pulse`
 * ring for live states), and a `removable` chip that collapses + fades out.
 * Same tones as the React badge.
 *
 * ```html
 * <bpdm-badge variant="success" dot pulse>Live</bpdm-badge>
 * <bpdm-badge variant="primary" removable (removed)="drop()">Design</bpdm-badge>
 * ```
 */
@Component({
  selector: "bpdm-badge",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "[class]": "wrapperClass()",
    "(transitionend)": "onTransitionEnd($event)",
  },
  template: `
    <span [class]="removable() ? 'block min-w-0 overflow-hidden' : 'contents'">
      <span [class]="badgeClass()">
        @if (dot()) {
          <span class="relative flex size-2 shrink-0">
            @if (pulse()) {
              <span
                class="absolute inset-0 rounded-full animate-[bpdm-ping_1.8s_var(--bpdm-ease-out)_infinite]"
                [class]="dotColor()"
                aria-hidden="true"
              ></span>
            }
            <span class="size-2 rounded-full" [class]="dotColor()"></span>
          </span>
        }
        <ng-content />
        @if (removable()) {
          <button
            type="button"
            aria-label="Remove"
            (click)="remove($event)"
            class="-mr-1 ml-0.5 inline-flex size-4 shrink-0 cursor-pointer items-center justify-center rounded-full text-current opacity-60 transition-[color,background-color,opacity] hover:bg-foreground/10 hover:opacity-100 focus-visible:opacity-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
          >
            <svg viewBox="0 0 16 16" fill="none" class="size-2.5" aria-hidden="true">
              <path d="M4 4l8 8M12 4l-8 8" stroke="currentColor" stroke-width="2" stroke-linecap="round" />
            </svg>
          </button>
        }
      </span>
    </span>
  `,
})
export class BpdmBadge {
  readonly variant = input<BadgeVariant>("neutral");
  readonly appearance = input<BadgeAppearance>("soft");
  readonly size = input<NonNullable<BadgeVariants["size"]>>("md");
  /** Leading status dot, tinted to the variant. */
  readonly dot = input(false, { transform: booleanAttribute });
  /** Animate the dot with a pulse ring — for "live" / in-progress status. */
  readonly pulse = input(false, { transform: booleanAttribute });
  /** Interactive (cursor + press feedback) — pair with a `(click)`. */
  readonly interactive = input(false, { transform: booleanAttribute });
  /** Show a remove button; the badge collapses + fades, then emits `removed`. */
  readonly removable = input(false, { transform: booleanAttribute });
  readonly classInput = input<string>("", { alias: "class" });
  /** Fired after the badge has collapsed away. */
  readonly removed = output<void>();

  protected readonly removing = signal(false);

  protected readonly dotColor = computed(() => badgeDot[this.variant()]);

  protected readonly badgeClass = computed(() => {
    const ghost = this.appearance() === "ghost";
    const tone = ghost
      ? "border-transparent bg-transparent text-foreground"
      : badgeTone[this.variant()][this.appearance() as "soft" | "solid" | "outline"];
    return cn(
      badgeVariants({ size: this.size() }),
      tone,
      ghost && "h-auto gap-1.5 px-0 text-sm font-normal",
      this.interactive() && "cursor-pointer active:scale-[0.96]",
      this.removable() &&
        "animate-[bpdm-pop-in_var(--bpdm-duration-base)_var(--bpdm-ease-out)]",
      this.classInput(),
    );
  });

  protected readonly wrapperClass = computed(() => {
    if (!this.removable()) return "contents";
    return cn(
      "inline-grid transition-all duration-[var(--bpdm-duration-base)] ease-[var(--bpdm-ease-out)]",
      this.removing() ? "grid-cols-[0fr] opacity-0" : "grid-cols-[1fr] opacity-100",
    );
  });

  protected remove(event: Event): void {
    event.stopPropagation();
    this.removing.set(true);
  }

  protected onTransitionEnd(event: TransitionEvent): void {
    if (this.removing() && event.propertyName === "grid-template-columns") {
      this.removed.emit();
    }
  }
}

/**
 * `<bpdm-notification-badge>` — overlays a count or dot on the corner of its
 * content (a bell, an avatar, a button). Pops in on mount and re-pops when the
 * count changes.
 *
 * ```html
 * <bpdm-notification-badge [count]="5"><button …>🔔</button></bpdm-notification-badge>
 * ```
 */
@Component({
  selector: "bpdm-notification-badge",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: "relative inline-flex" },
  template: `
    <ng-content />
    @if (show()) {
      <span
        class="pointer-events-none absolute z-10 -translate-y-1/2 translate-x-1/2"
        [class]="dot() ? 'right-1 top-1' : 'right-0 top-0'"
      >
        <span
          class="flex items-center justify-center rounded-full font-semibold leading-none ring-2 ring-background animate-[bpdm-indicator-in_var(--bpdm-duration-base)_var(--bpdm-ease-overshoot)]"
          [class]="indicatorClass()"
        >{{ label() }}</span>
      </span>
    }
  `,
})
export class BpdmNotificationBadge {
  /** Numeric count. Omit (with `dot`) for a plain indicator. */
  readonly count = input<number>();
  /** Cap the displayed number, e.g. max=99 shows "99+". */
  readonly max = input(99);
  /** Show a small dot instead of a number. */
  readonly dot = input(false, { transform: booleanAttribute });
  /** Still render when count is 0. */
  readonly showZero = input(false, { transform: booleanAttribute });
  readonly variant = input<BadgeVariant>("destructive");

  protected readonly show = computed(() => {
    if (this.dot()) return true;
    const c = this.count();
    return c !== undefined && (c > 0 || (c === 0 && this.showZero()));
  });
  protected readonly label = computed(() => {
    if (this.dot()) return "";
    const c = this.count();
    if (c === undefined) return "";
    return c > this.max() ? `${this.max()}+` : String(c);
  });
  protected readonly indicatorClass = computed(() =>
    cn(
      badgeTone[this.variant()].solid,
      this.dot() ? "size-2.5" : "h-[1.125rem] min-w-[1.125rem] px-1 text-[0.625rem]",
    ),
  );
}
